### ISSUE TITLE
warc2zim tool

### ISSUE THREAD

**Issue by arjenpdevries** [openzim/libzim#109]
I was trying to find out if there exists any tools to convert between WARC and ZIM formats, but have trouble finding anything related.

Greetings,

Arjen

**Comment by kelson42** [comment]
@arjenpdevries We do not have this, but this would be quite good to have a converter warc2zim. Might be not so complicated to do.

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-tools#12
