### ISSUE TITLE
Support article's content bigger than 4Go.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#110]
`libzim` cannot handle article content bigger than 4Go.

All public API variables to store article's size are `zim::size_type` (defined to `uint32_t`).
There is also the size of the blog stored in an `unsigned` which is also a 32 bits integer.
It may have other place where a wrong integer size is used to store a content size. A full audit of libzim would be necessary.

Related to https://github.com/kiwix/kiwix-tools/issues/146

**Comment by kelson42** [comment]
This is quite a priority problem to fix - as soon as we have a bit of time.

**Comment by JonathanJonathanJonathan** [comment]
Are there any workarounds? Would love to deploy Kiwix next week in a rural district of africa where there is no internet, but it looks like that this bug prevents us from deploying any ZIM's larger as 4gb?

**Comment by kelson42** [comment]
@JonathanJonathanJonathan No, but this bug should be fixed really soon. Which file exactly are you dealing with?

**Comment by JonathanJonathanJonathan** [comment]
@kelson42 Cool! The file is https://dumps.wikimedia.org/kiwix/zim/wikipedia/wikipedia_en_all_nopic_2017-08.zim

Error:
root@prototype-apu:/var/kiwix# kiwix-manage library_zim.xml add [wikipedia_en_all_nopic_2017-08.zim](https://dumps.wikimedia.org/kiwix/zim/wikipedia/wikipedia_en_all_nopic_2017-08.zim)
article index out of range
Unable to build or save library file '/var/kiwix/library_zim.xml'

**Comment by kelson42** [comment]
@JonathanJonathanJonathan Your problem has nothing to do with that bug. It should work. Your ZIM file is corrupted or you use an extremely old version of kiwix-manage. Check with a version of the nightly build and check the md5sum of your ZIM file against https://download.kiwix.org/zim/wikipedia/wikipedia_en_all_nopic_2017-08.zim.mirrorlist. Please open a new ticket if you still have a (an other) problem.

**Comment by JonathanJonathanJonathan** [comment]
@kelson42 you're right, the md5 of my file is 3f8394f4edee6979ad703b3a81c3b032 and that one is different compared to the mirror list. Thanks again for your help!

**Comment by mgautierfr** [comment]
Fixed in #122
