### ISSUE TITLE
Remove dependency to icu4c.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#115]
We are using icu4c only here (https://github.com/openzim/libzim/blob/master/src/search.cpp#L80-L94) to get the ISO-639 **2 letters** language code from the **3 letters** language code stored in the database or in the zimfile.

It seems a pretty big dependency to convert a 3 letters code to a 2 letters code, especially when the 3 letters code comes from a information we control and made especially for this use case.

It would be better to directly store the 2 letters code in the database and use it directly.

We still would have to handle the compatibility with old zim containing 3 letters codes.
The transition from a 3 letters code to a 2 letters code seems to be most of the time to truncate the code to two letters.
There is some exceptions (<100) but it could be easily handle by a conversion map.
(https://fr.wikipedia.org/wiki/Liste_des_codes_ISO_639-1)
If we decide to support only zim we have created (I don't know if we have to do it), it may be even less.

@kelson42 what do you think about this ? It is you who have mainly create the search code in kiwix-lib.
Do I've missed something ?

**Comment by kelson42** [comment]
The ZIM std says we use 3 letters ISO code. The two letters iso codes have a lot of weaknesses.

**Comment by mgautierfr** [comment]
There is two place where the 3 letters code is stored :
- In the zim itself
- In the fulltext index database metadata.

The second one is only used to instantiate the xapian stemmer and the 3 letters codes is not recognized. If fact, it seems that very few language code is known by xapian (https://xapian.org/docs/apidoc/html/classXapian_1_1Stem.html#a6c46cedf2047b159a7e4c9d4468242b1).

We could store in the database the 2 letter code directly usable by xapian and keep the 3 letter code in the zim file.

**Comment by mgautierfr** [comment]
Well, we also used icu for the indexation step to remove accents on the titles.

For now, the indexation part is entirely in `zimwriterfs` but we plan to move this part into `libzim`.
So it is useless to remove icu dependency to readd it later.

Saying that, I wonder if this is a good idea to add indexation in libzim as it will create a dependency only used in very few case (only at zim creation).  Maybe we could investigate to see if it is possible to create two version of the libzim (one for reading, one for writing). Or any other idea.
Anyway, this is a open question and we will have time to discuss about this before we merge indexation in libzim and it is not the priority.

I'm leaving the discussion open as a reminder.

**Comment by kelson42** [comment]
@mgautierfr This might be better talked in https://github.com/openzim/libzim/issues/12

**Comment by kelson42** [comment]
@mgautierfr Good question. I'm not 100% sure about the answer. What I thin for now:
* It's a shame that are (more or less) the only group to create broadly use ZIM files and I want to fix that problem.
* We need more libzim bindings and toolsets and many of them will obviously want to benefit from the fulltext index feature (indexing+searching).
* To me, usage of libicu and libxapian are quite dependant (like we see in comments above). I do not really see the value of having one without having the other... and this for both ft indexing & searching (without forgetting geo indexing/searching).
* We have currently an option to build the libzim with Xapian. It might be an idea to move it to something like `--with-search` and this would include search feature and the libraries making them possible: `libicu` and `libxapian`.

**Comment by kelson42** [comment]
@mgautierfr Considering that we do (optional) Xapian indexing in the libzim now, I'm not sure this ticket is still valid. Do you?

**Comment by kelson42** [comment]
Closing the issue for now as the situation as singnificantly evolved since the time the ticket has been open.
