### ISSUE TITLE
[writer] Do not duplicate blob content while creating zim file.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#123]
Implementing #122, I've found that the blog content is duplicated while we create the zim file:

- zimwriterfs open the file and read the content in a buffer.
- when `zimcreator` add the blob to the cluster, the content is copied into the internal cluster buffer.
- Later on, the cluster is written in the zim file.

This is especially important for big files (xapian index) but it should make a speed improvement if we do it for all files.

One solution could be to rewrite the `zim::writer::Cluster` class to not duplicate the content but keep a reference to the original content and write directly the original content into the zim file. Even better for binary files, we could simply have a reference to the file path, this way it would be the `libzim` writer who open the file and copy it directly to the zim file. So big binary files would never be copied in memory at all.

However, we need to rewrite a bit how we handle memory management. `libzim` writer copy the content to allow `zimwriterfs` to reuse the article. If we keep a reference, we have to change this and be sure who is responsible of the data between `libzim` and `zimwriterfs`.

**Comment by kelson42** [comment]
@mgautierfr Might be a good moment to handle this
