### ISSUE TITLE
MacOS compilation issues

### ISSUE THREAD

**Issue by luhar** [openzim/libzim#126]
I am running into an issue when trying to compile libzim.

Versions:
MacOS High Sierra version 10.13.3
zlib -> 1.2.11 
icu4c -> 60.2
xapian -> 1.4.5
automake -> 1.16.1
libtool -> 2.4.6_1
virtualenv -> 15.1.0
pkg-config -> 0.29.2
re2c -> 1.0.3

Here is the full output during compilation:
(libzim) $ mkdir build
(libzim) $ meson . build
The Meson build system
Version: 0.45.0
Source dir: .../wiki/libzim
Build dir: .../wiki/libzim/build
Build type: native build
Project name: libzim
Native C compiler: cc (clang 9.0.0 "Apple LLVM version 9.0.0 (clang-900.0.39.2)")
Native C++ compiler: c++ (clang 9.0.0 "Apple LLVM version 9.0.0 (clang-900.0.39.2)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Native dependency zlib found: YES 1.2.8
Native dependency liblzma found: YES 5.2.3
Native dependency xapian-core found: YES 1.4.5
Dependency threads found: YES
Dependency icu-i18n found: NO

meson.build:30:4: ERROR: Dependency 'icu-i18n' not found, tried Extra Frameworks and Pkg-Config:

Native dependency 'icu-i18n' not found

---

Please let me know what steps I should take.

**Comment by luhar** [comment]
I resolved the icu-i18n dependency issue but am not sure why the cython3 dependency is not found. I have installed cython using pip and have aliased it to cython3.

**Comment by kelson42** [comment]
@luhar We have officially added the support of macos in libzim 3.3.0. If you still have problem please reopen the ticket and push your new log.
