### ISSUE TITLE
Add support for SBR (Shared Brotli) compression format

### ISSUE THREAD

**Issue by mossroy** [openzim/libzim#144]
Suggested by @eustas in https://github.com/kiwix/kiwix-js/issues/240 : 

> FYI
> We are working on standardization of the new content encoding "sbr" = "shared brotli"; basically, this allows using of language-specific dictionaries and LZ77 prefix dictionaries. Our early experiments with wikipedia pages has shown that with topic-specific dictionary, compression ratio is ~2.48x better than gzip -9.

**Comment by data-man** [comment]
Related issue: https://github.com/openzim/libzim/issues/84

**Comment by kelson42** [comment]
@mossroy @data-man Miy global attitude regarding the support of additional algorithm is that these algorithm should be really stabilised and proven to add a real benefit in comparison to LZMA. Which means a prototype of libzim include this compression/decompression backend needs to be done. This is not too complicated, but in general the core team does not really have the time to work on that.

**Comment by data-man** [comment]
@kelson42 
Just an idea: new tool (zim-recompress, e.g.).
It will help to understand the benefits.

**Comment by kelson42** [comment]
> @kelson42
> Just an idea: new tool (zim-recompress, e.g.).
> It will help to understand the benefits.

@mgautierfr had the same idea and made it, cf. https://github.com/openzim/zim-tools/blob/master/src/zimrecreate.cpp

**Comment by kelson42** [comment]
We are moving on zstd and I don't see the real value to go further with implementing SBR. I will close this ticket.

**Comment by kelson42** [comment]
Interesting article https://www.peazip.org/fast-compression-benchmark-brotli-zstandard.html

**Comment by JensKorte** [comment]
A comprehensive list with best compression by different programs. <http://mattmahoney.net/dc/text.html> The test file is "enwik9: compressed size of first 10^9 bytes of enwiki-20060303-pages-articles.xml."

The (second) last column contains the main compression algorithm used. xz is quite good for LZ77, only two other programs are better. Better programs use content mixing (CM), Burrows-Wheeler Transformation, dictionary and LSTM, which is a kind of CM and Prediction by Partial Match.



## Interesting compression programs which compress better then xz and have high decompression speed
### BWT
* nanozipltcb 30ns/byte
* pcompress  74ns/byte

### Dictionary
* glza: 11.9ns/byte

### LZ77
* xz 20ns/byte
* plzma 55 ns/byte
* lzturbo 1.1 9ns/byte
