### ISSUE TITLE
Delete "subprojects" directory / GoogleTest source code from the git repo

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#151]
This is not part of the project. This should be installed as dep with a reliable system. README should be updated if not trivial.

**Comment by kelson42** [comment]
@mgautierfr Assuming we are happy with GoogleTest solution for testing our C++ code for all our C++ based repositories. I think this has to be implemented first. Copying GoogleTest source code was on the edge for this repo., I could hardly support such an approach for all our repos.

**Comment by mgautierfr** [comment]
Removed with #258
