### ISSUE TITLE
zimwriterfs fails when processing a soft-link for CSS file

### ISSUE THREAD

**Issue by julianharty** [openzim/libzim#16]
Here's what I know, the bug may be more general or very specific to my case. More testing could help identify the extent, for instance to see if the same behavior happens when using soft-links for images, html, etc.

# Ingredients:

* zimwriterfs (I used the current Docker Image that contains it). Note I added a shared folder so I could easily share data between the running Docker image and my macbook. This had to be configured using the command line. See https://github.com/rocker-org/rocker/wiki/Sharing-files-with-host-machine for tips on how to do this.
* some basic content. I generated it from the https://github.com/julianharty/testing-heuristics project (follow the instructions in the README)
* create a folder called `./A` in the `dist` folder
* create a soft-link using `ln -s` for style.css: `ln -s style.css A/style.css`
* run zimwriterfs with the following command (in the extract below) in the running Docker container.

Using a soft-link (`ls -s source-file destination-file`) caused `zimwriterfs` to report and error and fail as follows:
```
root@3090e980e81e:/# zimwriterfs  --uniqueNamespace  -w index.html -f icon.png -l EN -t "Testing Heuristics" -d "Early cut of the testing heuristics material." -c "Julian Harty" -p "Commercetest Ltd." /Volumes/shared/dist/ /Volumes/shared/th-ln.zim

create directory entries
collect articles
zimwriterfs: unable to open file at path: /Volumes/shared/dist/A/style.css
terminate called after throwing an instance of 'int'
Aborted
```
Copying the file and then re-running the identical `zimwriterfs` command worked (I had to delete the soft-link first).
```
rm A/style.css 
cp style.css A/
```

**Comment by julianharty** [comment]
REelocated from https://github.com/wikimedia/openzim/issues/9

**Comment by kelson42** [comment]
This is a bug in zimwriterfs, not in the zimlib.

**Comment by kelson42** [comment]
This issue was moved to openzim/zimwriterfs#9
