### ISSUE TITLE
Rename zimcreator.(h|cpp) to creator.(h|cpp)

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#173]
_From @kelson42 on July 7, 2018 9:23_

We are in the libzim, we know its about zim.

_Copied from original issue: openzim/mwoffliner#349_

**Comment by sameeriitkgp** [comment]
Hey,
Is this still open? Would love to get started and submit a pull request.
Awaiting reply.

**Comment by kelson42** [comment]
@sameeriitkgp No, we have a PR waiting to be merged.

**Comment by kelson42** [comment]
Fixed with #232
