### ISSUE TITLE
Error compiling in MacOS

### ISSUE THREAD

**Issue by Pedneri1** [openzim/libzim#181]
I am getting an issue when trying to compile libzim in MacOS

MacOS 10.13.5

The Meson build system
Version: 0.47.1
Build type: native build
Project name: libzim
Project version: 4.0.0
Native C compiler: cc (clang 9.0.0 "Apple LLVM version 9.0.0 (clang-900.0.38)")
Native C++ compiler: c++ (clang 9.0.0 "Apple LLVM version 9.0.0 (clang-900.0.38)")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Native dependency zlib found: YES 1.2.8
Native dependency liblzma found: YES 5.2.4
Native dependency xapian-core found: YES 1.4.7
Dependency threads found: YES
Dependency icu-i18n found: NO

meson.build:30:4: ERROR:  Dependency 'icu-i18n' not found, tried Extra Frameworks and Pkg-Config:

Native dependency 'icu-i18n' not found

**Comment by Pedneri1** [comment]
Thanks for your quick reply,

I installed libicu using brew and was getting this error,

Then I compiled from source
http://site.icu-project.org/download/62#TOC-ICU4C-Download
```
tar xzvf icu4c-62_1-src.tgz
cd icu/source
chmod +x runConfigureICU configure install-sh
./runConfigureICU MacOSX
make
sudo make install
```

 and it worked

**Comment by kelson42** [comment]
:)
