### ISSUE TITLE
zimlib fails reading clusters if they aren't written sequentially to the end of a zim file

### ISSUE THREAD

**Issue by vss-devel** [openzim/libzim#196]
zimlib 4.0.4 assumes that all clusters are to be written one after another at the end of a zim file. Based on this assumption src/fileimpl.cpp calculates a cluster's size before reading it:
```    offset_t clusterOffset(getClusterOffset(idx));
    cluster_index_t next_idx(idx.v + 1);
    offset_t nextClusterOffset( (next_idx < getCountClusters())
                                        ? getClusterOffset(next_idx).v
                                        : (header.hasChecksum())
                                            ? header.getChecksumPos()
                                            : zimFile->fsize().v );
    zsize_t clusterSize(nextClusterOffset.v - clusterOffset.v);
    log_debug("read cluster " << idx << " from offset " << clusterOffset);
    CompressionType comp;
    bool extended;
    std::shared_ptr<const Reader> reader = zimReader->sub_clusterReader(clusterOffset, clusterSize, &comp, &extended);
    cluster = std::shared_ptr<Cluster>(new Cluster(reader, comp, extended));
```
I'm not quite sure if its a requirement of the http://www.openzim.org/wiki/ZIM_file_format. At least I'm failing to find such a requirement there.

So, this version of zimlib fails if clusters are scattered irregularly across a zim file, because in this scenario a cluster size can not be calculated before reading its content.

A typical example:
```
Assertion failed at ../../SOURCE/libzim_release/src/cluster.cpp:85
 offset[107867] == reader->size().v[108592]
/tmp/.mount_kiwixzhGEza/usr/bin/../lib/libzim.so.4(_Z15_on_assert_failIjmEvPKcS1_S1_T_T0_S1_i+0x172) [0x7f119d7916e9]
```
Apparently it wasn't the case before as, for example, Kiwix Android 2.2 and Kiwix for Linux 0.9 do not have a problem with reading such a file. It doesn't seem to be a problem for Firefox Kiwix plugin version 2.4.0.

**Comment by mgautierfr** [comment]
Related to https://github.com/openzim/libzim/issues/189.

**Comment by mgautierfr** [comment]
I confirm it is a bug. I have a fix there : #210 

@vss-devel Where could I find zim files created by zimmer ?

**Comment by vss-devel** [comment]
@mgautierfr: here are a couple of files: https://www.dropbox.com/sh/vfb4ujhe3ryympe/AAAOzSvjar7mKNirUYVRyaGda?dl=0

**Comment by archenemies** [comment]
I'm looking into Zimmer because Mwoffliner currently lacks TOC.

Thanks for the Maori Wiktionary example file. It doesn't crash `kiwix-serve` and I can look at the root page (running Linux). However, the search feature doesn't work, and I don't know the URL format for pages, so I can't examine an individual page to see if I want to proceed. Any tips?

    kiwix-serve -p 8080 mi.wiktionary.org.zim
    w3m 'http://localhost:8080/mi.wiktionary.org/A/whiri'

    -> Not Found
    The requested URL "/mi.wiktionary.org/A/whiri" was not found on this server.

**Comment by kelson42** [comment]
@archenemies Please open a new ticket if you have a new problem

**Comment by archenemies** [comment]
@kelson42 I tried to build ZIM tools so I could look inside the archive and see what URLs it contained, but wasn't able to do so. I opened a ticket <https://github.com/openzim/zim-tools/issues/223> for that. If you just tell me one of the URLs in the archive then I could look at the format of the page and see if Zimmer might work for me.

**Comment by archenemies** [comment]
I got it:

    kiwix-serve -p 8080 mi.wiktionary.org.zim
    w3m http://localhost:8080/mi.wiktionary.org/A/birdo.html

Unfortunately it looks like all the articles here are too small to have a TOC so it doesn't answer my question, I'll try asking at <https://github.com/vss-devel/zimmer>.
