### ISSUE TITLE
Are ZIM format integer signed or unsigned?

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#197]
Following this comment: https://github.com/openzim/libzim/issues/189#issuecomment-443540604

It seems unclear in http://www.openzim.org/wiki/ZIM_file_format if `integer` means `unsigned integer` or signed integer`.

It seems that whatever the answer, we should update the specifications.

**Comment by tim-st** [comment]
Thanks, yes that was my question. But now I think because of little endian assumption unsigned int will always work. I used (signed) int because I saw in an older version of zim that was used too in a pascal code, and I had no issues.

**Comment by kelson42** [comment]
@tim-st ok, please update the new ticket, we will sort out all of this.

**Comment by tim-st** [comment]
@kelson42 sorry, I dont understand what you mean by "update the new ticket".
Btw. Another thing in the docs is a value `0xffffffffff` for an size 32 int.

**Comment by kelson42** [comment]
@tim-st New ticket is  #189

**Comment by mgautierfr** [comment]
Yes I confirm it is always unsigned integer.
I have modified the spec accordingly.

**Comment by kelson42** [comment]
@mgautierfr thx http://www.openzim.org/w/index.php?title=ZIM_file_format&type=revision&diff=2909&oldid=2897
