### ISSUE TITLE
Distribute binaries for libzim

### ISSUE THREAD

**Issue by ISNIT0** [openzim/libzim#199]
Seeing as we already build `libzim` for various platforms on Travis, it might be worth distributing the binaries.

This would be very helpful for node bindings to `libzim`, where most users won't know what Ninja/Meson are etc.

Some examples of this being done already:
- https://github.com/electron/electron/releases
- https://github.com/andlabs/libui/releases

**Comment by ISNIT0** [comment]
@kelson42 @mgautierfr Would be great to get this done soon if possible 👍

**Comment by mgautierfr** [comment]
I suppose that you want all other dependencies (liblzma, libz, libxapian, libicui18n, libicuuc, libuuid, libm, libicudata, ... ) embedded in the final libzim.so ?

If so I have to modify the build system to build all dependencies statically while building libzim shared.

**Comment by kelson42** [comment]
@mgautierfr yes

**Comment by mgautierfr** [comment]
This is done with kiwix/kiwix-build#289 and openzim/libzim#200 for linux x86_64.

Today's build is available here : http://download.openzim.org/nightly/2019-02-07/libzim_linux-x86_64-2019-02-07.tar.gz

@ISNIT0 Please test the binary and if it is ok, feel free to close this issue.

**Comment by ISNIT0** [comment]
@mgautierfr Is there a MacOS build?

**Comment by mgautierfr** [comment]
No

**Comment by ISNIT0** [comment]
Will there be? 😄

**Comment by mgautierfr** [comment]
Not planned for now :)

**Comment by ISNIT0** [comment]
A MacOS build is kind of important because a lot of the development and use of MWOffliner is on MacOS

**Comment by ISNIT0** [comment]
@mgautierfr also, the `libzim.so` file is 11 bytes

**Comment by mgautierfr** [comment]
`libzim.so.4.0.4` is 23Mo here.

**Comment by ISNIT0** [comment]
Do I need to use a special flag when I extract the file? I only have `libzim.so`

**Comment by mgautierfr** [comment]
What is your archive ? (discuss this on IRC ?)

**Comment by ISNIT0** [comment]
The one you linked above. Are you on Slack?

**Comment by mgautierfr** [comment]
```
$ wget http://download.openzim.org/nightly/2019-02-07/libzim_linux-x86_64-2019-02-07.tar.gz
$ tar xf libzim_linux-x86_64-2019-02-07.tar.gz
$ ls -lh libzim_linux-x86_64-2019-02-07/libzim.so.4.0.4
-rwxr-xr-x. 1 mgautier mgautier 23033797  7 févr. 10:14 libzim_linux-x86_64-2019-02-07/libzim.so.4.0.4
```
`libzim.so.4.0.4` is 23033797 bytes (22Mb)

**Comment by ISNIT0** [comment]
@mgautierfr Ahh, sorry, I was using `2019-02-06`

**Comment by ISNIT0** [comment]
Emmanuel sent me that link yesterday :)

**Comment by ISNIT0** [comment]
@mgautierfr It now looks like the soft links are incorrect, I think `libzim.so` -> `libzim.so.4` instead of `libim.so.4.0.4`

**Comment by mgautierfr** [comment]
This is `libzim.so` -> `libzim.so.4` -> `libzim.so.4.0.4`

**Comment by ISNIT0** [comment]
I just re-downloaded the latest and I now don't see `libzim.so` at all:
```
➜  Downloads wget http://download.openzim.org/nightly/2019-02-07/libzim_linux-x86_64-2019-02-07.tar.gz
--2019-02-07 11:10:57--  http://download.openzim.org/nightly/2019-02-07/libzim_linux-x86_64-2019-02-07.tar.gz
Resolving download.openzim.org (download.openzim.org)... 195.154.156.115
Connecting to download.openzim.org (download.openzim.org)|195.154.156.115|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8047508 (7.7M) [application/octet-stream]
Saving to: ‘libzim_linux-x86_64-2019-02-07.tar.gz’

libzim_linux-x86_64-2019-02-07.ta 100%[=============================================================>]   7.67M  3.37MB/s    in 2.3s    

2019-02-07 11:10:59 (3.37 MB/s) - ‘libzim_linux-x86_64-2019-02-07.tar.gz’ saved [8047508/8047508]

➜  Downloads tar xf libzim_linux-x86_64-2019-02-07.tar.gz 
➜  Downloads ls -lart libzim_linux-x86_64-2019-02-07
total 44992
-rwxr-xr-x    1 user  staff  23033797  7 Feb 09:14 libzim.so.4.0.4
drwx------+ 502 user  staff     16064  7 Feb 11:11 ..
drwxr-xr-x    3 user  staff        96  7 Feb 11:11 .
➜  Downloads 

```
![image](https://user-images.githubusercontent.com/5173131/52407807-28a1db80-2ac9-11e9-805b-508a76bc357c.png)

**Comment by mgautierfr** [comment]
You should use directly `libzim.so.4.0.4` or make a symlink `libzim.so.4` to `libzim.so.4.0.4`.
You should not use `libzim.so`, else you will lost ABI versioning.

I don't know how you (want to) use it.

**Comment by ISNIT0** [comment]
Okay, I now have this working full on my end, thanks @mgautierfr

**Comment by kelson42** [comment]
@mgautierfr We need a proper release of the libzim of course to complete mwoffliner 1.8.

**Comment by mgautierfr** [comment]
I've updated how the archive is made. There will be :
- `libzim.so.4.0.4` (or any new version)
- a symlink `libzim.so.4` pointing to `libzim.so.4.0.4`
- The include files. Doing the review of `node-libzim` it appears that you need the include files. Do not use the old version of the include else you may have incompatible headers if the API change (and in this case, I will change the major version (4))

**Comment by ISNIT0** [comment]
Is there a url for the new files? I don't see `libzim.so.4.0.4` in http://download.openzim.org/release/libzim/libzim-4.0.4.tar.xz

**Comment by ISNIT0** [comment]
Missing ZimCreator header files 😢

**Comment by kelson42** [comment]
Done
