### ISSUE TITLE
Remove zlib dependency

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#20]
I do not see any reason why we should keep it (like for bz2).

**Comment by kelson42** [comment]
@mgautierfr Might also be good to do that just before release

**Comment by kelson42** [comment]
@mgautierfr It seems quite complicated to remove the libz dependence. As this dependence is anyway installed everwhere, I consider that this is not a big problem. What do you think. Should we close this ticket and leave it like it is?

**Comment by mgautierfr** [comment]
Yes we should close the ticke.
zlib is also used by aria2, xapian, qt and licurl, kiwix-tools
Removing it from libzim will not help.

**Comment by kelson42** [comment]
We finally decided to make it.
