### ISSUE TITLE
Confusion between github & wikimedia git repositories

### ISSUE THREAD

**Issue by soloturn** [openzim/libzim#202]
what is the strategy with the two repositories:
* https://github.com/openzim/libzim/
* https://gerrit.wikimedia.org/g/openzim

**Comment by kelson42** [comment]
@soloturn Indeed, Wikimedia stuff was the old repository. Everything (ticket/code) has been migrated to github. It is outdated. Would you be able to request its deletiong/archiving?

**Comment by kelson42** [comment]
I have open a ticket at WMF level to tag the Wikimedia Gerrit repo as `[archived]`, see:
https://phabricator.wikimedia.org/T219060

**Comment by kelson42** [comment]
@soloturn This has been done upstream. Thx for the bug report.
