### ISSUE TITLE
compile / pytest failure libzim 4.06

### ISSUE THREAD

**Issue by nobicycle** [openzim/libzim#214]
Hello,

Prior versions compiled OK on Manjaro Linux but 4.06 produces this:

==> Starting check()...
[0/1] Running all tests.
1/6 cluster                                 OK       6.58 s 
2/6 dirent                                  OK       0.02 s 
3/6 header                                  OK       0.01 s 
4/6 uuid                                    OK       1.03 s 
5/6 template                                OK       0.01 s 
6/6 pytest                                  FAIL     0.67 s (exit status 1)

Ok:                    5
Expected Fail:         0
Fail:                  1
Unexpected Pass:       0
Skipped:               0
Timeout:               0

The output from the failed tests:

```
6/6 pytest                                  FAIL     0.67 s (exit status 1)

--- command ---
PYTHONPATH='/mnt/HD02-1T/backup/Packages/Manjaro/yay/libzim/src/libzim-4.0.6/build/test/pytest/wrapper' /usr/bin/python -m pytest
--- stdout ---
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
rootdir: /mnt/HD02-1T/backup/Packages/Manjaro/yay/libzim/src/libzim-4.0.6/test/pytest, inifile:
collected 158 items

basic_open_test.py ..................................................
-------

Full log written to /mnt/HD02-1T/backup/Packages/Manjaro/yay/libzim/src/libzim-4.0.6/build/meson-logs/testlog.txt
FAILED: meson-test 
/usr/bin/meson test --no-rebuild --print-errorlogs
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in check().
    Aborting...
Error making: libzim

```

Log attached
[testlog.txt](https://github.com/openzim/libzim/files/3041580/testlog.txt)

**Comment by kelson42** [comment]
@nobicycle Thank you for the bug report. Do you still have problem to compile the libzim with latest versions?

**Comment by nobicycle** [comment]
Hello kelson42
Version 5.0.0 compiles without error.

Thank you

**Comment by kelson42** [comment]
@nobicycle Wonderful :) Thx for the quick feedback.
