### ISSUE TITLE
cython is not detected during package building for Alpine Linux

### ISSUE THREAD

**Issue by OTLabs** [openzim/libzim#216]
Hi!

I would like to add support for `cython` in `libzim` package for Alpine Linux. Cython3 is provided in `cython3` package as `/usr/bin/cython` and during configuration stage it is not detected.

Is it possible to force or trick configuration script to detect or to use `/usr/bin/cython`?

Thank you in advance for your kind attention to my comment!

**Comment by kelson42** [comment]
@OTLabs maybe a stupid question, but what is the problem you want to fix? Is this ticket about providing a python binding of the libzim?

**Comment by OTLabs** [comment]
@kelson42 During libzim compilation I see a message from meson that `Program cython3 found: NO`. I have cython installed as /usr/bin/cython. I would like to see that cython is detected in meson and see the effect of availability of cython on build process.

**Comment by kelson42** [comment]
@mgautierfr @OTLabs For what is needed Cython? Why we do test it in the Meson?

**Comment by kelson42** [comment]
@OTLabs It seems to be used for testing the libzim and we need cython3. I'm not sure why this is not detected on alpine, but it works fine on Trusty Ubuntu container. So I guess this is a problem that Cython is not the right version of badly installed in your Docker. Do you have any proof that something is wrong with our code?

**Comment by OTLabs** [comment]
@kelson42 `meson` is unable to detect presence of `cython3` if it was installed as `/usr/bin/cython`, not `/usr/bin/cython3`.

Now the package `cython3` on Alpine Linux provides a link from `/usr/bin/cython3` to `/usr/bin/cython` so meson detects its presence correctly.

**Comment by kelson42** [comment]
great!
