### ISSUE TITLE
libicu 62 no longer available on Mac

### ISSUE THREAD

**Issue by ISNIT0** [openzim/libzim#219]
Similar issue: https://github.com/SublimeLinter/SublimeLinter/issues/1555

This makes it difficult to develop and build libzim on a Mac. Could we update to `64`?

**Comment by kelson42** [comment]
@ISNIT0 I don't understand, we force a specific version of libicu somewhere?

**Comment by ISNIT0** [comment]
Actually, I've thought on it more and realised that we don't even use the binaries on Mac, so it must be my locally compiled version is referring to an old version. I'll try re-compiling libzim and re-open if it's still an issue.
