### ISSUE TITLE
Better dirent structure in the writer.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#221]
As explain in openzim/node-libzim#10, the writer has to keep the dirent in memory to do all the
postprocessing.

With a lot of articles we will end with a lot of memory used. There are several thing we can do :
- Dirent can be "simple" dirent or "redirect" dirent. Depending of the kind, only some field are used. But the dirent structure store all field and so, is bigger than needed. By using `union` and changing the order of the field to avoid padding, we can reduce the size of the dirent from 200 bytes to 192.
- version field is not used at all at writing. It is always 0. We could store it elsewhere than in the dirent structure, it would remove the 
- We use 3 string to store the url, tittle and parameter. This is a niftly hack but we could instead use only one string and concat all url/title/paramater in only one string.
- The aid is stored in a separated string. We could force the fact that aid is always `ns + "/" + url` and avoid to cost of storing it.
- The redirectAid string is only used to resolve redirection at end of the process and set the redirectIndex. So we could use a union to store the redirecAid and redirectIndex to use the same space for both.

We could end with a size of 96 bytes instead of 200.
String data (url, title, redirectAid) would be still stored, so we cloud expect only 100bytes*nbArticle, so around 1Go for 10 million articles.

**Comment by kelson42** [comment]
@mgautierfr What is the status here? What is the relation to #222 (seems pretty much to be a duplicate to me).

**Comment by mgautierfr** [comment]
We have done most of the ideas here.
I'm closing the issue.
