### ISSUE TITLE
Specialized dirent structure in the writer.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#222]
We use the same `Dirent` structure for "classic" article and "redirect" article.
However, redirect article need to more information (the target article) than "classic" article.

If we use polymorphism and create a specific dirent for each article, we avoid to store a `redirectAid` and `redirectIndex` for classical dirent.

**Comment by kelson42** [comment]
@mgautierfr Sounds a good idea.

**Comment by kelson42** [comment]
@mgautierfr Looks like this hasn't be done during our last optimisation effort. Is that still actual?

**Comment by mgautierfr** [comment]
For the record, we don't use a specialized dirent but an internal union to avoid wasted memory usage. (https://github.com/openzim/libzim/blob/master/src/writer/_dirent.h#L44-L47)

I'm closing the issue. This is not relevant anymore.
