### ISSUE TITLE
Do not write tempory file for uncompressed article in memory.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#224]
For now, when we have a full uncompressed cluster, we do not write it in the fs. We instead keep it in memory and keep a path to files containing the actual data.

That way, when the articles are already on the filesystem (`zimwriterfs` case), we avoid a lot a memory copy from one file to another. However, when the data is in memory and not in the fs (`node-libzim` case), we write the data in a temporary file (one per article) to not keep all the data in memory. We only store the path of the temporary file in memory.

However, when all the data are in memory, this is pretty inefficient, it is even worse :
* We write a lot of temporary files (can be millions)
* We keep a lot of path (to the temporary files) in memory.

It would be better to directly write a temporary file per cluster and keep only one path to the temporary cluster... and relieve the fs and the memory.

**Comment by kelson42** [comment]
@mgautierfr Why we do have to write the clusters in distinct files before "concatenating" them at the end? Why we can not start to concatenate them from the beginning?

**Comment by mgautierfr** [comment]
There is a header at beginning of the cluster with all the offsets of the blob. So we can write the cluster only when we know what is in the cluster.

**Comment by kelson42** [comment]
@mgautierfr OK. but the offset are relative to the whole ZIM file? We anyway write a cluster to the fs at the time the cluster is completed!?

**Comment by mgautierfr** [comment]
> OK. but the offsets are relative to the whole ZIM file?

No, there are relative to the cluster.

> We anyway write a cluster to the fs at the time the cluster is completed!?

If we write the (uncompressed) cluster in a temporary file when the cluster is full. We globally copy the content of article (in zimwriterfs, it is a file) into a temporary file (the cluster file) and then, copy this temporary file into the zimfile at the end of the process.

So, it ends with a unnecessary copy of files into temporary files.

For compressed cluster, we write the cluster temporary file directly. This way we can do the compression in parallel of other tasks and at the end of the process we simply do a plain copy without compression.
