### ISSUE TITLE
Resolve redirect when we add it, not at the end of the process.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#226]
For now, when we add a redirect article, we keep the targetaid (target article id) in memory.
At the end of the process, we loop on all article and resolve redirects.

If we enforce (on zimwriterfs or mwoffliner or ...) that the target article is already added when we add the redirect article, we can resolve the redirect directly and avoid use to store the targetid.

We would need to pointer to the targeted dirent, so we need to implement #223 first.

**Comment by kelson42** [comment]
@mgautierfr Considering that we know which articles have already been added to the ZIM file, would that be possible to resolve and keep it only if not resolved (and keep cleaning at the end)? That way is the writing software is smart (write the redirects at the end) then this is efficient... but still works otherwise.

**Comment by mgautierfr** [comment]
Not for now. A redirect article stores the `id` (a number) of the targeted article. But this id is only known at the end because the id is the index of the article in the urlPtr array (and so, we need to know all articles to sort them by url).
So, we store in the dirent the url of the targeted article. End then, at the end, we resolve the redirect :
- We sort all articles by url,
- We loop over articles and, when redirect, correctly set the id.

But yes, with this change, we could keep unresolved articles in the list and resolve them at the end.

**Comment by mgautierfr** [comment]
I don't think it is a good idea after all.
The new implementation skip the redirectArticle in a different set than the article. So the end loop to resolve article more efficient.
Resolving the redirect article when we add it doesn't change a lot of things on the side of perf/memory and complicate somehow the code (two place where redirection is resolved).
