### ISSUE TITLE
Memory leaks when search on iOS

### ISSUE THREAD

**Issue by automactic** [openzim/libzim#231]
![5aananum1ddx](https://user-images.githubusercontent.com/8294252/57702797-cf4bca00-762c-11e9-9165-ee6a0f11c0b7.jpg)
*There is a leek in the engine room!*

---

I think there might some memory issue in libzim / libkiwix or xapian. (Or it could also be my fault...)

Here are some call trees: 
<img width="1680" alt="Screen Shot 2019-05-13 at 10 59 52 PM" src="https://user-images.githubusercontent.com/8294252/57703412-05d61480-762e-11e9-8866-613e03010c95.png">
<img width="1680" alt="Screen Shot 2019-05-13 at 11 00 44 PM" src="https://user-images.githubusercontent.com/8294252/57703414-05d61480-762e-11e9-8788-6f7df787d5a0.png">

**Comment by automactic** [comment]
This happens during search, not during reading articles

**Comment by mgautierfr** [comment]
Shoud be fixed by https://github.com/openzim/libzim/pull/236 and https://github.com/kiwix/kiwix-lib/pull/226
