### ISSUE TITLE
Missing slash between namespace and URL in error message

### ISSUE THREAD

**Issue by ISNIT0** [openzim/libzim#242]
When using MWOffliner, we're seeing this log: `Impossible to add AAndagaadu` (https://github.com/openzim/mwoffliner/issues/828)

Aside from the missing `/` between the namespace, there is no context showing why this has failed, making it difficult to debug.

Would be great to get more information from this log message :)

**Comment by mgautierfr** [comment]
The text (copied from openzim/mwoffliner#828)
```
Impossible to add ABhansali_Productions
  dirent's title to add is : Bhansali Productions
  existing dirent's title is : Sanjay Leela Bhansali
```
Means that you try to add two "articles" (real article or redirect) with the same url (`ABhansali_Productions` for this case, and it probably should be printed `A/Bhansali_Productions`). The article already added has for title "Sanjay Leela Bhansali" and the one you want to add has "Bhansali Productions".

There is not a lot of more information to give (maybe if this is a redirect or not).

I don't know what the single line ` Impossible to add AAndagaadu` means. The sentence is only present in libzim in the context described and it always comes with the information about the title. I didn't find any reference to the sentence elsewhere (even in mwoffliner or node-libzim)

**Comment by kelson42** [comment]
@mgautierfr Thank you. To me, everything works fine, except the lack of slash between the namespace and the URL. I will rename the ticket.
