### ISSUE TITLE
"write zimfile" is too long without printing anything to the output

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#243]
As a consequence, the process is believed to be stallen by zimfarm and then the worker is killed before the end. Logs about the progression would be welcome.

**Comment by kelson42** [comment]
@mgautierfr Are we sure that none of the things happening beetween the new log entries is going to take more than a few minutes?

**Comment by mgautierfr** [comment]
No, but then we will know what takes time and where to add more debug information :)

**Comment by kelson42** [comment]
@mgautierfr Sure we need to go through 2 libzim+node-libzim+mwoffliner releases to come to that point? I'm convinced you could probably already answer this question with an educated guess and do the necessary to print things within the few `for` loops happening around that code.

**Comment by mgautierfr** [comment]
Well, at this time, all the complex work has already been done. There is nothing but writing things without calculation. This is why there was no output at the first time.

I've just added more output to print the advancement of the clusters written. This is what takes most of the place, so probably the most of the time. I print a line every 1000 clusters, but I don't know if it is enough.

**Comment by kelson42** [comment]
@mgautierfr Thx, this is the kind of thing I had in minde. Lets hope this will be enough.
