### ISSUE TITLE
On Ubuntu Xenial libzim.so is install in an "unsupported" directory

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#26]
```
$ sudo ninja install | grep "\.so*"
Installing src/libzim.so to /usr/local/lib/x86_64-linux-gnu/libzim.so

```

The problem is the location where the libzim is installed
```
$ find /usr -name "libzim.so*"
/usr/local/lib/x86_64-linux-gnu/libzim.so.0
/usr/local/lib/x86_64-linux-gnu/libzim.so
```

This is not parsed per default by ld
```
$ more /etc/ld.so.conf.d/*conf
::::::::::::::
/etc/ld.so.conf.d/fakeroot-x86_64-linux-gnu.conf
::::::::::::::
/usr/lib/x86_64-linux-gnu/libfakeroot
::::::::::::::
/etc/ld.so.conf.d/i386-linux-gnu.conf
::::::::::::::
# Multiarch support
/lib/i386-linux-gnu
/usr/lib/i386-linux-gnu
/lib/i686-linux-gnu
/usr/lib/i686-linux-gnu
::::::::::::::
/etc/ld.so.conf.d/i386-linux-gnu_GL.conf
::::::::::::::
/usr/lib/i386-linux-gnu/mesa
::::::::::::::
/etc/ld.so.conf.d/libc.conf
::::::::::::::
# libc default configuration
/usr/local/lib
::::::::::::::
/etc/ld.so.conf.d/x86_64-linux-gnu.conf
::::::::::::::
# Multiarch support
/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu
::::::::::::::
/etc/ld.so.conf.d/x86_64-linux-gnu_EGL.conf
::::::::::::::
/usr/lib/x86_64-linux-gnu/mesa-egl
::::::::::::::
/etc/ld.so.conf.d/x86_64-linux-gnu_GL.conf
::::::::::::::
/usr/lib/x86_64-linux-gnu/mesa

```

As a consequence zimwriterfs does not find it
```
$ sudo ldconfig
kelson@kelson-VirtualBox:~/libzim/build$ zimwriterfs 
zimwriterfs: error while loading shared libraries: libzim.so.0: cannot open shared object file: No such file or directory
```

We need a solution where this works out-of-the-box, without tweaking LD_LIBRARY_PATH and LD_PATH env variables.

**Comment by mgautierfr** [comment]
I'm not sure here. On ubuntu the default prefix for x86_64 libs is `lib/x86_64-linux-gnu`.
Hence, meson detect we are running on ubuntu and use the "right" prefix.

It seems that either the "libc default configuration" or the "Multarch support" is wrong in the default ubuntu configuration.

However, you can force the libprefix with the `--libdir` option.

**Comment by kelson42** [comment]
If /usr/local/lib/x86_64-linux-gnu/ is the right prefix then it should work out of the box. It does not. I strongly doubt there is a bug on Ubuntu about that. The mutliarch hierarchy seems mostly reserved for compilation stuff, all the rest is installed in /usr/lib (like usual). I think things should land in /usr/local/lib as this is what Ubuntu understands per defaults... and what users/developers are used too.

**Comment by mgautierfr** [comment]
It's either a bug in meson or in Ubuntu, `kiwix-build` do not force a special `libprefix`[*] to `meson`.
`meson` detects automatically it is running on `debian` like distribution and use the `lib/x86_64-linux-gnu` prefix on 64 bits platform. (On other platform, like `Fedora`, it will use `lib64`)
Either this prefix is not the good one or `Ubuntu` (and `Debian`) should look into it.

Looking into this, it is more complex that it seems, on `Fedora`, `/usr/local/lib` is even not in the default search paths.
Maybe it is not a bug at all and you should add yourself the path to the search paths.

I've open a issue on `meson` side (https://github.com/mesonbuild/meson/issues/1972), we'll see what they say about this.

[*] Actually, `kiwix-build` is forcing the `libprefix` to build systems (`make`, `cmake`, `meson`). But the `libprefix` is either the one specified with `--libdir` option or it is automatically detected using the exact same code than `meson`

**Comment by kelson42** [comment]
@mgautierfr It seems the ticket has been fixed upstream by Debian, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=685519. I would recommend to also close the ticket on Meson side.
