### ISSUE TITLE
word/title index for zim files

### ISSUE THREAD

**Issue by I338** [openzim/libzim#262]
I don't know if there is already some implementation of this, but it seems like it would be much faster to search an index of article titles instead of a fulltext search of the entire multi-gigabyte file. 

For instance, it takes several seconds to find a word in the Wiktionary ZIM, while grepping from a wordlist of the entire English language takes 6 milliseconds on my computer.

Also, if this is not the right place for ZIM file related issues, please tell me

**Comment by kelson42** [comment]
@I338 Thank you for your report.

The libzim provides both already:
* A search in the titiles
* A fulltext search

Both should be fast, but we have a speed problem on the title search which should be fixed soon (a few bugs have been reported on Kiwix-Android and Kiwix-Desktop).

**Comment by I338** [comment]
thanks for the quick response! so, if I understand correctly, the search speed problem is a bug in kiwix, not a missing feature?

**Comment by kelson42** [comment]
@I338 Definitly
