### ISSUE TITLE
Avoid duplicate cluster writing

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#264]
Currently clusters, which represent 99% of the whole size of a ZIM files, are written two times to the file system:
* Each cluster is written to a file first
* Then all the clusters are concatenate to a ZIM file.

If we could do everything in one pass, this would:
* Save disk usage
* Save time because fs access are slow

We might be able to do so by just writing ZIM files on the fly. That would imply to keep the header at the beginning on the file, but to write dirents + indexes at the end. Would should be able to do so without modifying the ZIM spec (probably by pre-allocating enough fs space for the variable part of the header: mimetypes, etc...)

**Comment by kelson42** [comment]
Reopen, I guess this was the wrong ticket written in the PR

**Comment by mgautierfr** [comment]
Yes, this PR is still open, I wrongly closed it.

https://manpages.ubuntu.com/manpages/disco/en/man2/fallocate.2.html could help here.
