### ISSUE TITLE
Would it be possible to remove Python dependence

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#265]
We currently use Python to partly automated test the libzim. This is not optimal IMO because we create here a dependence to one additional tech, which is at the end not really necessary as we can run all our tests in C++ anyway.

This is not a major problem, but we have already seen many time in the past that users had difficulties with that point and have open tickets. The dependence is optional, but that also mean that not all users automated test the code in the same manner, depending of their Python setup.

I would prefer to reduce the test dependence to only gtest. Hope this could be done without a high price to pay?

**Comment by veloman-yunkan** [comment]
meson build system depends on python, thus python is a natural dependence. pytest is a minor additional dependence on top of python. I think that reimplementing `pytest/basic_open_test.py` in C++ is possible, but not worth the effort. If done, it will most probably simply replace one type of issues with another type of issues.

**Comment by kelson42** [comment]
@veloman-yunkan The problem is not really Python, this is Cython and users (most of the time first users) get confused about that. There is really no reason to have this here. Googletest to the contrary is a natural dependency.

**Comment by veloman-yunkan** [comment]
@kelson42 Indeed, cython is an unjustified dependency.

**Comment by veloman-yunkan** [comment]
@kelson42 On a different note, I think that this issue was added to the [Speed-up](https://github.com/openzim/libzim/projects/2) project by mistake.

**Comment by kelson42** [comment]
@veloman-yunkan I agree, this is a bit exotic here. But I had difficulties to bring it to any of the projects we had so far (this is on the meta level). Now, I would like to just get rid of it. I'm not sure exactly of the nature of the automated tests done in Python. I don't know if a lot of work is necessary to rewrite them in C++ (maybe we can just get rid of the Python automated test?), do you have a clue about it? Do you feel unconfortable with this ticket?

**Comment by veloman-yunkan** [comment]
Another problem with these tests is that they are NOT executed when libzim is built as a static library.

**Comment by kelson42** [comment]
@veloman-yunkan OK, strange, anyway I would like to build systematically both dyn+static https://download.kiwix.org/zim/wikipedia/wikipedia_ar_all_maxi_2020-07.zim. This the simpliest solution and this is BTW how Debians needs it I believe @legoktm .

**Comment by veloman-yunkan** [comment]
@kelson42 Your response is a little confusing, and I guess I better clarify my previous comment. Currently, the unit-tests of libzim found under `test/pytest` are run only if libzim is built as a shared library. Converting them to gtest will make them run for a static build too, which is another reason for getting rid of the Python dependency.

**Comment by kelson42** [comment]
@veloman-yunkan Sorry, got your first comment properly, my comment is out-of-topic.
