### ISSUE TITLE
Extend stopwords list

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#281]
In other languages.

They could be done from example with the help of https://github.com/stopwords-iso

**Comment by imrahul361** [comment]
I am new to open source projects.can i try working on it

**Comment by imrahul361** [comment]
can anyone help me and tell how to setup the environment for codebase?

**Comment by kelson42** [comment]
@imrahul361 Everything should be explained in the `README.md`

**Comment by Souravs437** [comment]
@kelson42 , I want to try this one , is this issue still open.

**Comment by kelson42** [comment]
@Souravs437 There is already a PR running for this ticket. Please don't take it.
