### ISSUE TITLE
Missing CMake build.

### ISSUE THREAD

**Issue by qis** [openzim/libzim#285]
Please add CMakeLists.txt to the project. It's the de-facto standard for open-source libraries.

**Comment by kelson42** [comment]
@qis What is the problem here? We don't use `cmake`, so why have this `CMakeLists.txt`?

**Comment by qis** [comment]
Easier integration in vcpkg is my main concern.

**Comment by kelson42** [comment]
@qis I don't know `vcpkg` and I don't understand the full use case and why we should support it. Please give more details about what is the problem you try to fix.

**Comment by qis** [comment]
As many others, I use vcpkg to build libraries and their dependencies with a single CMake toolchain file that defines non-standard compiler and options.

It would be nice to be able to build libzim on windows with clang and libc++ and use it to crawl gutenberg language archives that are available in zim format.

**Comment by kelson42** [comment]
@qis Our build system is `meson` and `ninja`. AFAIK it works on Windows. This is what we (want to) support. We can not support many build system for the same operating system. That would be too much of work.

**Comment by qis** [comment]
Understood. I'll try to get archives in another format then.
