### ISSUE TITLE
Consider using Xapian "honey" backend

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#286]
It produces a lot smaller indexes, see https://trac.xapian.org/wiki/FAQ/DatabaseSize

**Comment by kelson42** [comment]
Closing for the moment, this is still no ready and there is no release date. We will have a look to the new backend when Xapian 1.5 will be released.

**Comment by data-man** [comment]
> We will have a look to the new backend

What about [LucenePlusPlus](https://github.com/luceneplusplus/LucenePlusPlus)?

**Comment by kelson42** [comment]
@data-man We tried this 10 years ago without much success.
