### ISSUE TITLE
Should redirectUrl on Article have a namespace?

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#298]
First of all, what we're trying to fix is `libzim` complaining about incorrect redirect via `zimwriterfs` on `sotoki`. See openzim/sotoki/issues/95.

https://github.com/openzim/libzim/blob/0860914299fff7697c97072c75587f768002c803/src/writer/creator.cpp#L604

The problem reveals itself in `dirent->getRedirectUrl().getLongUrl()`.

https://github.com/openzim/libzim/blob/0860914299fff7697c97072c75587f768002c803/include/zim/writer/url.h#L45

`libzim` builds a long URL (ie. including the namespace) from a redirect that was instantiated (by `zimwriterfs`) without a namespace (the _redirect to_ url).

My understanding of [the spec](https://wiki.openzim.org/wiki/ZIM_file_format#Redirect_Entry) leads to redirects being possible only inside the same namespace. I get that from the fact that we're specifying the namespace and the mime type for the Entry but that shouldn't prevent cross-namespace redirect I guess.

Based on this, `zimwriterfs` is able to ingest a TSV file of `namespace url title target_url` format to create the redirect entries.

What `zimwriterfs` does is creating a `RedirectArticle` that's a subclass of `Article` for which `isRedirect()` always returns `true` and… **the redirectUrl is set directly from that TSV value**.

[zimcreatorfs.cpp#L55](https://github.com/openzim/zimwriterfs/blob/bfccf4b07aea35d1f2c670f45d075414826b0f06/src/zimcreatorfs.cpp#L55)
``` cpp
    auto redirectArticle = std::make_shared<RedirectArticle>(
      matches[1].str()[0],
      matches[2].str(),
      matches[3].str(),
      matches[4].str());
    addArticle(redirectArticle);
```

Now, you may ask what does `mwoffliner` do? Well, it (`node-libzim` actually) builds Article entries with a namespace but whether that was taken from the spec or based on what worked is unknown.

[Article.cc#L89](https://github.com/openzim/node-libzim/blob/1dbb42c058ed93b3d135aea5e08fec851f0149c6/src/Article.cc#L89)

``` c
  zim::writer::Url getRedirectUrl() const
    {
        return zim::writer::Url(ns, redirectAid);
    }
```

So, **back to the questions**: what should be the expected/desired behavior?

* does the spec allows specifying a different namespace for redirects?
* if it does, should `zimwriterfs` allow it?
* Depending on above, should `zimwriterfs` automatically fill the namespace for the `redirectUrl`? Or should we ask `zimwriterfs` users to add namespace to redirectUrl
* should libzim expects a namespace in `redirectUrl`?
* Shouldn't we change this `Url` constructor be a little safer and check for a `/` in `[1]` at least (or a known namespace prefix)?

https://github.com/openzim/libzim/blob/0860914299fff7697c97072c75587f768002c803/include/zim/writer/url.h#L45

@mgautierfr @kelson42 @dattaz

**Comment by rgaudin** [comment]
Following discussion with @kelson42, current behavior of both `libzim` and `zimwriterfs` is correct: spec allows redirect to different namespace (although not encouraged).

`zimwriterfs` users should provide a _full URL_ on the redirect_url column of their TSV file so that `zimwriterfs` would insert it directly.

**Comment by dattaz** [comment]
I agree with the sotoki fix now that the behavior is known. 
But I draw attention to the fact that this is a regression, it worked correctly with previous versions of zimwriterfs (and thus libzim).

**Comment by rgaudin** [comment]
It's possible. It's the second time we're seeing a _broken feature_-like behavior on sotoki-zimwriterfs. That's why we changed the docker to use named version.

Do you know if other scrapers use the redirect file feature ? mwoffliner uses redirects but uses the node-libzim directly (and manually sets the target namespace).

**Comment by mgautierfr** [comment]
> does the spec allows specifying a different namespace for redirects?

Yes.

> if it does, should zimwriterfs allow it?

Probably not. We plan to remove/hide the namespace. Adding a way to specify it would be counterproductive.

> Depending on above, should zimwriterfs automatically fill the namespace for the redirectUrl? Or should we ask zimwriterfs users to add namespace to redirectUrl

It should fill the namespace

> should libzim expects a namespace in redirectUrl?

That's a open question. My point is as far as the spec allow a different namespace, the libzim should allow it. If we don't want to use it
in the kiwix project, it is to writer/reader to hide it.

> Shouldn't we change this Url constructor be a little safer and check for a / in [1] at least (or a known namespace prefix)?

Yes, we should add this test to avoid such mistake (or at least detect it quickly)
