### ISSUE TITLE
libzim should provide a simple way to got through articles quickly

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#300]
For the moment we can go trough all articles in a ZIM file via titles and URLs indexes. This is used for example in the ZIM tools:
* zimcheck
* zimdump
* zimrecreate

This works fine but is slow because articles are given in an order which is not the order in which they are physically stored in the ZIM file (clusters). Therefore a same cluster can be read many times which leads to:
* A lot of I/O
* A lot of CPU usage because of the decompression effort.

We should have a method allowing to go through all articles but in the order in which they are stored in the ZIM file cluster. Therefore:
* Each cluster should be read only one time on the fs
* Clusters are read in a row which avoid a lot of seek effort of magnetic hard drives
* Each cluster should be decompressed only one time

**Comment by mgautierfr** [comment]
Some more complementary information :

- `zim::File` provides already a API based on iterator (`File::const_iterator`, `File::begin`, `File::beginByTitle`, `File::end`, ...)
- This iterator can iterate using Url or Title order. We should add a new mode here (`ClusterIterator` ? `FastIterator` ?)
- There is no direct way to have the article ordered by cluster. We have to loop hover all article and read in which cluster they are. And then sort.
- You already did that in https://github.com/openzim/zim-tools/pull/72 (as I made it in zimrecreate tool). However it is somehow inefficient. By
using public api (article), libzim always read the full dirent (and parse all information,  as url and title). But we only need to map the index of the article to the cluster. As we do it in libzim, we can read only the information we need and it would be more efficient.
- Of course, we should generate this list only if we need it.
