### ISSUE TITLE
About clusterOrder and multithread.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#303]
This is a issue to discuss publicly (and in written format) about the "problem" I mention during our weekly meeting.

The idea behind https://github.com/openzim/libzim/pull/301 is that if we loop over the article using url order, we somehow do random access to the article and then, we have to decompress a lot of cluster to use only one article. As the cache system is not infinite, we drop cluster from cache and when we need another article in a already uncompressed cluster, we need to decompress it again.
With this change, we can loop article using cluster order, on the first access to an article in a cluster, we still need to decompress the cluster, but for the following articles, as they are in the same cluster, we don't have to decompress it again (because it is in the cache).

On the other side, the idea behind https://github.com/openzim/zim-tools/pull/72 is to use multi-thread to do all the work in parallel.

The problem is that, as we are looping in cluster order, the N threads will want to read N articles in the same cluster. So at a moment, only one of them will decompress the cluster and the N-1 other will wait the decompression ends to continue.
So, the longest operation (decompression) is mostly not parallelized.
On the other side, the thing parallelized is writing the content on the fs. And it is probably a thing than cannot parallelized efficiently.

Solutions I see (I'm open to other ideas) is :
- Do some kind of "local shuffle" of the article order ("local" need to be defined). This way, article are mostly cluster ordered (and we take advantage of cache) but not to much so each thread works on a different cluster and so decompress in parallel.
- Or instead of having tasks handling one article, we create tasks handling all the article of a cluster. This way we are sure that no thread is waiting for the decompression made in another thread. And we parallel "at maximum" decompression and writing (Assuming that not all threads decompress in the same time and then write in the same time). But we need a api to regroup the article per cluster.

In both case, we need to improve the cache system. For now, when a key is not present, the whole cache is blocked because of "There is a modification of the cache going on, please wait". We must change it to not block the whole cache while we are computing (decompressing) the value of only one key. See https://stackoverflow.com/questions/2139724/design-options-for-a-c-thread-safe-object-cache

**Comment by kelson42** [comment]
@mgautierfr @MiguelRocha 

Would a perfect multithreaded system be really faster in case of `zimdump` than one thread to read sequentially the ZIM file and put things in a queue, and another thread to write sequentially things on the fs?

**Comment by mgautierfr** [comment]
I don't know :)

If we are CPU bound (I suppose this is the case but I'm not sure), yes multi-threading the decompression will help (until we are I/O bound)
But if we are I/O bound this will not change a lot.

As all the time, we need measurements before doing anything related to performance :)

**Comment by kelson42** [comment]
@mgautierfr I don't like the idea of "local shuffle" .Therefore if I understand properly:
* We need an iterator on clusters
* We need a way to limit the cluster iterator on one cluster
* We need a cache big enough to cache N clusters (with N the number of threads getting articles) and able to be less blocking

Do I'm right?

**Comment by MiguelRocha** [comment]
If the decompression operation is the bottleneck I think we do not need caching. But it really depends on the hardware that we are running - I believe that with SSD will have no problems with I/O.

**Comment by kelson42** [comment]
@MiguelRocha We can not really make big assumption about the fs speed IMO.

**Comment by mgautierfr** [comment]
> - We need an iterator on clusters
> - We need a way to limit the cluster article iterator on one cluster

No, clusters are internal to libzim. You can't iterate over them (outside of libzim). And even if you would have it, it would be useless. Once you have a cluster, you cannot know which articles are in it.

We need to regroup article per clusters. (We know it is per cluster because we are in libzim, but from outside, it is just that articles are regrouped by whatever contains them in the same place, something that make things more performant, cache efficient, ...)

> We need a cache big enough to cache N clusters (with N the number of threads getting articles) and able to be less blocking

Yes, but that is not complicated, we can already change the cache size with the `ZIM_CLUSTERCACHE` env variable.

What we really need is to not block the cache while we are computing the value to put in. (And still ensure that if two threads want to access the same value not in the cache, they do not ends by both computing the value)

**Comment by kelson42** [comment]
@mgautierfr What would be your approach in term of API to allow a thread to deal one cluster at a time?

Regarding `ZIM_CLUSTERCACHE`, we probably need to have a solution to configure/adapt it in a better manner. I don't want to have a big cache everytime.

**Comment by mgautierfr** [comment]
> What would be your approach in term of API to allow a thread to deal one cluster at a time?

Returning a list of list of article. 

> Regarding ZIM_CLUSTERCACHE, we probably need to have a solution to configure/adapt it in a better manner. I don't want to have a big cache everytime.

Yes, it is not complicated to change.

**Comment by kelson42** [comment]
> Returning a list of list of article.

If we don't use an iterator here... Does that mean we are going to put in memory 100M "ids" if the files has 100M entries?

**Comment by mgautierfr** [comment]
This is already the case, we are internally storing all article's entries in a list.

**Comment by kelson42** [comment]
@mgautierfr We need to clarify this memory thing... Sounds not subtainable to me.

I have created a ticket for changing the cache size programmatically. We need one to retrieve the the articles list cluster by cluster. We need another one for revamping the cache. Then we could close this one IMO.

**Comment by veloman-yunkan** [comment]
What are the flows/operations where this optimization may result in noticeable speed-up? Are they fully limited to zim-tools?

**Comment by mgautierfr** [comment]
This issue was mainly a discussion at first.
However, one thing important here is the need to rewrite the cache system to not lock the whole cache while we are generating the value (to add to the cache). The last paragraph of the first comment :

> In both case, we need to improve the cache system. For now, when a key is not present, the whole cache is blocked because of "There is a modification of the cache going on, please wait". We must change it to not block the whole cache while we are computing (decompressing) the value of only one key. See stackoverflow.com/questions/2139724/design-options-for-a-c-thread-safe-object-cache

I think (but I have no performance measurement) that it will greatly improve multi-threaded access (especially random access, as we would be able to decompress two cluster in the same time). It is not limited to `zim-tools`.

**Comment by mgautierfr** [comment]
Issue about the cache optimization is #379

**Comment by kelson42** [comment]
The best ideas of this ticket have been tracked in tickets. Closing the discussion.
