### ISSUE TITLE
libzim should be able to "automatically" decide if a content should be compress or not

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#305]
For the moment all the logic is deported to a higher lever. We can see that for example here:
https://github.com/openzim/node-libzim/blob/master/src/Article.cc#L92

It is important to keep the ability for the libzim user to decide, but in 99% of the time, this new auto-mode based on mime-type should be good enough.

Doing so will make the libzim user life easier.

**Comment by mgautierfr** [comment]
New api (libzim_next) does this.
