### ISSUE TITLE
[Xapian] Exclude content fulltext and keeping title index

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#307]
In a few cases (like a web app ZIM file) we don't need the fulltext Xapian index, but we need to keep the Title index. So far, I believe the libzim does not allow that.

**Comment by mgautierfr** [comment]
Yes, this is the method `zim::Creator::setIndexing` (https://github.com/openzim/libzim/blob/master/include/zim/writer/creator.h#L41)

**Comment by kelson42** [comment]
@mgautierfr It is not clear to me. What does this method do? Fulltext index? Title indexing? Both? How do I get one without the other?

**Comment by mgautierfr** [comment]
Title xapian index is always generated (if you compile libzim with xapian).

The behavior have not changed when we start to use xapian for the title index. This was about fulltext index, it is still.

**Comment by kelson42** [comment]
OK, sounds good to me. Thx for the explanation.
