### ISSUE TITLE
Use std::map instead of std::vector in zimwriter

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#31]
This is a reminder issue for potential performance improvement of the zim writer.

While building a zim, we store all dirents in a `std::vector`. This work (very) well while we are only doing only insertion/linear reading, but we are also doing some sort,find and erase in the vector.

For the "find", we use `std::binary_search` and `std::lower_bound` using the `aid` as key. Both methods are *probably* better implemented (and more logical) in a `map` than in a `vector`.

Moreover, we also remove element from the vector. This is very time consuming (linear) as vector has to move (copy) all elements after the removed element.

It should be possible to improve this by using a `std::map<std::string, Dirent>` where the erase of a element is constant complexity.

This is also probably a specific usecase. I've interrupt a mwoffliner in the middle before launching a zimwriterfs. So I add a "full" redirect article list but not all the articles. So I had to remove all redirect article pointing to non existent article. With a full article set, this is maybe not a problem. As always, this need more investigation before starting patching.

**Comment by kelson42** [comment]
@mgautierfr Probably a good moment to tackle this.

**Comment by kelson42** [comment]
We still have a map, but things have been done in a way it is a lot faster. This should be good enough as this use case (a lot of wrong redirects) should not happen in normal case.
