### ISSUE TITLE
getRedirectUrl should return NULL if called on a non-redirect article

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#312]
For now it seems it returns a non empty URL.

**Comment by kelson42** [comment]
The problem seems to be that this method returns a `zim::Article`, so no way to return NULL or similar.

**Comment by kelson42** [comment]
@mgautierfr Have we been able to finally fox this in libzim_next?

**Comment by mgautierfr** [comment]
Yes. There is no more `getRedirectUrl`.
You will have to get the redirectEntry (`getRedirectEntry()`, which raise an exception if this is not a redirect) or the final item (`getItem(true)`) and then use `getPath()` on them.
