### ISSUE TITLE
Update dependencies list in README

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#323]
Compiling from scratch on a fresh Ubuntu focal (20.04), I realized the README is not completely up to date.

Specifically, I add to install the following packages:

```
cmake liblzma-dev cython3 uuid-dev
```

The readme mentions `lzma-dev` instead of `liblzma-dev`, I think it's a typo. For `cython3`, it seems like a recent addition and for `uuid` and `cmake`, that's lower-level but still required to compile…

I'll let you update as see fit.

**Comment by kelson42** [comment]
I would really like to get ride of Python compile dependence here, see #265

**Comment by kelson42** [comment]
I have fixed the obvious stuff https://github.com/openzim/libzim/commit/542e1e1e205ba3fca3b0145fb60a63ec0eb95dd4. Not really wanting/explaining the whole compilation stuff around Python binding honestly.

**Comment by mgautierfr** [comment]
`cython3` is indeed used for test and is optional.
`cmake` however is not use by libzim. (Or maybe to compile one of its dependences).
