### ISSUE TITLE
libzim 6.1.2 should rename the file to ".zim" only a the end

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#331]
The latest libzim writes the ZIM file straight. This is great, but as long as the last bit is not written, the file is not a proper ZIM file. Unfortunately, from the very beginning it has its final name ending with `.zim`. This is not only a semantic problem, but this fools as well the Zimfarm which - legitemely IMO - believes that there is a new ZIM file ready... and starts to upload a 0 byte ZIM file.

This ticket is to request that the ZIM file is called `.zim.tmp` (or similar) the whole process and only renamed to its final name at the very end.

**Comment by kelson42** [comment]
@rgaudin In case you wonder, this explain the really strange behaviour around upload and ZIM file size on Zimfarm task using MWoffliner `dev` version.

**Comment by rgaudin** [comment]
ah ! haven’t noticed it but yes it was agreed long ago that any .zim file should be considered valid.
