### ISSUE TITLE
Debian 10 error when installing

### ISSUE THREAD

**Issue by lonnietc** [openzim/libzim#335]
Hello,

I am trying to build and install libzim so that I can build up the Kiwix server on my Debian 10 (x86_64) system but after the building process, which seems to come out good, I get an error on install:

test-libzim/test$ ninja -C build
- - - - - - - - - - - 

[54/62] Compiling C++ object 'test/9f86d08@@find@exe/find.cpp.o'
In file included from ../test/find.cpp:25:
/usr/src/googletest/googletest/include/gtest/gtest.h: In instantiation of ‘testing::AssertionResult testing::internal::CmpHelperEQ(const char*, const char*, const T1&, const T2&) [with T1 = unsigned int; T2 = int]’:
/usr/src/googletest/googletest/include/gtest/gtest.h:1472:23:   required from ‘static testing::AssertionResult testing::internal::EqHelper<lhs_is_null_literal>::Compare(const char*, const char*, const T1&, const T2&) [with T1 = unsigned int; T2 = int; bool lhs_is_null_literal = false]’
../test/find.cpp:38:5:   required from here
/usr/src/googletest/googletest/include/gtest/gtest.h:1444:11: warning: comparison of integer expressions of different signedness: ‘const unsigned int’ and ‘const int’ [-Wsign-compare]
   if (lhs == rhs) {
       ~~~~^~~~~~
[62/62] Linking target test/find
- - - - - - - - - - - 

Then I do:

- - - - - - - - - - - 
  
test-libzim/test$ ninja -C build install

- - - - - - - - - - - -

ninja: Entering directory `build'
[0/1] Installing files.
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
Traceback (most recent call last):
  File "/home/lonnie/.local/bin/meson", line 6, in <module>
    from mesonbuild.mesonmain import main
ModuleNotFoundError: No module named 'mesonbuild'
FAILED: meson-install 
/home/lonnie/.local/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.

- - - - - - - - - - 

Any ideas what is happening here?
Thanks in advance

**Comment by kelson42** [comment]
You need to be `root` to install something on your system.
