### ISSUE TITLE
Segmentation Fault from unchecked blobNumber parameter to Cluster::getBlobSize

### ISSUE THREAD

**Issue by zandi** [openzim/libzim#336]
I don't use C++ much, so apologies if a few details are wrong. I spent some time experimenting with fuzzing libzim using afl, and found this.

Directory Entries specify the Cluster and Blob number of their data, which is used for later indexing into the cluster for data retrieval. Internally, the Cluster class stores blob offsets as a vector of `offset_t` types. This vector is indexed into by the single parameter to `getBlobSize`. But this isn't checked against the vector's size, possibly leading to bad dereferences. A malicious/malformed zim file can cause this crash, all it takes is an invalid BlobNumber in a Directory Entry.

This was found in libzim 6.0.2, but the code at issue appears unchanged in master (https://github.com/openzim/libzim/blob/master/src/cluster.h#L58). I also tested against kiwix-desktop 2.0.1 and kiwi-serve 3.1.0 on Ubuntu 18.04 LTS, and found that they are affected as well.

Here is an example backtrace of crashing the `zimdump` utility from zim-tools 1.0.5, to show the execution flow:
```
gdb --args ./bins/zimdump -F -d crash.zim
...
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7b5128b in zim::Cluster::getBlobSize (this=0x631510, n=...) at ../src/cluster.h:59
59            zsize_t getBlobSize(blob_index_t n) const  { return zsize_t(offsets[blob_index_type(n)+1].v
(gdb) bt
#0  0x00007ffff7b5128b in zim::Cluster::getBlobSize (this=0x631510, n=...) at ../src/cluster.h:59
#1  0x00007ffff7b4f19a in zim::Article::getArticleSize (this=0x7fffffffe2a0) at ../src/article.cpp:41
#2  0x00007ffff7b50145 in zim::Article::getData (this=0x7fffffffe2a0, offset=0) at ../src/article.cpp:194
#3  0x000000000040686b in ZimDumper::dumpArticle (this=<optimized out>) at ../src/zimdump.cpp:141
#4  0x0000000000412a2d in main (argc=<optimized out>, argv=0x7fffffffe3e8) at ../src/zimdump.cpp:385
(gdb) print n
$1 = {<REAL_TYPEDEF<unsigned int>> = {v = 4063232}, <No data fields>}
(gdb) print offsets
$2 = std::vector of length 1, capacity 1 = {{<REAL_TYPEDEF<unsigned long>> = {v = 0}, <No data fields>}}
(gdb) x/i $rip
=> 0x7ffff7b5128b <zim::Cluster::getBlobSize(zim::blob_index_t) const+67>:      mov    (%rax),%rbx
(gdb) i r rax
rax            0x2531568        38999400
(gdb) x/x $rax
0x2531568:      Cannot access memory at address 0x2531568
```
I think `Cluster::getBlobSize` needs checking added that index values are valid, as well as `getBlob` and other Cluster methods that index into `offsets` based on parameters, and throw an exception or otherwise handle the error without crashing. I can provide a test zim file I'm seeing this behavior with if needed.

**Comment by kelson42** [comment]
@zandi Thank you very much for this interesting bug report. Would you be able to provide a Zim file which demonstrates this bug?
@mgautierfr @MiguelRocha Would you be able to confirm the big please?

**Comment by zandi** [comment]
[zim_crash.zip](https://github.com/openzim/libzim/files/4648333/zim_crash.zip)
@kelson42 here you go, let me know if there's anything else that can help.

**Comment by mgautierfr** [comment]
I confirm we should check the index.

**Comment by kelson42** [comment]
@MiguelRocha This should be checked in the libzim but for the users via zimcheck.
