### ISSUE TITLE
Better creation of iterator by clusterOrder.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#344]
The implementation of the byClusterOrder sort the dirent by cluster order :
https://github.com/openzim/libzim/blob/master/src/fileimpl.cpp#L263

To do this, it get all the dirents to sort them.
However, the `getDirent` function is pretty complex and do stuffs we don't need in this context:
- Handle a cache of dirents (we don't need it as we loop over all dirents)
- Use mutex (to protect the cache from multi-thread access)
- Do complex(full) parsing of the dirent.

The full parsing (https://github.com/openzim/libzim/blob/master/src/dirent.cpp#L40) try to get all information but it can be pretty long (especially get title and url because they have variable lengths) and can even fail and cause a re-parsing of the dirent.

But to order the dirent we only need two informations : the mimetype (to check if it is a redirect article or not) and the cluster number (only if the article is not a redirect). Both are at known offsets and are integer, we can quickly parse them directly in `byClusterOrder` to be able to sort the article index correctly.

**Comment by kelson42** [comment]
@mgautierfr Thank you very much for creating this ticket. I have a concrete properly with for example the Stackoverflow ZIM file which is huge. For that file, getting this iterator takes edges. What kind of performance to you expect from this improvement? I really fail to understand why we have to create the full list of instead of just reading the file from the low offset up to high offset in the file (so without having this list in memory). Why stops us to do that?

**Comment by mgautierfr** [comment]
> I really fail to understand why we have to create the full list first instead of just reading the file from the low offset up to high offset in the file (so without having this list in memory). Why stops us to do that?

Well... nothing.. it depends of what we want.
It is what is done if you use url ordered iterator. But there is nothing in the zim file about the cluster order so we have to generate the cluster order list if we want to iterate this order.

**Comment by kelson42** [comment]
@mgautierfr AFAIK the url ordered iterator does not "read the file from the low offset up to high offset". It does the opposite: jumping from one side of the file to the other. We should not need a list of read blobs from the cluster 0 up to the last cluster... just because this is the order on the fs itself.

**Comment by mgautierfr** [comment]
Ho, I miss understand you question.

The problem is that the cluster contains the raw data (blob) without any metadata. We can iterate directly the cluster (and we need to iterate the list of cluster anyway), but then we cannot know what is the article pointing to the blob we have. The only way to do that would be to iterate over all dirent to find the one pointing to the current blob.

**Comment by kelson42** [comment]
@mgautierfr Thx, I think I understand now, I have a few questions: There is really now way we could store withing the Clusters or the ClusterPointerList a pointer to the corresponding Dirents? Or maybe secure that the Dirents are written in the same order than the clusters?

**Comment by mgautierfr** [comment]
Not without changing the format.

**Comment by kelson42** [comment]
@mgautierfr I have no problem with changing the format if this makes sense. I want to have here all alternatives listed/evaluated before we do anything. I don't consider that sorting and keeping things in memory to be a nice approach (at least as long as wee don't have a precise memory/time consumption estimation).

**Comment by mgautierfr** [comment]
Well...

- Store in the cluster (within the blob to exact) the dirent associated to the blob : it would introduce a break in the cluster. There is no way to add extra information without breaking the format (so, no forward compatibility). But the real "blocker" is that nothing says that a blob is associated with an article. It is totally valid that two dirents point to the same blob. And if we implement the extradata in blob as proposed in #345 we will have one dirent pointing to two different blobs.

- Ensure that dirents are writen in the same order than the cluster : First, dirents have different size, so we cannot loop directly on the dirents. This is why we have the urlprtlist, to know where the dirents are.

The best we could have (for what I see now) is to add a list in the format to list the dirent is a cluster order (as the titlePtrList lists dirents in title order).
But it would be an incompatible format change. I'm not sure we want this if just reimplementing the way we create the list is performant.

The change I propose here is pretty self contained, it is about reimplemeting the lines https://github.com/openzim/libzim/blob/master/src/fileimpl.cpp#L266-L275. No other changes for the same functionality. It should be only few hours of dev.

About the memory consumption of creating a list of index : First we already mmap the ptrlist (url and title) in memory. (We don't for android, but it is trade of with a system call for each read of the index), it would be the same for the clusterOrderPtrList. Second, if we really don't want to have a list, it is still possible to "generate" this next index at runtime (when we iterate the "list") and so, to not store any list (with the trade of to iterate over the urlptrlist several time)

**Comment by mgautierfr** [comment]
With `stackoverflow.com_eng_all_2018-08.zim` (67_818_251 articles):
- the old implementation takes 2m11s to read 5_000_000 articles (so ~30m to read all dirents)
- the new implementation takes 1m36s to read all dirents (plus 1m9s to sort them), so 2m45s total.

**Comment by MiguelRocha** [comment]
> With `stackoverflow.com_eng_all_2018-08.zim` (67_818_251 articles):
> 
>     * the old implementation takes 2m11s to read 5_000_000 articles (so ~30m to read all dirents)
> 
>     * the new implementation takes 1m36s to read all dirents (plus 1m9s to sort them), so 2m45s total.

So the sorting is faster right? What was the sort time for the old implementation?

**Comment by mgautierfr** [comment]
I haven't wait that time to measure the sorting step, but it should be the same (same input, same algo). That's the reading of the dirents who is faster (from ~30m to 1m36s).

**Comment by kelson42** [comment]
@mgautierfr Thx for this massive speed-up here.
@MiguelRocha We really need to secure that zimdump `list` does not use this clusterOrder, otherwise each time someone wants to inspect a ZIM file, he has to wait a long time before getting anything printed.
