### ISSUE TITLE
libzim is not able anymore to retrieve mime-type list properly

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#353]
Reported by @Jaifroid at https://github.com/kiwix/kiwix-js/issues/628#issuecomment-650709448

Based on my limited understanding of C++, I think the same issue is in the libZim codebase. Please take a look at:
https://github.com/openzim/libzim/blob/master/src/fileimpl.cpp#L130, and in particular these lines:
```
    // read mime types
    size = zsize_t(header.getUrlPtrPos() - header.getMimeListPos());
    // No need to check access, getUrlPtrPos is in the zim file, and we are
    // sure that getMimeListPos is 80.
    auto buffer = zimReader->get_buffer(offset_t(header.getMimeListPos()), size);
    offset_t current = offset_t(0);
```
It looks very much to me like the size of the MIME type list is being calculated by subtracting the `mimeListPos` from `urlPtrPos`. This works fine **only** if the URL pointer list starts one byte after the end of the MIME type list. However, if the URL pointer list is relocated elsewhere, e.g. at the end of the ZIM file, then this will become a huge size and the reader may well fail to load the MIME type list depending on size of ZIM file and on memory in the machine. Several recent ZIMs have the URL pointer list at the end of the file.

**Comment by Jaifroid** [comment]
@mgautierfr Once you have a patch for this issue, could you let me know? I've implemented a rough-and-ready version in JavaScript [here](https://github.com/kiwix/kiwix-js-windows/commit/2406b1c4f62d50ee8bc341d92126d310d4366d21#diff-007c0d1e629514c68435857c47963679R267), but it's a kludge, limiting any read for the MIME table to 1024 bytes. The largest MIME table I've seen in any ZIM file in the wild is 142 bytes.

**Comment by mgautierfr** [comment]
@Jaifroid limiting to 1024 bytes is good. It is what I've done.
Just be sure to not always read 1024 bytes as a very small zim file (test) could be smaller.

**Comment by Jaifroid** [comment]
OK thanks @mgautierfr . What I've done is accept the value given by subtracting mimeListPos from urlPtrPos if it is less than or equal to 1024. If it is greater than 1024, I use 1024, so this should be safe for small ZIMs. It looks like the same approach.
