### ISSUE TITLE
Change internal namespace handling

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#366]
Once #345 and #364 are done, it would be not more public namespace.
Then, we can start to change its handling internally.

On the writer side it would be pretty easy (put article in `C` namespace).
On the reader side, check for minor version and look for articles in `C` namespace if needed or does at
before (compatibility and default namespace would be already handled by #345)

**Comment by kelson42** [comment]
@mgautierfr what is the status on this? I’m not sure to fully understand what needs to be changed.

**Comment by mgautierfr** [comment]
This is done.
