### ISSUE TITLE
zimcheck should catch zimfiles with invalid mimetype list.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#376]
Recent zim files created by zimwriterfs are broken (https://github.com/openzim/zimwriterfs/issues/48)
zimcheck should be extended to catch them.

**Comment by kelson42** [comment]
Assigning @veloman-yunkan to help polishing the PR.

**Comment by kelson42** [comment]
@veloman-yunkan what abou this last Ticket which has been constantly postponed since last summer. One of your last ones on libzim.

**Comment by veloman-yunkan** [comment]
@kelson42 I will nail it down today
