### ISSUE TITLE
Update the cache system to not block the whole cache in case of multi-thread access.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#379]
For now the usage of the cache in libzim is somehow like this (pseudo code) :

```cpp
lock_cache();
if (cache.has_entry(key)) {
   value = cache.get_entry(key);
} else {
   value = generate_value(); //<-- will take times.
   cache[key] = value;
}
unlock_cache();
use_value(value);
```

There is one global lock for the whole cache. If the value is not in the cache, we need to generate the cache while the lock is in place (because we don't want two thread to generate the same value in the same time).
As the generation takes time (it why we have a cache), we have situation where we look the whole cache system because of only one entry generated. Even if the values for other keys are already present in the cache.

See https://github.com/openzim/libzim/blob/master/src/fileimpl.cpp#L310-L365 and https://github.com/openzim/libzim/blob/master/src/fileimpl.cpp#L393-L414 for real usage.
And there we release the lock to generate the value. This is an issue in itself as we may generate twice the value (not so important for the dirent, but we may decompress (loooong) twice the same cluster, especially with the clusterOrder iteration).

The proposed solution is inspired from https://stackoverflow.com/questions/2139724/design-options-for-a-c-thread-safe-object-cache
The idea is to have a intermediate handle, cheap to create wrapping the key/value pair. We lock the whole cache to get the handle (cheap and fast). And then we lock only the handle to generate the value.

It would lead to something:

```cpp
lock_whole_cache();
if (cache.has_entry(key)) {
    handle = cache.get_handle(key);
} else {
    handle = create_handle(key); //<-- cheap and fast
    cache[key] = handle;
}
unlock_whole_cache();
lock_handle();
if (handle.has_value()) {
    handle.get_value();
} else {
    value = generate_value(); //<-- long
    handle.set_value(value);
}
unlock_handle();
```

By moving the lock in the method we can better have :

```cpp
handle = cache.get_handle(key);  // lock the whole cache for a small time and generate the handle (fast) if necessary.
value = handle.get([]()->Value{ return generate_value(); }); // Will lock for a small time if the value is there, or a long time (but just the handle, not the cache) calling the lambda if the value is not there.
```

It would greatly simplify the usage, not lock the whole cache for long operation and avoid the user to lock itself the cache correctly (error prone).

The exact API may be adapted depending of the real use case but the main idea is there.

**Comment by veloman-yunkan** [comment]
> For now the usage of the cache in libzim is somehow like this (pseudo code) :
> 
> ```c++
> lock_cache();
> if (cache.has_entry(key)) {
>    value = cache.get_entry(key);
> } else {
>    value = generate_value(); //<-- will take times.
>    cache[key] = value;
> }
> unlock_cache();
> use_value(value);
> ```

In current code neither the cluster cache, nor the dirent cache is accessed in that pattern. Rather it looks like below:
```c++
getValue(key) {
  lock_cache();
  if (cache.has_entry(key)) {
     value = cache.get_entry(key);
     unlock_cache();
     return value;
  }
  unlock_cache();
  value = generate_value(key); 
  lock_cache();
  cache[key] = value;
  unlock_cache();
  return value;
}
```
Therefore the cache is not locked for the duration of the slow value generation operation. But the problem with that solution is that the `generate_value(key)` for the same value of key may be executed concurrently more than once (which is a waste of both CPU and memory resources). The proposed solution will eliminate that problem.

**Comment by mgautierfr** [comment]
Yes, that's why : 

> And there we release the lock to generate the value. This is an issue in itself as we may generate twice the value (not so important for the dirent, but we may decompress (loooong) twice the same cluster, especially with the clusterOrder iteration).

:wink:

**Comment by veloman-yunkan** [comment]
@mgautierfr I feel silly now

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan What is exactly left to do here?

**Comment by veloman-yunkan** [comment]
I think that the access to the dirent cache must be addressed in a different way. I vote for closing this ticket.

**Comment by kelson42** [comment]
@veloman-yunkan Thank you for your feedback. I agree with you. But I would like to secure that we keep track of the dirent cache topic properly. Would you be able please to open this ticket? I would then link this ticket to it and close it?

**Comment by veloman-yunkan** [comment]
@kelson42 Done
