### ISSUE TITLE
Debian package for libzim should be "libzim"

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#389]
It is currently "zimlib" which is the (really) old name of the library.

**Comment by legoktm** [comment]
There are two names for a Debian package, the "source package" name, which is currently `zimlib`, and the "binary package" names, which are `libzim-dev` and `libzim6`.

End users should only ever interact with the latter names which already use the libzim naming, which I think is the most important.

I'll ask some more experienced Debian Developers on how difficult it is to rename the source package and whether it's worth it.

**Comment by kelson42** [comment]
@legoktm Does that sounds doable? We are just about to release libzim7 which be available just after Debian Bulleye package freeze. To me is seems to be like the best timing to fix this problem.

**Comment by kelson42** [comment]
@legoktm Considering that libzim7 and that we start a new cycle at Debian, would that not be a good time to make this ticket?

**Comment by legoktm** [comment]
Sorry, forgot to update the ticket. Turns out this is pretty straightforward on the Debian side. I'll try and get a PR ready in the next few days.

**Comment by kelson42** [comment]
@legoktm Any news?

**Comment by kelson42** [comment]
@legoktm I reopen the ticket as the change has not been applied to Debian repository.

**Comment by legoktm** [comment]
This is still on my list to do, I'm just aiming to get the libzim7/libkiwix10 upgrades done first before the rename.

**Comment by kelson42** [comment]
@legoktm Now that you have even packaged and released on Debian the version 7.2.0 of the libzim, would that be a good time to do this renaming?

**Comment by kelson42** [comment]
@legoktm Sorry to insist but a year has passed and actually we could do it now. I see all is already done correctly for the PPA, just Debian official repo isstill wrong.

**Comment by kelson42** [comment]
Closing, Ticket has been open upstream at Debian and there is nothing more we can do here.
