### ISSUE TITLE
Libzim for Archlinux aarch64 without compiling

### ISSUE THREAD

**Issue by sobaee** [openzim/libzim#396]
Could you make it available to install this amazing module to Archlinux (aarch64) without compiling it manually?

 Either this, or python-libzim one?

Why it just support linux (86-64) 😞?

**Comment by kelson42** [comment]
It looks like Github CI allows aarch64 https://github.com/marketplace/actions/run-on-architecture. Should be theoritically possible.

**Comment by kelson42** [comment]
@sobaee Aarch64 is an architecture mostly for mobile devices... so not really part of our priorities to have a compiled version for python-libzim. Out of curiosity, whatkin of hardware do you use?

**Comment by mgautierfr** [comment]
The `run-on-architecture` action "simply" run the action under qemu to emulate a specific arch.

**Comment by sobaee** [comment]
@mgautierfr 
I just know some informations about archlinux and some commands which needed by a simple user

Could you just explain this with details, please?

**Comment by mgautierfr** [comment]
It is just a comment about how the `run-on-architecture` pointed by @kelson42 is working. There is no really more to say :)

**Comment by kelson42** [comment]
Will try to make a PR for that to at least have it in the CI

**Comment by kelson42** [comment]
@mgautierfr We need to move on this, more and more devices use this arch.
