### ISSUE TITLE
Handling of multipart ZIM files is broken under MacOS

### ISSUE THREAD

**Issue by veloman-yunkan** [openzim/libzim#398]
It looks like handling of multipart ZIM files is broken under MacOS, as demonstrated by the `ZimFile.multipart` unit-test: https://github.com/openzim/libzim/pull/387#issuecomment-667708593

**Comment by veloman-yunkan** [comment]
The issue is with the implementation of `std::map::equal_range()` under MacOS (which is used in [`FileCompound::locate()`](https://github.com/openzim/libzim/blob/6.1.8/src/file_compound.h#L59-L61)) . The implementation makes assumptions about the properties of the key comparison function and abuses the `std::map` requirement that it must contain unique keys. As a result, `std::map::equal_range(k).first != std::map::lower_bound(k)`. If in the said piece of code `equal_range(k)` is replaced with `{lower_bound(k), upper_bound(k)}` problem disappears.

**Comment by kelson42** [comment]
@automactic BTW, you need to beinformed

**Comment by kelson42** [comment]
@veloman-yunkan Do you have a clue when this regression has been introduced?

**Comment by veloman-yunkan** [comment]
@kelson I don't think this is a regession (at least not a recent one). It was discovered due to a new unit-test. Previously a multipart ZIM file flow was probably never exercised under MacOS.

**Comment by kelson42** [comment]
> @Kelson I don't think this is a regession (at least not a recent one). It was discovered due to a new unit-test. Previously a multipart ZIM file flow was probably never exercised under MacOS.

It is true that Kiwix Desktop for macOS is less used than the Windows or Linux one... but still, I wonder a bit that such a bug might have been long without beeing noticed.

**Comment by veloman-yunkan** [comment]
@kelson42 How common is the use of multipart ZIM files?

**Comment by kelson42** [comment]
@veloman-yunkan less and less, but a few people have habits.

**Comment by kelson42** [comment]
@veloman-yunkan It is currently not recommended as well to use randomly splitted files as they can cut the xapian index or videos... which then become unreadable. They should use `zim-split` but almost nobody use it (binaries are only available on Linux).

**Comment by veloman-yunkan** [comment]
@kelson42 Then it's unsurprising that no one has run against this issue under MacOS (since the bug is triggered only in case of multi-part ZIM files).

**Comment by mgautierfr** [comment]
And splitting zim file is only needed on file system that doesn't handle file bigger than 4GB (ie, only fat32 fs on windows).
