### ISSUE TITLE
[Idea] Memory mapped dirent cache

### ISSUE THREAD

**Issue by veloman-yunkan** [openzim/libzim#399]
This is just an idea. Everyone is welcome to criticize it. I am the first to do so (compare the Pros and Cons below).

In general, caching in the applications data that resides on storage in raw form in some sense duplicates low-level caching facilities of the operating system (support for memory mapped files).

`zim::Dirent` is conceptually close to being an object that is stored in the ZIM file in raw form. Its implementation can be changed so that it becomes a lightweight handle to a region of memory (actually a single pointer), which decodes its various fields on demand.

Then the dirent cache can be implemented as a special object that generates the dirents using their index and the [URL pointer list](https://wiki.openzim.org/wiki/ZIM_file_format#URL_Pointer_List_.28urlPtrPos.29). Some care must be taken to handle multi-part ZIM files with the dirent table cut between two or more parts (the areas around the cut points will have to be represented as small in-memory buffers).

Pros:
- No need to care about the size of the dirent cache. The OS will automatically manage the total memory usage by a libzim-based application (swapping out the least used data as needed).
- Dirents will be cheap to construct. Currently a dirent is constructed in its entirety, even if we need only its URL (for example during the search-by-URL operation).
- A lock-free thread-safe dirent cache (even in case of multi-part ZIM files, provided that the cache's data structures are constructed eagerly).

Cons:
- Access to individual fields of a dirent will become more costly.
- Going agains the KISS principle due to implementation complexity (especially, because of the need to handle multipart ZIM files).
- The granularity of caching via memory mapped files will typically be larger than caching of individual dirents. As a result effective virtual memory usage (the resident set size) may be larger for the case when there is a stable sparse set of dirents in active use (since each dirent will come with at least one memory page, and those spanning the page boundaries will bring with them two pages).
- The dirent table cannot be compressed (if we need that in the future).

**Comment by mgautierfr** [comment]
It is interesting but I'm not sure at all it is a good idea :)

> Dirents will be cheap to construct. Currently a dirent is constructed in its entirety, even if we need only its URL (for example during the search-by-URL operation).

The problem here is that expensive operation on dirent creation are getting the url and title. (because we don't know their length (and position for title))
Using a lazy cache to then all the time do long operation (several times) on it is somehow counterproductive.

> Dirents will be cheap to construct

Not so. Creating a mmap is time consuming see (https://stackoverflow.com/questions/45972/mmap-vs-reading-blocks). Doing it on small memory size may be worth that read it and parse it.

> Some care must be taken to handle multi-part ZIM files with the dirent table cut between two or more parts

[`FileReader::get_buffer`](https://github.com/openzim/libzim/blob/master/src/file_reader.cpp#L126-L155) already takes care of that.

**Comment by veloman-yunkan** [comment]
@mgautierfr 

I guess there is some misunderstanding of the proposal. Dirent's will not be `mmap`-ed individually. The entire dirent table will be `mmap`-ed (here is why we may need to handle the case of split ZIM files by creating two or more mappings and an in-memory buffer serving as a seam between them).

> The problem here is that expensive operation on dirent creation are getting the url and title.

When considered in isolation that's correct. But in the overall picture, the slow operation is the cache lookup and maybe the IO syscall in case of a cache miss. This proposal addresses those sources of poor performance (as well as, aims to drop the issue of having to care about the dirent cache size). Besides, the biggest bottleneck in the current implementation is the search by URL, which needs only the URL (i.e. the title is ignored). Fortunately, the URL is in the beginning of a dirent's serialized layout and will be the quickest to restore (especially if we change the return type of `Dirent::getUrl()` from `std::string` to `const char*`).

**Comment by mgautierfr** [comment]
> I guess there is some misunderstanding of the proposal. Dirent's will not be mmap-ed individually. The entire dirent table will be mmap-ed (here is why we may need to handle the case of split ZIM files by creating two or more mappings and an in-memory buffer serving as a seam between them).

The main problem here is that there is no dirent table.
Nothing in the spec say how and where the dirent should be stored. Just that the offsets in `UrlPtrList` must point to a dirent. They can be put all together or sparsely.

> But in the overall picture, the slow operation is the cache lookup and maybe the IO syscall in case of a cache miss.

Then we should fix the cache lookup (#385)

> Fortunately, the URL is in the beginning of a dirent's serialized layout

It is not. And the offset depends of the type of the dirent (need a 2 bytes reading (with endian conversion) to know the type)

> Besides, the biggest bottleneck in the current implementation is the search by URL, which needs only the URL (i.e. the title is ignored). 

I agree. But we can do this without mmaping the dirent.
The real question is what is the most efficient :
- Parsing the data at creation (costly) and have cheap member access,
- Do lazy (cheap) creation and have costly member access ?

But I cannot answer this question right now.
On top of that, with the plan to add extradata to entries we will also need to read parameters of a dirent, and we cannot find its offset without reading url and title.

**Comment by veloman-yunkan** [comment]
> The main problem here is that there is no dirent table.
> Nothing in the spec say how and where the dirent should be stored. Just that the offsets in `UrlPtrList` must point to a dirent. They can be put all together or sparsely.

In theory this is the most serious argument against my idea. However, how sparsely can the dirents be scattered inside a ZIM file in practice? In theory, they can appear even inside clusters if some fragment of a cluster (maybe even a compressed one) coincides with some dirent and the ZIM writing tool detects and decides to take advantage of that fact. In practice, dirent's must be clustered between clusters and therefore cannot be too sparse. Handling such a fragmented dirent table is not very different from having to handle multipart ZIM-files.

**Comment by veloman-yunkan** [comment]
> > But in the overall picture, the slow operation is the cache lookup and maybe the IO syscall in case of a cache miss.
> 
> Then we should fix the cache lookup (#385)

But the issue of the optimal cache size and syscalls in case of cache misses remains.

**Comment by veloman-yunkan** [comment]
> > Fortunately, the URL is in the beginning of a dirent's serialized layout
> 
> It is not. And the offset depends of the type of the dirent (need a 2 bytes reading (with endian conversion) to know the type)

I meant *in the beginning relative to other variable sized fields*. Endian conversion can be avoided, so the overhead is just reading a `uint16_t`.

**Comment by mgautierfr** [comment]
> syscalls in case of cache misses remains.

Most of the time we do only one syscall (one read) in case of cache misses. mmap may not help here.

> In theory, they can appear even inside clusters if some fragment of a cluster (maybe even a compressed one) coincides with some dirent and the ZIM writing tool detects and decides to take advantage of that fact. In practice, dirent's must be clustered between clusters and therefore cannot be too sparse. Handling such a fragmented dirent table is not very different from having to handle multipart ZIM-files.

In practice, libzim write them consecutively. But other may write them otherwise.
The difficulty is to know what are the ranges. We have to read all the offsets to know all the start of the dirents. Then we have to figure a way to detect dirents' regions (without knowing the size of the dirents).

Then we have to mmap all those regions, and have a map `dirent's offset` to `mmap "id" and offset in it`.

Then each time we want to url of a dirent, we have to read its offset (using `UrlPtrList`), then figure out in which mmap read and at which local offset. Then parse the mimetype to know the type of the dirent, then get the url. (Hoping that the page is mapped and kernel doesn't have to map it). Compared to a simple read/parse in a structure, this is not simple.

On top of that, as we do binary search, some dirents will be accessed a lot of time. Removing the cache may be counterproductive.

Handling multipart ZIM-files is pretty simple compared to all this. All the high level algorithm are unaware of this and only the low level parts (`FileReader::read` and `FileReader::getBuffer`) handle this.

**Comment by veloman-yunkan** [comment]
> Most of the time we do only one syscall (one read) in case of cache misses. mmap may not help here.

I don't get this point.

> Then each time we want to url of a dirent, we have to read its offset (using UrlPtrList), then figure out in which mmap read and at which local offset. Then parse the mimetype to know the type of the dirent, then get the url. (Hoping that the page is mapped and kernel doesn't have to map it). Compared to a simple read/parse in a structure, this is not simple.

You make the proposal look at a disadvantage to the *simple read/parse* by decomposing into lower-level steps the former but not the latter. This form of argument reminds me of a tale where a sly man convinces a simpleton that he could walk/run faster than a horse, because while the horse would move his legs oooneee-twooooo-threeeeee-fooooouuuur, he could quickly do one-two, one-two. :smiley:

**Comment by mgautierfr** [comment]
> Most of the time we do only one syscall (one read) in case of cache misses. mmap may not help here.

Most of the time we need only only one syscall (one read) to read a dirent.
The `urlPtrList` is already mmaped (so getting the offset from it is no syscall). We read (syscall) the content of the dirent into an already allocated buffer. The parsing of the buffer is done without syscall.

We may end with more syscall with the rare case of the dirent is bigger than 256 bytes or the dirent is in two different zim part.

> This form of argument reminds me of a tale where a sly man convinces a simpleton that he could walk/run faster than a horse, because while the horse would move his legs oooneee-twooooo-threeeeee-fooooouuuur, he could quickly do one-two, one-two

It is up to you to convince me that "prepare the mmaps, avoid a read when accessing a dirent and parse dirent's member at all access" will be cheaper than "read and parse when accessing dirent" (I assuming we have efficient cache with #385)
(Ie, that horse has long legs than human :) )

**Comment by mgautierfr** [comment]
> So, if it eliminates the syscall, why won't mmap help (provided that there is no page-fault)?

Because `Access to individual fields of a dirent will become more costly.`

> I will do it via a quick&dirty prototype implementation of my idea.

You will have to solve `The difficulty is to know what are the ranges. We have to read all the offsets to know all the start of the dirents. Then we have to figure a way to detect dirents' regions (without knowing the size of the dirents` before.

And then, we will compare a solution without cache with a solution with a poorly implemented cache. We should probably fix #385 first.

**Comment by veloman-yunkan** [comment]
> We should probably fix #385 first.

OK

**Comment by mgautierfr** [comment]
To be more exact, it is not that mmap should not be used.
It is the mmap on a lot of data that may reserved a lot of (continuous) memory address.
But it really doesn't change the problem here as the idea is to map all the dirents in once.
