### ISSUE TITLE
getNamespaceEndOffset() and getNamespaceBeginOffset() return wrong values

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#407]
it seems that neither getNamespaceEndOffset and getNamespaceBeginOffset return good value for limits value (missing namespace at the border of the range and touching existing namespace).

Follower of https://github.com/openzim/libzim/pull/382#issuecomment-681836803

**Comment by kelson42** [comment]
@mgautierfr What is the impact of this bug?

**Comment by veloman-yunkan** [comment]
Quoting https://github.com/openzim/libzim/pull/382#issuecomment-681836803:

> We should add unit tests (to be sure we don't break what is working) and then fix this (and I think we should not fix the algorithm but use `std::lower_bound`, `std::upper_bound`, `std::equal_range` and `std::binary_search`.

I think that we can afford replacing `std::map<char, article_index_t>` as the underlying container for  `NamespaceCache` with an `std::vector<article_index_t>` (where the namespace char is used as an index into the array). Then we will avoid the binary search.

**Comment by mgautierfr** [comment]
The `std::map<char, article_index_t>` is pretty small (it contains only few items, `A`, `I`, `J`, `X`, `M` and `-`. On new zim files it will contains only `M`, `X` and `C`).

But I agree with the idea of a vector. It is what I called a "fanout" algorithm in our previous discussions. I've just opened https://github.com/openzim/libzim/issues/424 to speak about it.

**Comment by veloman-yunkan** [comment]
It looks like only `getNamespaceEndOffset()` was buggy
