### ISSUE TITLE
New build system is not detecting cxxtools and tests are disabled

### ISSUE THREAD

**Issue by copyninja** [openzim/libzim#41]
Hi,

New meson build system is unable to find `libcxxtools-dev` on Debian possibly due to missing pkg-config files. This disables the unit tests. Its always recommended for Debian package to run the unit tests when they are present but this is not happening with new release.

Previous build had option `--enable-unittest` which allowed running test. I would highly appreciate a solution for this.

**Comment by kelson42** [comment]
@mgautierfr Any idea?

**Comment by kelson42** [comment]
@legoktm might be interesting for you too.

**Comment by legoktm** [comment]
This looks like an issue with the Debian package I think. Upstream provides the necessary pkg-config files in the latest release, but the cxxtools pakage doesn't seem to be installing them at all (c.f. https://packages.debian.org/sid/amd64/libcxxtools-dev/filelist)

**Comment by legoktm** [comment]
Huh. Turns out https://anonscm.debian.org/cgit/collab-maint/cxxtools.git/commit/?h=debian&id=36219f04742e7cd6ed7beed3a07ae31e05a1d17a was committed to the git repository but never actually uploaded to the archive. Probably worth a bug report to the maintainer(s)?

**Comment by mgautierfr** [comment]
@legoktm seems to have pointed the problem on cxxtools packaging side.

libzim meson system build automatically the tests if `cxxtools` dependency is found.
Tests can be run using `mesontest` or `ninja test` inside the build directory.

**Comment by kelson42** [comment]
@copyninja May we close that ticket?

**Comment by copyninja** [comment]
Please report the bug against cxxtools.

**Comment by copyninja** [comment]
Yes. Thanks

**Comment by legoktm** [comment]
For reference, followed as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871416
