### ISSUE TITLE
Optimization of random access to dirents

### ISSUE THREAD

**Issue by veloman-yunkan** [openzim/libzim#410]
Dirents are the second biggest type of data in ZIM files. In certain scenarios, for example `zimcheck -U`, random access to dirents can be a serious source of sub-optimal performance (need to support this claim with factual evidence). Current implementation of dirent caching doesn't solve the stated problem in the best way (for example, one has to care about the dirent cache size).

This ticket was opened as a follow-up to #379

**Comment by kelson42** [comment]
@veloman-yunkan @mgautierfr What is the plan here?
