### ISSUE TITLE
Packaging status in README.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#419]
We recently introduce a "status badge" in the README to have the packaging status of libzim in different distribution.

I'm not against "status badge" but here it takes a lot of space (more than one screen).
Is this status really necessary ? It is possible to have a smaller version (same size than other badges) ?

**Comment by data-man** [comment]
Many projects has packaging status in wiki pages.

**Comment by kelson42** [comment]
> Many projects has packaging status in wiki pages.

This is an interesting idea, we could bind this page with one badge "packages" in the README.

**Comment by data-man** [comment]
https://github.com/ziglang/zig/wiki/Install-Zig-from-a-Package-Manager
