### ISSUE TITLE
Secure proper functioning of libzim without Xapian

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#423]
Xapian is an optional dependence, but the scenario without Xapian is rare and suffer of many problems:
* The compilation without Xapian is implicite (does not compile if Xapian is not on the system). It should be explicit, ie. there should be a way to tell Meson to compile with or without Xapian.
* It seems the compilation might fail in the scenario of Xapian missing on not on the system, see https://github.com/kiwix/kiwix-lib/pull/117
* Compilation without Xapian should be part of the CI
* ZIM writting and reading of ZIM files without Xapian based indexes should be tested:
    * ZIM creation
    * ZIM reading in particular: call of ft related methods and suggestions
* Compilation without Xapian should be documented in the README.md or CONTRIBUTING.md

**Comment by kelson42** [comment]
@mgautierfr What is left to do?

**Comment by mgautierfr** [comment]
- The compilation without Xapian is implicite (does not compile if Xapian is not on the system). It should be explicit => DONE
- It seems the compilation might fail in the scenario of Xapian missing on not on the system, see kiwix/kiwix-lib#117 => Probably DONE
- Compilation without Xapian should be part of the CI => DONE
- ZIM writting and reading of ZIM files without Xapian based indexes should be tested => It is difficult to test as we need different compilation. And there is not a lot to test, as the functions don't exist at all if libzim is compiled without xapian
- Compilation without Xapian should be documented in the README.md or CONTRIBUTING.md => TODO (but it is "standard" meson option)
