### ISSUE TITLE
ClusterTest.read_extended_cluster failing on armhf architecture

### ISSUE THREAD

**Issue by legoktm** [openzim/libzim#427]
The most recent builds of libzim in the PPA are failing on the armhf architecture:

```
17:32:54 /<<BUILDDIR>>/zimlib-6.2.2+git202009231723.2b4558b~groovy/obj-arm-linux-gnueabihf/test/cluster
--- stdout ---
Running main() from /build/googletest-CcIXyV/googletest-1.10.0/googletest/src/gtest_main.cc
[==========] Running 8 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 8 tests from ClusterTest
[ RUN      ] ClusterTest.create_cluster
[       OK ] ClusterTest.create_cluster (0 ms)
[ RUN      ] ClusterTest.read_write_cluster
[       OK ] ClusterTest.read_write_cluster (0 ms)
[ RUN      ] ClusterTest.read_write_empty
[       OK ] ClusterTest.read_write_empty (1 ms)
[ RUN      ] ClusterTest.read_write_clusterZ
[       OK ] ClusterTest.read_write_clusterZ (2 ms)
[ RUN      ] ClusterTest.read_write_clusterLzma
[       OK ] ClusterTest.read_write_clusterLzma (1671 ms)
[ RUN      ] ClusterTest.read_write_clusterZstd
[       OK ] ClusterTest.read_write_clusterZstd (1526 ms)
[ RUN      ] ClusterTest.read_write_extended_cluster
[       OK ] ClusterTest.read_write_extended_cluster (0 ms)
[ RUN      ] ClusterTest.read_extended_cluster
unknown file: Failure
C++ exception with description "
Assertion failed at ../src/buffer.cpp:55
 offset.v+size.v[4294968320] <= m_size.v[0]" thrown in the test body.
[  FAILED  ] ClusterTest.read_extended_cluster (2 ms)
[----------] 8 tests from ClusterTest (3203 ms total)

[----------] Global test environment tear-down
[==========] 8 tests from 1 test suite ran. (3203 ms total)
[  PASSED  ] 7 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ClusterTest.read_extended_cluster

 1 FAILED TEST
```

I can provide the full build log if you need it.

**Comment by kelson42** [comment]
I wonder why our CI did not cautch that one? We don't test on armfh?

**Comment by legoktm** [comment]
> I wonder why our CI did not cautch that one? We don't test on armfh?

Correct, CI is just on amd64 for now. I'm sure it's theoretically possible to set up CI for armhf, but I haven't looked into that yet.

**Comment by kelson42** [comment]
There is as well a new warning, which might be good to remove:
```
[69/82] Compiling C++ object 'test/9f86d08@@bufferstreamer@exe/bufferstreamer.cpp.o'.
../test/bufferstreamer.cpp:35:13: warning: ‘std::string {anonymous}::toString(const zim::Buffer&)’ defined but not used [-Wunused-function]
   35 | std::string toString(const Buffer& buffer)
      |             ^~~~~~~~
[81/82] Installing files.
```

**Comment by veloman-yunkan** [comment]
@legoktm I have a [tentative fix](https://github.com/openzim/libzim/pull/428) for this issue based solely on code review. Will you please check that it indeed fixes the bug?

**Comment by kelson42** [comment]
@veloman-yunkan Thx for the quick fix. It might be defficult for @legoktm (our Debian packager) because the problem has poped up in our PPA CI which is not under our control.

I wonder a bit that such a fix impacts only certain architectures... Looks like a generic bug. If confirmed, I suspect we can just go one with the review and we will see if that fixes as well our ARM bug.

Otherwise, what about the warning (see my comment)?

**Comment by veloman-yunkan** [comment]
> Otherwise, what about the warning (see my comment)?

Fixed that one too.

**Comment by kelson42** [comment]
@veloman-yunkan Perfect, thx for having put your PR in review.

**Comment by legoktm** [comment]
Sorry, I've been busier than expected this past week. Thanks for the fix, the latest PPA builds have all passed.

In the future, I have access to servers running most architectures through Debian (slightly different than the Ubuntu PPA setups, but hopefully close enough) and can test stuff as needed.
