### ISSUE TITLE
Introduce `Formatter` in libzim.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#432]
This class is nice. I may worth to move this in libzim's tools and use it everywhere we create a stringstream in our code.
This could even be merged with a `to_string` function.

_Originally posted by @mgautierfr in https://github.com/openzim/zim-tools/pull/158#discussion_r497382543_

**Comment by kelson42** [comment]
This is not really clear to me about which class and which added value this would bring.

**Comment by mgautierfr** [comment]
We are speaking about the `Formatter` class @asashnov introduces in openzim/zim-tools#158

It will allow us to replace all
```
std::stringstream ss;
ss << "foo" << variable;
use_string(ss.str());
```

in our code by
```
use_string(Formatter() << "foo" << variable);
```

**Comment by YPD-HG** [comment]
I wanna on this issue ,please assign this to me and since i am sort of new in repo your help (if needed) will be great!

**Comment by mgautierfr** [comment]
Welcome @YPD-HG.
This issue should be pretty easy as the code already exists in the zim-tools repository.
It would be nice to have a two commits PR here (one to add the "formater", one other to adapt libzim code and use the "formater")

**Comment by viragjain30** [comment]
Hello @kelson42 & @mgautierfr.

I am interested in working on this issue and it would be great if you assigned this issue to me and may need your help as I am new to this repo but very interested to work on it.
