### ISSUE TITLE
Article creator getPath() works asynchronously

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#437]
But there is no proper way to know if the file at the given path can be deleted.

This is not correct, we should either:
* Have a way to know if the file has been used (callback for example)
* Read the file syncrhonously
* Remove the whole API

Follower of https://github.com/openzim/python_scraperlib/issues/69

**Comment by mgautierfr** [comment]
The next api doesn't have this problem as the user code has to provide a `ContentProvider`. It is in charge to read the data and so can do as it which.
