### ISSUE TITLE
Correctly write empty cluster ?

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#442]
It seems that cluster writing is buggy as we create empty cluster without offset and we should have at least one to parse it correctly.
But in the same time, we never try to write an empty cluster.

An empty cluster should be at least 1 + OFFSET_SIZE.
(OFFSET_SIZE being 4 or 8 depending if cluster is extended or not).
This is needed for the reader to know the cluster has no data. Else it will read garbage data after the first byte.

However, the writer's cluster doesn't do this and write only the first byte.
But in the same time, the creator check that the cluster is not empty before closing (and writing) it.

While the libzim creator is in the same time buggy (because we would wrongly create empty cluster) and not buggy (we never create empty cluster), we should assume when checking that clusterMinSize is 5.

_Originally posted by @mgautierfr in https://github.com/openzim/libzim/pull/425#discussion_r520669186_

Maybe just add a assert in cluster writing is enough.

**Comment by kelson42** [comment]
@veloman-yunkan What would be the best approach to your opinion?

**Comment by veloman-yunkan** [comment]
The severity of this issue is very low (if it is an issue at all, since the described problem is mostly theoretical). I don't think we should spend time looking for a solution before this becomes a real problem.

**Comment by kelson42** [comment]
@veloman-yunkan Ok. I'm not really eager to keep bug ticket open for ever. Would you agree to put an assert like suggested by @mgautierfr? To me this seems a good compromise.

**Comment by veloman-yunkan** [comment]
> Would you agree to put an assert like suggested by @mgautierfr?

@kelson42 I do agree

**Comment by kelson42** [comment]
Would be good to make a test to test this.
