### ISSUE TITLE
Gather informations about dependence libraries version

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#452]
With our tools (typically zim-tools and kiwix-tools), we need to know which versions of the libzim/libkiwix/... binary runs against.

Therefore. we should be able to deliver the list of librairies we need with there version used for compilation/linking.

The tools, following a similar procedure with their own deps, should be able to print the information with option `-v`.

**Comment by lizfrank** [comment]
That's great!  It sounds like exactly what we need.  Thank you.  Do you have any idea when it will be implemented?

**Comment by kelson42** [comment]
@lizfrank there is no ETA for now, nobody is foreseen to work on it for the moment.

**Comment by pranavich18** [comment]
@kelson42  I would like to work on this can you explain more about the issue.

**Comment by mgautierfr** [comment]
https://github.com/openzim/libzim/pull/465 make libzim install the `libzim_config.h` header with the define `LIBZIM_VERSION` set.
Depending projects can now use this define to print the libzim version to the user.
(Not sure we should also display information about libzim dependencies (zstd, ...). And it is probably not to the libzim library to handle this)

**Comment by kelson42** [comment]
What is asked in the ticket is not delivered yet. We should keep the ticket open or revamp it.

**Comment by mgautierfr** [comment]
We have a define publicly available. External software can use it to display them.

**Comment by kelson42** [comment]
I believe we should have a method delivering this list, otherwise each software will have to handle the whole stack of deps on its own. Which is super annoying.

**Comment by mgautierfr** [comment]
I don't think that libzim should export version of other libraries.

**Comment by kelson42** [comment]
> I don't think that libzim should export version of other libraries.

If we don't do so, we will have:
* A lot of duplicate in each end-user software
* Each software developer will have to be aware about the full dependence stack to be able to display it.
* Each time we add/remove a dependence, or each time the way to retrieve the version in a dependence change, all the softwares will have to be patched

@mgautierfr So why would want to do that if a simply abstraction in libzim/libkiwix would provide this in a normalised manner?

**Comment by adigitoleo** [comment]
Alternative idea, possibly complimentary: version the ZIM file spec. Track somewhere (changelogs) which versions of libzim/zimwriterfs/etc. are compatible with which ZIM spec version. This is done for other file formats, e.g. [hdf5](https://docs.hdfgroup.org/hdf5/develop/_s_p_e_c.html), toml, etc.
