### ISSUE TITLE
Possible I/O performance issue in Cluster::write()

### ISSUE THREAD

**Issue by asashnov** [openzim/libzim#455]
libzim 'master' (540bc34d)

Cluster::write() writes data in 4k chunks, instead of 4Gib:

libzim/src/writer/cluster.cpp
```c
void Cluster::write(int out_fd) const
...

    case zim::zimcompNone:
    {
      auto writer = [=](const Blob& data) -> void {
        // Ideally we would simply have to do :
        // ::write(tmp_fd, data.c_str(), data.size());
        // However, the data can be pretty big (> 4Gb), especially with test,
        // And ::write fails to write data > 4Gb. So we have to chunck the write.
        size_type to_write = data.size();
        const char* src = data.data();
        while (to_write) {
         size_type chunk_size = to_write > 4096 ? 4096 : to_write;
         auto ret = _write(out_fd, src, chunk_size);
         src += ret;
         to_write -= ret;
        }
      };
      write_content(writer);
      break;
    }
```

In another place in code the data read from file in chunks of 1MiB:

```c
void Cluster::write_data(writer_t writer) const
...
      char* buffer = new char[1024*1024];
      while (true) {
        auto r = read(fd, buffer, 1024*1024);
```

**Comment by kelson42** [comment]
@veloman-yunkan Is that a valid remark?

**Comment by veloman-yunkan** [comment]
@kelson42 I don't think so.

**Comment by kelson42** [comment]
@veloman-yunkan Ok, then we should close it with a small explanation.

**Comment by veloman-yunkan** [comment]
Actually, 4KiB chunks may be too far away from the sweet spot of I/O write operations, however I don't have any idea how significant an impact that may have on the overall performance of ZIM creation. Pursuing this issue separately doesn't make much sense. It should be considered in the wider context of ZIM creation performance analysis and optimization.

**Comment by kelson42** [comment]
@mgautierfr Reassigning to you as we have discussed the topic and agree that there is nothing to loose to write bigger chunks.
