### ISSUE TITLE
Calling zim::Search::end() before zim::Search::begin() leads to an infinite loop

### ISSUE THREAD

**Issue by veloman-yunkan** [openzim/libzim#463]
`zim::Search::end()` returns a meaningful end iterator only if the search object has been properly initialized before that by a call to `zim::Search::begin()`. As a result, the following code is an infinite loop:

```
const zim::Search search(archive);
... // initialize the search
const auto endOfSearch = search.end();
for ( const auto it = search.begin(); it != endOfSearch; ++it ) {
}
```

This is very counter-intuitive, especially given that both `zim::Search::begin()` and `zim::Search::end()` are `const` member functions.

**Comment by kelson42** [comment]
@veloman-yunkan What should be returned to fix that problem? An exception should throwed?
