### ISSUE TITLE
Zstd compression should be always used

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#467]
Lzma compression should not be used anymore

**Comment by kelson42** [comment]
See as well #431

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan Can one of you to that briefly please? With #431?

**Comment by veloman-yunkan** [comment]
> @mgautierfr @veloman-yunkan Can one of you to that briefly please? With #431?

There is a saying that when more than one person is in charge, no one is in charge. Probably that's how this request missed my attention.

**Comment by kelson42** [comment]
> > @mgautierfr @veloman-yunkan Can one of you to that briefly please? With #431?
> 
> There is a saying that when more than one person is in charge, no one is in charge. Probably that's how this request missed my attention.

I can not be more agree. Usually I say that myself. You are in charge.
