### ISSUE TITLE
Possible Leaks when calling getContentByURL

### ISSUE THREAD

**Issue by automactic** [openzim/libzim#47]
When building the kiwix for macOS, I encountered possible leaks in libzim. Please see call tree below.
![screenshot 2017-08-29 10 04 41](https://user-images.githubusercontent.com/8294252/29825353-235c1076-8ca2-11e7-9664-ac61fc26241a.png)

**Comment by holta** [comment]
@mgautierfr thx!

Do you happen to know why kiwix-tools have not been published to http://download.kiwix.org/nightly/ since, during this past half-week?

**Comment by kelson42** [comment]
@holta Please open new tickets for new questions or bug reports.
