### ISSUE TITLE
online documentation is not current version

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#472]
README (discreetly) point to https://libzim.readthedocs.io/ which should contain the CI-built documentation.

This documentation currently describe the *previous* API (before libzim-next) from 2020-08-18.

I imagine this is due to that code not being released but still

**Comment by kelson42** [comment]
We need to update the CI to:
* Make a static version of the doc per release
* Make the version choosable in the readthedocs sidebar
* Make a `dev` version each time git head master is changed

**Comment by mgautierfr** [comment]
readthedocs was configure to use the doc branch for latest.
Now it is master. (Refresh your browser)

**Comment by rgaudin** [comment]
Great. Closing. @kelson42 reopen if you think the versioning is still necessary.
