### ISSUE TITLE
zim::parseLongPath() should handle paths consisting of the namespace only

### ISSUE THREAD

**Issue by maneeshpm** [openzim/libzim#477]
Currently if a url like `"A"` is given to the function, it throws an error. A more appropriate response should be to return the namespace character(if any) along with an empty string like `(ns, "")`.
This will help in fixing openzim/zim-tools#171. Refer openzim/zim-tools#216.

**Comment by maneeshpm** [comment]
@veloman-yunkan the way zim::archive::findByPath is implemented, it uses `path` to find `begin_idx` and `path.back()++` to find the `end_idx`. If I add a check to consider only namespace chars in `parseLongPath()`, the function will break in the `end_idx` call. To prevent this, I have to modify the check to include namespace chars and the next chars (like `J` followed by `K`). 
This looks a bit messy to me, I think handling namespace chars inside the `findByPath` function as an `else if` case is better so that `parseLongPath()` can only handle namespace chars.

**Comment by veloman-yunkan** [comment]
@maneeshpm I don't fully understand your last comment. If you wrote it because I edited the title of this ticket, then please be advised that I didn't suggest by that action any change in the intended way of fixing this issue - I only wanted to make the title describe the problem, rather than how it should be fixed.

**Comment by maneeshpm** [comment]
Thanks for the clarification @veloman-yunkan, Let me open a draft pr so that I can point out the implementation issue.

**Comment by veloman-yunkan** [comment]
@maneeshpm OK, I looked at the code and now I understand your comment. However, I don't understand why you decided to change your fix from what you used in https://github.com/openzim/zim-tools/issues/171#issuecomment-761817734

**Comment by maneeshpm** [comment]
@veloman-yunkan That fix doesn't check if the passed namespace is a valid namespace char(one of -,A,B,C,I,J,M,U,V,X). It seems `findx` is already handling the wrong paths, so this check might be unnecessary. Should I revert to the old fix?

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan That fix doesn't check if the passed namespace is a valid namespace char(one of -,A,B,C,I,J,M,U,V,X)

It's not `parseLongPath()``s job to check if the namespace component is valid. Similarly it doesn't check that the path component is valid. It only has to split the long path into two parts.

> Should I revert to the old fix?

Yes, please
