### ISSUE TITLE
zim::windows::FD::close() buggy for a FD constructed from a POSIX file descriptor

### ISSUE THREAD

**Issue by veloman-yunkan** [openzim/libzim#478]
[`zim::windows::FD:FD(int fd)`](https://github.com/openzim/libzim/blob/6.3.0/src/fs_windows.cpp#L60-L61) constructor works via [`_get_osfhandle()`](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/get-osfhandle?view=msvc-160):

```c++
FD::FD(int fd):
  mp_impl(new ImplFD(reinterpret_cast<HANDLE>(_get_osfhandle(fd)))) {}
```

The documentation of `_get_osfhandle()` [requires](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/get-osfhandle?view=msvc-160#remarks):

> To close a file whose operating system (OS) file handle is obtained by `_get_osfhandle`, call `_close` on the file descriptor *`fd`*. Never call `CloseHandle` on the return value of this function. 

However, [`zim::windows::FD:close()`](https://github.com/openzim/libzim/blob/6.3.0/src/fs_windows.cpp#L126-L132) doesn't respect above requirement:

```c++
bool FD::close()
{
  if (!mp_impl || mp_impl->m_handle == INVALID_HANDLE_VALUE) {
    return false;
  }
  return CloseHandle(mp_impl->m_handle);
}
```

**Comment by kelson42** [comment]
@veloman-yunkan I'm not sure about the nature of the ticket? What is the user impact? Should we not fix it right now as we are bringing this new feature to the libzim?

**Comment by veloman-yunkan** [comment]
The new feature shouldn't claim Windows support. Let's limit its usage to the Android app for a while. I don't think that this bug can affect the users. Currently it can only fail a unit-test, though it doesn't.

**Comment by kelson42** [comment]
@veloman-yunkan Got it, yes, this feature should be available only Linux/Android, unit tests for this feature should run consequently only on Linux OS and be ignored otherwise.

**Comment by kelson42** [comment]
@veloman-yunkan Now that #449 has been merge, could we fix/close this one so we are “clean” regarding fd handling?

**Comment by veloman-yunkan** [comment]
@kelson42 Do you mean implementing full support for fd handling under Windows? If not, I don't see what fixing this issue will buy us now.

**Comment by kelson42** [comment]
@veloman-yunkan I probably don’t understand properly what this ticket is about. Windows does not handle ZIM content given via FD. This is not even a requirement. This ticket seems to complain that a Windows FD dedicated part of the libzim does not work properly. I wonder in a first place why it exists? Then if it has to exist this should clearly die (an ASSERT?) as non supported feature. Both way i would like to avoid leaving this ticket open as it seems a small unclean edge case mgmt and easy to fix.

**Comment by veloman-yunkan** [comment]
@kelson42 This ticket is about a *potential* issue identified while reading the documentation and code. I prefer to report issues as soon as I find them. I think that the current situation doesn't justify spending any effort on this ticket, but that may not always be true.

**Comment by kelson42** [comment]
@veloman-yunkan I appreaciate you opened the ticket. I fear this ticket will be open for years. How long would be needed to fix it?

**Comment by veloman-yunkan** [comment]
> I fear this ticket will be open for years. How long would be needed to fix it?

@kelson42 Anywhere from half an hour to several days if it is valid to generalize the experience we had with #479. Frankly I don't care about this ticket at all. I don't mind if it is closed right away.

**Comment by mgautierfr** [comment]
Would it be possible to delete `zim::windows::FD:FD(int fd)` ?
Or do we use it somewhere ?

**Comment by veloman-yunkan** [comment]
> Would it be possible to delete `zim::windows::FD:FD(int fd)` ?
> Or do we use it somewhere ?

If I remember correctly, it is used only in a unit test.
