### ISSUE TITLE
Enable Discussions

### ISSUE THREAD

**Issue by data-man** [openzim/libzim#485]
GitHub Discussions [now available](https://github.blog/changelog/2020-12-08-github-discussions-now-available-as-a-public-beta/) for beta testing.

It would be nice to enable them for (all/some) openZIM's repositories.
Another idea: new empty repository with enabled discussions for all openZIM's projects.

**Comment by Popolechien** [comment]
Ok, I've enabled these on [/zim-requests](../../zim-requests/discussions) as it is one of the most outward-facing. We'll see how that pans out.

**Comment by kelson42** [comment]
@Popolechien Thx for the experimentation. I'm not 100% convinced this is a good move, but lets try for a few months with only one repository. If it works well we could then see if this makes sense to activate it on other repositories.
