### ISSUE TITLE
windows.h min/max macros interfere with std::min/max

### ISSUE THREAD

**Issue by maneeshpm** [openzim/libzim#489]
[#497](https://github.com/openzim/libzim/pull/479) 
`windows.h` includes macros `min` & `max` which might interfere with `std::min()` and `std::max()` functions. 
Can be handled by explicitly mentioning function return type like `std::min<int>();`

**Comment by veloman-yunkan** [comment]
FYI,@mgautierfr had the same issue in #487 and he [solved it differently](https://github.com/openzim/libzim/pull/487/commits/2f5f4994539b336c46855b1bea8572d6d98d6026)
