### ISSUE TITLE
Disparity in results with suggestions kiwix-search

### ISSUE THREAD

**Issue by maneeshpm** [openzim/libzim#491]
using file: wikipedia_en_100_maxi_2021-01.zim
Firstly searching "world" with suggestions flag:
```
$ kiwix-search --suggestion wikipedia_en_100_maxi_2021-01.zim "world"
World Trade Center 1
World Trade Center 2
World Trade Center (1973)
World Trade Center (1973–2001)
Original World Trade Center
World Trade Center (1970-2001)
World Trade Twin Tower
World Trade Center Towers
First World Trade Center
Old World Trade Center
```
Now running without suggestion flag:
```
$ kiwix-search wikipedia_en_100_maxi_2021-01.zim "world"
World Trade Center (1973–2001)
Australia
United States
Association football
Germany
India
Philippines
Michael Jackson
Primate
Hong Kong
```
Apart from the sorting issue(kiwix/kiwix-tools#360), It seems some entries are missing when we search without suggestions. Not sure if this is the expected behavior. Looks related to #474 as well.

**Comment by kelson42** [comment]
@maneeshpm It seems normal to me that two different search tools give too different results. The suggestion system works only on indexes with title whereas the search works on fukltext search.

**Comment by maneeshpm** [comment]
Okay! so the idea is to search over titles when generating suggestions and over fulltext when we perform a full search. Thanks for the info, I guess this issue can be closed now.
