### ISSUE TITLE
Is auto-indexing limited to text/html Items?

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#500]
Testing current libzim nightly ([2021-02-16](http://download.openzim.org/nightly/2021-02-16/), via pylibzim), I get the expected behavior:

- adding HTML content to an Item with `text/html` -> is indexed
- adding HTML content to an Item with `application/octet-stream` -> is not indexed

Wanting to check what kind of mime types were allowed for indexation, I couldn't find where this behavior is applied in the current code base.

The default `Item::getIndexData()` doesn't seem to discriminate any mime type and simply passes the whole content's string to `DefaultIndexData` which itself simply parses it as HTML and index its result.

https://github.com/openzim/libzim/blob/cc6c256661dcbf4c538a08f2b108b2f3a2bda02a/src/writer/item.cpp#L102-L114

https://github.com/openzim/libzim/blob/cc6c256661dcbf4c538a08f2b108b2f3a2bda02a/src/writer/item.cpp#L31-L41

Where is the observed discrimination applied?

**Comment by mgautierfr** [comment]
Are you sure of testing 2021-02-16 version ? Maybe you have a environment linking to a previous version of libzim.

Previous "version" of libzim have this test here : https://github.com/openzim/libzim/blob/7915388cb9727a16c9bb8bec5bb228fc73bf29b1/src/writer/creator.cpp#L174-L182

However, recent PR (with this commit : https://github.com/openzim/libzim/commit/d70dd56793d04ccb9c9fbd8942ff72a712540c07) remove the test.
We shouldn't have remove this test. I'm moving this issue as a bug.

**Comment by rgaudin** [comment]
Would be a good opportunity to improve the text in testing that it starts with `text/html`, not that it exactly is `text/html` as this prevents types using optional parameters such as `charset` from being indexed.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#structure_of_a_mime_type

**Comment by rgaudin** [comment]
Cleaned up my workdir and rebuild and indeed, any mimetype gets indexed, as long as the HTML parser is happy.
