### ISSUE TITLE
Queries are not anchored to the beginning of the document in suggestion search

### ISSUE THREAD

**Issue by maneeshpm** [openzim/libzim#510]
Suppose we have the following titles in an index: {`aterm bterm this is a title cterm`, `this is a title aterm bterm cterm`, `aterm this is a title bterm cterm`}

if I perform a suggestion query "this is a title",
The results are in the order:
```
aterm bterm this is a title cterm
aterm this is a title bterm cterm
this is a title aterm bterm cterm
```
Whereas, the expected order is:
```
this is a title aterm bterm cterm
aterm this is a title bterm cterm
aterm bterm this is a title cterm
```

**Comment by kelson42** [comment]
@maneeshpm Here a few quesitons:
* How the solution would looks (principle)?
* Does this solution is recommended by the Xapian team?
* Do we need somehow to have a property somewhere to detect/know if we have an index supporting anchoring?
* How would older library/kiwix deal with new indexes?
* How would new library/kiwix deal with older indexes?

**Comment by maneeshpm** [comment]
A crude idea is to leverage OP_PHRASE capabilities to match the order in a document. We need to somehow match the 0th position of all documents and all queries so that the "window" of the phrase starts from the 0th position. Such a solution must be formed by modifying the search flow so that we can ensure backward compatibility. Upon my conversation with Xapian team, they suggested the following:
- We need a suitable `PostList` subclass internally which returns a simple `PositionList` subclass that returns position 0 with every phrase query. This will be similar to `Query::MatchAll` but with a position list. This will not change anything that is already stored on the disk and does not effect future indexes.
- The best way to do this is to extend by MatchAll itself.

Such a solution works because the changes are made in the search time routine within xapian without changing anything else in libzim. I am yet to investigate the feasibility of such a solution. Will keep this ticket updated.
<details>
<summary>If someone wishes to read the exerpts of the conversation</summary>
<br>
It needs a suitable PostList subclass internally which gives a simple PositionList subclass that just returns position 0 then done when asked for positions <br>
And something similar to Query::MatchAll in the public API,
 It wouldn't need any changes to what's stored on disk <br>
const Query Query::MatchAll((string()));<br>
so it's actually just a term query for the empty term<br>
the empty term is special and is treated as indexing all documents<br>
we could perhaps just extend that so it also occurs at position 0 in all documents - that shouldl make no difference to existing uses, but means it can be used in a positional query<br>
if you look in matcher/localsubmatch.cc at method LocalSubMatch::open_post_list there's currently Assert(!need_positions); in the if (term.empty()) case<br>
so that'd need to be removed, and then you can see it calls open_leaf_post_list on the DB
which is implemented per backend, but e.g for glass see backends/glass/glass_database.cc where you can see it creates a ContiguousAllDocsPostList or GlassAllDocsPostList<br>
probably this can just be done generically by inserting a new parent class for these AllDocsPostList classes above them and below LeafPostList - this new class can then implement read_position_list() and open_position_list() suitably<br>
oh, except they all inherit from LeafPostList except for GlassAllDocsPostList<br>
i guess we could put this in a new parent class for most of them, and also in GlassAllDocsPostList for glass<br>
it's not going to be much code at all
</details>

**Comment by kelson42** [comment]
@maneeshpm So, the Xapian Title index would not look differently?

**Comment by maneeshpm** [comment]
@kelson42 if it is feasible to implement this, then no. Indexing will remain the same. the query will return 0 in the position list of all documents no matter any other term matches or not.

**Comment by kelson42** [comment]
@maneeshpm That would be awesome, then this feature would be beneficial even for older ZIM file.
