### ISSUE TITLE
Does the integrity check the new indexes v0+v1 properly?

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#517]
It probably should I guess, but want to secure this part of the code has been updated properly.

**Comment by mgautierfr** [comment]
Reading code is good : https://github.com/openzim/libzim/blob/master/src/fileimpl.cpp#L626-L660 :)

Or maybe we should define "properly" and you find this test is not enough.

**Comment by kelson42** [comment]
@mgautierfr Thx, no it looks good. As we have introduced the sorting check recently for the "old" title index, just wanted to secure with you that the new location of old/v0 index AND v1 of the indexes are still tested.
