### ISSUE TITLE
Invalid result returned by suggest

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#521]
Testing the latest nightly with pylibzim I got a failing test.

Investigating it, it appears that `suggest()` returns an invalid result when testing `example.zim`.

```py
suggest_str = "Nayriri"
zim.get_estimated_suggestions_results_count(suggest_str)
> 3
list(zim.suggest(suggest_str))
> ['A/Nayriri_Uñstawi', 'A/index']
# there are only 2 results but we know the estimated is *estmated* from xapian so that might differ
zim.get_entry_by_path("A/index")
> KeyError: 'Cannot find entry'
```

So the problem is that `suggest()` returns this `A/index` path which doesn't exist in the ZIM. In the ZIM, there is a `A/Main_Page` which is a redirect to the `A/Nayriri_Uñstawi` but no sign of this `A/index`.

Please note that returning this `A/index` is not new to this nightly. It was there at least a month ago when I wrote the test. I just did not care to test it. What changed is the estimated suggestions result count which bumped from `2` to `3`.

**Comment by kelson42** [comment]
@maneeshpm Would you be able please to have a look to this?

**Comment by maneeshpm** [comment]
@kelson42 Sure, I will look into this. @rgaudin where can I find this zim?

**Comment by rgaudin** [comment]
It's from the libkiwix's test data: https://github.com/kiwix/kiwix-lib/raw/master/test/data/example.zim

**Comment by maneeshpm** [comment]
To recreate the issue, I wrote the following unittest in libzim suggestion tests:
```c++
TEST(Suggestion, matchesEstimated) {
    const zim::Archive archive1("./data/example.zim");
    zim::Search search(archive1);
    search.set_suggestion_mode(true); search.set_query("Nayriri"); search.set_range(0, archive1.getEntryCount());

    int matches_estimate = search.get_matches_estimated();
    ASSERT_EQ(matches_estimate, 2);
    for (auto entry = search.begin(); entry != search.end(); entry++) {
      std::cout<< entry.get_title() << ", " << entry.get_url() << ", " << (*entry).getIndex() <<std::endl;
    }
  }
```
```
output:
nayriri unstawi, A/Nayriri_Uñstawi, 42
nayriri_unstawi, A/index, unknown file: Failure
```
It seems like `zim::Search::get_matches_estimated()` is working fine here, I am getting a result 2 as expected (not actually) since we have 2 entries with a similar name in the xapian index as given by the output. I am not getting a 3 here as mentioned in the ticket so I am unable to recreate this issue with latest libzim master.

As @rgaudin mentioned, we don't have the entry `A/index` with the title `nayriri_unstawi`. But it is present in the xapian index as a xapian document with data `A/index`. It is possible if `TitleXapianHandler::handle(Dirent* dirent, ...)` is called with a "wrong" dirent. This is an index time problem rather than a search time problem. I should rather examine the index routine to see if something is messy there.

**Comment by rgaudin** [comment]
Thanks @maneeshpm, you unveiled a pylibzim bug 👍 

And thank you for investigating this. I suggest we close this and let you figure out whether to open one for the index-creation issue you mentioned?

**Comment by maneeshpm** [comment]
Yes, we can do that. I haven't found anything spooky in the indexer yet that can cause a misread of the path like in this case. It can be an isolated incident as well, but just to be sure I will keep digging.

**Comment by kelson42** [comment]
@mgautierfr Can you please tell us if the zim is buggy? If not how should it look like?

**Comment by mgautierfr** [comment]
> It is possible only if TitleXapianHandler::handle(Dirent* dirent, ...) is called with a "wrong" dirent. This is an index time problem rather than a search time problem. I should rather examine the index routine to see if something is messy there.

`example.zim` is create with a "old" libzim (https://github.com/openzim/libzim/releases/tag/6.3.0 is probably close enough to the code used to create it).

**Comment by maneeshpm** [comment]
It seems like the zim is buggy and should be replaced in lib-kiwix as well. We can close this issue.

**Comment by kelson42** [comment]
See https://github.com/kiwix/kiwix-lib/issues/467 for the ZIM file fix
