### ISSUE TITLE
About article path in fulltext index in new zimfile (searching with old libzim/kiwix-lib)

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#523]
Looking for #519, I've found a compatibility issue when searching in new zim file with old libzim.

In new zim file, when we index article, we are storing the path without the namespace in the database.
It is coherent with the fact that we want to remove(hide) the namespace.
All articles are by definition in `C` namespace, we don't have to specify it (and new libzim will search in `C` namespace).

But old kiwix-lib expect the have a full path (with namespace) and there is not compatibility layer to search in `C` namespace (as it is a old kiwix-lib). So the links in the search page is broken.

The technical solution would be to store the fullpath (with `C` namespace) in the xapian database.
Then, old kiwix-lib would have the namespace and would be happy.
New libzim, with the compatibility layer would be able to open it.

But if we go this way, we would create zimfile which broke the assumption to not have explicit namespace.
We would have to always keep some kind of compatibility layer.

**Comment by kelson42** [comment]
@mgautierfr I'm supportive of this approach

**Comment by kelson42** [comment]
@maneeshpm Would that be something you could/would work on?

**Comment by maneeshpm** [comment]
Yes I can do this. As I understand, there are two parts to fixing this issue
1. We need to index full path with namespace as the data of documents. This can be done in the handler routine.
2. Implement a compatibility layer to take care of namespaces in new libzim. 

@mgautierfr I assume we already have a compatibility layer that helps to read older zims?
