### ISSUE TITLE
Favicon not set properly

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#525]
In many cases, the favicon set using libzim7 is not displayed by a libzim6 kiwix-serve.

The [spec](https://wiki.openzim.org/wiki/Metadata) expects the favicon at `/-/favicon` from the format.
One would thus expect the API (ie. `setFaviconPath(entry_path)`) to do what's necessary for that to happen.

The first issue is that `setFaviconPath` is deceptive. It allows to set any path and will only complain if the path that it received doesn't resolve to an added Entry.

That's the proper behavior but Archive->getFaviconEntry() (**on libzim6**) only works if the Entry's path is either `favicon` or `favicon.png`.

Second issue is that **the path of the entry holding the favicon __must__ be the first one in the zim** for the icon to be working on libzim6 kiwix-serve (probably libkiwix but only tested kiwix-serve).

So if you have two Entries: `home` and `favicon`, this will work as `favicon` is before `home` in path sorting and thus gets included first in ZIM.

If you have instead `assets` and `favicon`, the icon won't show up.

You can try any combination. The only way it works is when the favicon entry path is first into ZIM and thus its path the first alphabetically.

---

here's a python script to test it (not very specific ; had a hard time finding this!)

```py
import pathlib
import urllib.request

import libzim.reader
import libzim.writer


class StaticItem(libzim.writer.Item):
    def __init__(self, **kwargs):
        super().__init__()
        for k, v in kwargs.items():
            setattr(self, k, v)

    def get_path(self) -> str:
        return getattr(self, "path", "")

    def get_title(self) -> str:
        return getattr(self, "title", "")

    def get_mimetype(self) -> str:
        return getattr(self, "mimetype", "")

    def get_contentprovider(self) -> libzim.writer.ContentProvider:
        if getattr(self, "filepath", None):
            return libzim.writer.FileProvider(filepath=self.filepath)
        return libzim.writer.StringProvider(content=getattr(self, "content", ""))


img_data = urllib.request.urlopen(
    "https://www.kiwix.org/wp-content/uploads/kiwix-logo-995x200-1.png"
).read()

fpath = pathlib.Path("jquery.min.js")
with open(fpath, "wb") as fh:
    fh.write(
        urllib.request.urlopen(
            "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
        ).read()
    )


def buildzim(fname, favicon_path, other_path):
    zim_fpath = pathlib.Path(fname)
    main_path = "www"
    with libzim.writer.Creator(zim_fpath).config_indexing(True, "eng") as c:
        c.set_mainpath(main_path)
        c.set_faviconpath(favicon_path)
        c.add_item(
            StaticItem(path=favicon_path, content=img_data, mimetype="image/png")
        )
        c.add_item(StaticItem(path=main_path, content="home", mimetype="text/html"))

        c.add_item(
            StaticItem(
                path=other_path, filepath=fpath, mimetype="text/html", title="zzz"
            )
        )

    zim = libzim.reader.Archive(zim_fpath)
    print(
        f"ZIM {fname=}",
        zim.main_entry,
        zim.favicon_entry,
        zim.favicon_entry.get_item(),
    )
    assert zim.favicon_entry.get_item().path == favicon_path
    for idx in range(0, zim.entry_count):
        print(zim._get_entry_by_id(idx))


if __name__ == "__main__":
    buildzim("test-favicon-ok.zim", "favicon.png", "g")
    buildzim("test-favicon-ok2.zim", "favicon", "g")
    buildzim("test-favicon-bad.zim", "favicon.png", "e")
    buildzim("test-favicon-bad2.zim", "favicon", "e")
    buildzim("test-favicon-bad3.zim", "not-favicon", "z")
```

<img width="762" alt="Screen Shot 2021-03-23 at 16 12 34" src="https://user-images.githubusercontent.com/57929/112179497-a74b2b80-8bf2-11eb-8641-240dceeead4c.png">

**Comment by mgautierfr** [comment]
> The spec expects the favicon at /-/favicon from the format.

I've miss the metadata page in the specs...
I've change this in the zim new format and write it in https://wiki.openzim.org/wiki/Well_known_entries
I don't remember where I write about this (or if we discuss about this in live) but we can keep a extra entry `/-/favicon` for compatibility with old libzim.


> Second issue is that the path of the entry holding the favicon must be the first one in the zim for the icon to be working on libzim6 kiwix-serve (probably libkiwix but only tested kiwix-serve).

I'm surprised about this. We don't expect a specific order. We may have a bug in the redirect resolution a writing time.
Does "bad" zim file work with libzim7 ?

**Comment by rgaudin** [comment]
> > Second issue is that the path of the entry holding the favicon must be the first one in the zim for the icon to be working on libzim6 kiwix-serve (probably libkiwix but only tested kiwix-serve).
> 
> I'm surprised about this. We don't expect a specific order. We may have a bug in the redirect resolution a writing time.
> Does "bad" zim file work with libzim7 ?

kiwix-tools from nightly (libzim7) displays the favicon OK

**Comment by kelson42** [comment]
Related to #527
