### ISSUE TITLE
Adapt functions and variables with new specifications

### ISSUE THREAD

**Issue by maneeshpm** [openzim/libzim#529]
According to the new specifications, we are hiding the namespace from path of the entries. With this change, we are also getting rid of the notion of "url". Many part of the code is up to date with the new scheme, but some modules still use it liberally and might cause confusion. 
eg in dirent.cpp
Some naming changes required are `url -> path` and corresponding changes in the function `getUrl` and `getLongUrl` etc.

Apart from this, functions like `Item::getPath`, `Entry::getPath` returns `getLongUrl` in certain cases when it should actually return only the path(formerly url, without namespace).

Do we need an overall variable cleanup and some function changes to maintain coherence with the new scheme prior to libzim7 release?

**Comment by mgautierfr** [comment]
For libzim7 release, the target is the public API.
So for dirent it is not necessary to change (but it may be nice). The initial plan was to reduce the internal changes and concentrate on the API.
Internal changes could be "transparently" made later.

For `Item::getPath` and `Entry::getPath` it is normal.
The new API has no more explicit namespace in it (there is no argument "namespace" or "ns"). A `Entry` is identified by a "path".
But what this "path" is composed is decided by the zim file itself :
- On new zim file, we hide the namespace (that's the goal).
- On old zim file, we must keep the namespace has we can have two entries `A/foo` and `I/foo`.

If you find some inconsistencies please tell here and we will discuss about them.

**Comment by kelson42** [comment]
@maneeshpm what should we do next with this ticket?

**Comment by maneeshpm** [comment]
@kelson42 I agree with @mgautierfr. The public APIs have been changed already with the new scheme. Internal code can be changed gradually. So we can close this issue since it's not relevant for libzim 7.
