### ISSUE TITLE
Missing Counter metadata

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#532]
Since the libzim-next merge, we've lost the automatic `Counter` metadata creation feature.

@mgautierfr is this a mistake or is there a reason behind this?

https://github.com/openzim/python-libzim/blob/c32525ec762a39224b88e997a7299c3836a70799/libzim/writer.py#L240-L245

**Comment by mgautierfr** [comment]
Fixed by #539.
Now the counter metadata is generated and added automatically by libzim.
