### ISSUE TITLE
writing obsolete compression type 1

### ISSUE THREAD

**Issue by vgbundo** [openzim/libzim#543]
According to the zim file format specification, the four low bits of the first byte of a cluster indicate the compression type, and 0 or 1 indicate an uncompressed cluster.  It further states that 1 is an obsolete value.  Thus 0 should be used for uncompressed clusters.  However, current zim files are being created with the deprecated value of 1.

**Comment by kelson42** [comment]
@vgbundo which zim file exactly?

**Comment by kelson42** [comment]
@veloman-yunkan Are you able to confirm? Fix?

**Comment by vgbundo** [comment]
It appears to be widespread if not universal. A convenient example (because it is a small file) is wikipedia_en_ray_charles_mini_2021-03.zim from download.kiwix.org/zim/wikipedia/. Cluster 2 starts at 0x56872 with 0x01.

April 22, 2021 11:39 AM, "Kelson" ***@***.*** ***@***.******@***.***>)> wrote:
	@vgbundo (https://github.com/vgbundo) which zim file exactly?

**Comment by kelson42** [comment]
@vgbundo Indeed something is wrong here. The spec was wrong (or at least misleading) and we have fixed it, see https://wiki.openzim.org/w/index.php?title=ZIM_file_format&diff=31202&oldid=31192. Let us know if this is still unclear.
