### ISSUE TITLE
[Spec] Clarification for search indices

### ISSUE THREAD

**Issue by vgbundo** [openzim/libzim#548]
Two things are unclear in the Zim file format specification regarding the search indicies.  I would like the specification to be clarified to help ensure compatibility between producers and consumers of Zim files.

1.  Must (or should) all search index items in namespace X be stored in uncompressed clusters?  This seems useful to allow random access to their content, but is not mentioned in the spec.

2. Should redirects to Articles be included in the v1 index, or should this only include actual articles?  I assume that such redirects should be included, to allow all available titles (including variants provided by redirects) of articles to be found by searching this index, but the spec is ambiguous.

**Comment by kelson42** [comment]
>     1. Must (or should) all search index items in namespace X be stored in uncompressed clusters?  This seems useful to allow random access to their content, but is not mentioned in the spec.

Yes, @mgautierfr Do you think we should modify the spec?
 
>     2. Should redirects to Articles be included in the v1 index, or should this only include actual articles?  I assume that such redirects should be included, to allow all available titles (including variants provided by redirects) of articles to be found by searching this index, but the spec is ambiguous.

**Comment by mgautierfr** [comment]
> Must (or should) all search index items in namespace X be stored in uncompressed clusters? This seems useful to allow random access to their content, but is not mentioned in the spec.

It was implies by the mimetype which is "not compressible".
But yes, we MUST store indexes (and listing) in a uncompressed cluster.
I've updated the spec.

> 2. Should redirects to Articles be included in the v1 index, or should this only include actual articles?  [...]

It can be redirect. It is up to the creator to decide. (I've updated the spec also).
