### ISSUE TITLE
Use bytes instead of kbytes to specificy the minChunkSize.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#553]
For I don't know which reason, the minChunkSize is specified in kilobytes. It would be better to have all size expressed in bytes.

I've keep this to avoid a (somehow silent) api break, but as we are breaking the whole api with libzim 7, it is maybe time to change this.

See #551

**Comment by veloman-yunkan** [comment]
I think that the definition of `minClusterSize` must be improved/clarified as well. The current doc message of `Creator::configMinClusterSize()` is something between ambiguous and meaningless: https://github.com/openzim/libzim/blob/223aaf3f1c528f0df27ed9601683b2d3548f7d48/include/zim/writer/creator.h#L76-L85
