### ISSUE TITLE
Limit possible value of minChunkSize.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#554]
We may want to enforce we don't create a cluster bigger than 4Gb (and probably lower) (except when we have no choice (one blob > 4Gb))
A too big size for the cluster is counterproductive :
- For compressed cluster, we would have to uncompress a lot of data to access a blob
- zim-split try to split a zim on "natural" bondaries (ie cluster size). And we want to be able to split a zim file in part < 4Gb (the fat32 limit)

_Originally posted by @mgautierfr in https://github.com/openzim/libzim/issues/552#issuecomment-831787580_

**Comment by mgautierfr** [comment]
Related to #553

**Comment by kelson42** [comment]
I have no strong opinion on this but I would prefer to just leave it like it is. I don't really like the idea that we decide in place of the publisher.

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan If #83 woukd be implemented, we could implement this ina form of a zimcheck warning? What do you think?

**Comment by mgautierfr** [comment]
I don't think that #83 will be implement.

**Comment by kelson42** [comment]
IMO we should better close this ticket and probably #83 as well.

**Comment by mgautierfr** [comment]
I've close #83 as wontfix.
But we don't need it to implement this ticket.
We may decide to not implement a limitation, but the decision is independent of #83.

**Comment by kelson42** [comment]
I'm not in favour of a limitation, not our responsability if someone does something sily in the its ZIM configuration.

**Comment by veloman-yunkan** [comment]
In my opinion, artificially set limitations are useful in the presence of limitations that are beyond our control or are much more difficult to eliminate. When users hit the limitation imposed by us we have more time to understand the reasons and, if it is a valid and justified use case, we can easily lift it and prepare for the likely future growth that may exceed the natural/harder limitation too.

**Comment by veloman-yunkan** [comment]
> I'm not in favour of a limitation, not our responsability if someone does something sily in the its ZIM configuration.

With such a point of view safety devices like circuit breakers, pressure relief valves, speed limiters, etc wouldn't exist. Sometimes fool-proofness is a useful feature.

**Comment by kelson42** [comment]
> > I'm not in favour of a limitation, not our responsability if someone does something sily in the its ZIM configuration.
> 
> With such a point of view safety devices like circuit breakers, pressure relief valves, speed limiters, etc wouldn't exist. Sometimes fool-proofness is a useful feature.

If we would potentially break something, I would be in favour. Not the case here.
