### ISSUE TITLE
search_iterator::get_snippet should use the same Stemmer used in query parser

### ISSUE THREAD

**Issue by maneeshpm** [openzim/libzim#558]
Snippets for searching "chocolate factory":
```
Chocolate <b>factory</b>
Wonka's chocolate <b>factory</b>
Cadbury's chocolate <b>factory</b>
```
The Expected result is:
```
<b>Chocolate</b> <b>factory</b>
Wonka's <b>chocolate</b> <b>factory</b>
Cadbury's <b>chocolate</b> <b>factory</b>
```
This happens because the query parser returns the stemmed matches to the query whereas `search_iterator::get_snippet` generates snippets without stemming.
 
To fix this, snippets must be generated with the same stemmer that was used to parse the initial query inside the query parser.

**Comment by kelson42** [comment]
@maneeshpm might this ticket be related or a duplicate of #86

**Comment by maneeshpm** [comment]
@kelson42 Yes, this seems to be a duplicate of it and might be a solution to that issue. Should we close this one and continue to work on that?
