### ISSUE TITLE
AVIF image format

### ISSUE THREAD

**Issue by JensKorte** [openzim/libzim#565]
At [Briar](https://code.briarproject.org/briar/briar/-/issues/2048) I found this link to <https://jakearchibald.com/2020/avif-has-landed/>. The short conclusion at "AVIF has landed" is: very small file size, quite good quality but encoding takes a lot of time.

**Comment by kelson42** [comment]
@JensKorte libzim can store any kind of content. What is the puropose of this ticket?

**Comment by JensKorte** [comment]
> @JensKorte libzim can store any kind of content. What is the puropose of this ticket?

I thought of AVIF support to get smaller images and ZIM files. Since not all browsers support the use of AVIF, I thought of a converting support in the decompression process of libZIM.

**Comment by kelson42** [comment]
Zim format is content agnostic. Regarding our scrapers, we use format which are widely supported in browsers.

**Comment by kelson42** [comment]
On the top of this, I have still a few concerns regarding patents. See https://avif.io/blog/faq/avif-patents/.
