### ISSUE TITLE
Question: How to choose the optimal cluster size

### ISSUE THREAD

**Issue by IMayBeABitShy** [openzim/libzim#579]
Hi everyone,

I was wondering how I can determine the optimal cluster size when creating a ZIM.
I am currently working on archiving a website containing a large amount of media. Roughly a quarter of all entries will be binary files (more specifically, a specialized variant of ZIP files) usually in the 10 to 20MB range, with some significantly larger.
The current build with only some of the data is already close to 200GiB, the expected final size being one or two TiB. The size isn't a problem, but I'm still interested in reducing it a bit. I've already optimized the input data significantly (and will continue doing so), so I'm looking into optimizing the size by changing the build parameters of the ZIM.

To my understanding, choosing a more fitting (min) cluster size could possible reduce the size of the ZIM somewhat.
According to #573, increasing the default cluster size from 1MiB to 2MiB yields a size reduction of 5%, which is already a great improvement.  I am assuming this is mostly regarding ZIM files more focused on "normal"-sized entries (like wikipedia articles) and I can imagine that it's quite counterproductive to the filesize if the content is on average larger than the min cluster size.

So, how can I find the optimal min cluster size? Or should i not change/configure it at all?

Also, what's the theoretical limit of a ZIM file? According to the wiki, the cluster count is a 4 byte integer, so libzim should be able to create zim files up to a size of `2 ^ (4 * 8) * cluster_size = 4294967296 * cluster_size`, correct?

**Comment by mgautierfr** [comment]
There is no easy answer here.

Cluster are used to regroup content together (and for compressible content, compress them together).
So the more content we compress together, the more the compression ratio will (may) be good.
But at reading we will need to decompress all file "before" the one we want in the cluster, and so we have a lost of performance. (And potentially a reading memory usage as we keep decompressed cluster in cache).

As almost always, this is a trade of between performance and memory usage.
The global idea is that the more you use bigger cluster, the more you will reduce the size (with a asymptote) and the more you will pressure the reader part.
(On uncompressible content, it almost doesn't change anything.)

> Also, what's the theoretical limit of a ZIM file? According to the wiki, the cluster count is a 4 byte integer, so libzim should be able to create zim files up to a size of 2 ^ (4 * 8) * cluster_size = 4294967296 * cluster_size, correct?

The cluster count is indeed unsigned 32 bits, so you can have a maximum of `(2^32) - 1` clusters.
However, each cluster has a different size.
The cluster size setting is a hint given to the creator.
It will create cluster the closer but not bigger (if possible) than the set size.
If single content is bigger than the given size, the cluster will be bigger (no choice) (and it will contain only one content).
The maximum size of a blob is 2^64

---

On thing we could do to improve the compression ratio would be to "regroup" content by type. html will probably be better compressed with other html content than with svg or js.
This could be done "easily" by the creator as the libzim creator regroup the content only base on the order the content are added.
And on the opposite side, for reading performance, we should regroup content by there usage (common style css should be put in the same cluster, articles mostly read together put in the same cluster,...) to avoid decompressing too much clusters.
