### ISSUE TITLE
zim/zim.h:35:10: fatal error: zim/zim_config.h: No such file or directory

### ISSUE THREAD

**Issue by kiicia** [openzim/libzim#583]
I am slowly crawling through installation of python libzim on cygwin with `pip install --upgrade libzim`.

After solving issues connected to required packages and taking hint from https://github.com/openzim/python-libzim/blob/master/setup.py to get headers from this repo and feed them to the process:

`export CFLAGS="-I/cygdrive/c/zim/include/"`

... I seem to hit wall, where file `zim/zim_config.h` is missing and I have no clue how/where to get it

```
  In file included from libzim/wrapper.cpp:648:
  /cygdrive/c/zim/include/zim/zim.h:35:10: fatal error: zim/zim_config.h: No such file or directory
     35 | #include <zim/zim_config.h>
        |          ^~~~~~~~~~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for libzim
```

**Comment by kiicia** [comment]
I was able to compile libzim (with some warnings) on cygwin after editing 4 source files, but it does not solve with python libzim

**Comment by mgautierfr** [comment]
The `zim_config.h` is generated by the build process of libzim.
I must not take the header from the sources but the header installed. (or from a dist archive of libzim)
