### ISSUE TITLE
ZIMs made with newest version of libzim have invalid X/listing/titleOrdered/v1 data

### ISSUE THREAD

**Issue by Jaifroid** [openzim/libzim#590]
As first discussed at https://github.com/kiwix/kiwix-js/issues/708, ZIMs made with the newest version of libzim either have invalid metadata in the file header indicating erroneoulsy that they are v1 ZIMs when in fact they are v0, or else the index at `X/listing/titleOrdered/v1` has an incorrect `dirEntry` header which indicates that the index size is 0. ZIMs which appear to have this invalid format are: 

- 2.5M http://tmp.kiwix.org/beer_meta_stackexchange_com_2021-07__nobase.zim
- 15M http://tmp.kiwix.org/beer_stackexchange_com_2021-07__nobase.zim

Original post about this below:

* Both of these ZIMs have invalid metadata in the ZIM header: the header indicates the archive's `minorVersion` property is 1, and that they therefore should use the new v1 title pointer lists, but `X/listing/titleOrdered/v1` has a size of 0 (or at least its size is declared as zero in the dirEntry metadata), and so it can't be used. The reader has to fall back to using the old v0 title pointer list. See screenshot below for diagnostic. I think this is an issue for @mgautierfr.

![image](https://user-images.githubusercontent.com/4304337/126609832-10fdfdd5-bccc-4c08-814e-aff7af78b96a.png)

**Comment by veloman-yunkan** [comment]
> ..., or else the index at `X/listing/titleOrdered/v1` has an incorrect `dirEntry` header which indicates that the index size is 0

What about `X/listing/titleOrdered/v1` entry being actually empty? This can happen if the creator [doesn't provide](https://github.com/kiwix/libkiwix/issues/588#issuecomment-886057241) correct hints about items being added to the ZIM archive (in this case a front item hint is required).

**Comment by Jaifroid** [comment]
@veloman-yunkan We were indeed asked to account for an empty v1 index, and to fall back gracefully to using the v0 index, which is what happens in this case. However, it is therefore an invalid type 1 (`minorVersion`) ZIM, and what we @ kiwix-js really need is a real-life reference v1 ZIM that we can use for standardized testing purposes.

**Comment by mgautierfr** [comment]
How those file have been generated ?
If it is a stackexchange zim, I assume it is generated throw sotoki which use the python binding.
python-libzim still not support Hints and it is necessary to mark entries as front_article (and put them in `X/listing/titleOrdered/v1`).

What could be done on libzim side, at best, is to avoid create a `X/listing/titleOrdered/v1` if it is empty.
But to really fix the issue, we have to update python-libzim (openzim/python-libzim#115) and update sotoki to pass the correct hints.

**Comment by kelson42** [comment]
@mgautierfr Yes, it was a Sotoki ZIM file, before your fix for the hints.
