### ISSUE TITLE
About workers and delays

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#591]
Apologies if this is obvious but I have difficulties documenting libzim's behavior.

My understanding is that on `startZimCreation`, a pool of `n` (`4` if not otherwise specified) `taskRunner` threads are started. An additional `clusterWriter` thread is also started.

Whenever an Item is added via `addItem`, there are a few stuff done in the main thread then in `addItemData` the _cluster_ is pushed to the two queues that the aforementioned threads are consuming.

`taskRunner` is always attempting to pop a `ClusterTask` from the queue while `clusterWriter` is looking at the first cluster's that has completed the `taskRunner` step to write it to the Zim file.

`taskRunner`'s job is to compress the data if it should be compressed (based on mimetype mostly – I don't use Hints).

---

Based on this description, I am expecting the following scenario to happen:

- I start a Creator
- I add a binary Item
- A taskRunner thread picks it up immediately, understands it's binary and should thus not compress and close it.
- the clusterWriter thread picks it up immediately and write it to the Zim file.

This is not what I observe. What I observe (through printing logs in workers.cpp 😅) is that the taskRunner is indeed triggered immediately but the clusterWriter is not. Only upon `finishZimCreation` is it called and indeed writes the content to zim and releases the Item.

From here, it looks like the cluster is not properly pushed to `clusterToWrite` in `closeCluster()`. I mean the loop in the worker receives `false` on `creatorData->clusterToWrite.getHead(cluster)`.

Can someone explain what is happening? Is it some kind of edge case due to the over simplification of this example (adding a single binary file to the ZIM, no indexing) ?

https://github.com/openzim/libzim/blob/20c0e3019c97f367acb0ba3c86f9dcd04ca44e77/src/writer/workers.cpp#L32-L82

**Comment by rgaudin** [comment]
Forgot to mention that in this example, the Item's content is larger than cluster size (10M vs 4M)

**Comment by kelson42** [comment]
@veloman-yunkan Would you be able to help @rgaudin with his questioning?

**Comment by veloman-yunkan** [comment]
> Forgot to mention that in this example, the Item's content is larger than cluster size (10M vs 4M)

@rgaudin Are you absolutely sure that this is true? The unit assumed for the cluster size in the libzim API was recently changed from kilobytes to bytes (see #553). If you missed it, then your target cluster size may actually be 4G.

**Comment by rgaudin** [comment]
Ah no I didn't known. Let me come back to you

**Comment by rgaudin** [comment]
Thanks @veloman-yunkan, you were right, the cluster wasn't full enough to be written. Doesn't seem really practical to get a single Item written before finishing the Zim so I've added other after and that matched the description.

Given the above description, could you explain how/when does the indexing happens and how that might impact releasing the provided Item?

**Comment by veloman-yunkan** [comment]
@rgaudin

To the best of my understanding indexing should have no impact on the act of releasing an item during ZIM creation. Items should be released when the cluster they have been assigned to is closed. @mgautierfr, as the author of the ZIM writer, can provide more details with less effort.

**Comment by mgautierfr** [comment]
> Whenever an Item is added via addItem, there are a few stuff done in the main thread then in addItemData the cluster is pushed to the two queues that the aforementioned threads are consuming.

No, the cluster is pushed to the two queues when we mark the cluster to be closed, the may happen when we try to add a item to a already full cluster, but not all the time.
We must may for the cluster to be full before writing/compressing it as we need to know all offsets of the data before.
And (what you've missed) a cluster is not closed after we add a content to it, but before we add a new one.
When we have a new content to add, we check if the existing cluster is full or not and if yes, we close the current cluster and open a new one.
As you add only one content, the cluster is closed at the end of the whole process when you call `finishZimCreation` (which close any opened and not empty cluster)

> taskRunner is always attempting to pop a ClusterTask from the queue while clusterWriter is looking at the first cluster's that has completed the taskRunner step to write it to the Zim file.

TaskRunner is always attempting to pop a task.
It may be a `ClusterTask` and the cluster task is to actually close the cluster (compressing it first if needed).
Or it may a `IndexingTask`:
- Take the indexData (this will use the contentProvider and a parse the content if you have not provided your own index data).
- Adding the indexData to xapian database.

> From here, it looks like the cluster is not properly pushed to clusterToWrite in closeCluster(). I mean the loop in the worker receives false on creatorData->clusterToWrite.getHead(cluster)

`closeCluster()` correctly push the cluster to `clusterToWrite`. But it doesn't actually close the cluster.
It add the cluster to the worker task and the cluster will be actually the closed there.


> Given the above description, could you explain how/when does the indexing happens and how that might impact releasing the provided Item?

When you add a item :
- A `contentProvider` is created using `getContentProvider()`. The contentProvider is be pass to the cluster/worker and used there.
- A `indexData` is created using `getIndexData()` (The default implementation create another contentProvider and keep it for later use). The indexData is pass to the worker and used there.
- The creator release the item (drop its reference). So, the item is "released" from the creator pov. Of course, the created contentProvider/indexData may keep a reference to the item if needed. In this case, the item is not released.

On python side, the contentProvider do not keep a reference to the item, so the item should be released.

**Comment by rgaudin** [comment]
Thanks 🙏

**Comment by kelson42** [comment]
> And (what you've missed) a cluster is not closed after we add a content to it, but before we add a new one.

There might be a really good reason for that, but at a first look this seems:
* Counter intuitive
* Leads to additional memory consumption (longer in memory)
* Leads to slow downs because things which could be done immediatly, should be done immediatly.

**Comment by mgautierfr** [comment]
We don't know if a cluster is full before we try to add a new content.
If we have a requested cluster size of 1024 and the current cluster size is 1000, then the cluster will be close or not at 1000 depending of the new content:
- If it is less than 24 (let's say 10), we add the content to the cluster, new size is 1010 and we have 14 space left.
- If it is more, we close the cluster with a size of 1000 and open a new one.

**Comment by kelson42** [comment]
@mgautierfr Thx for the clarification, but in this example, we know, because the one item is already a lot larger than the cluster size?!

**Comment by mgautierfr** [comment]
Yes, but it is somehow a exceptional case. Keep the cluster open to close it the next time doesn't change a lot of thing and it simplify a lot the code.

> Counter intuitive

Once you know what is the problem, this is not counter intuitive.

> Leads to additional memory consumption (longer in memory)

It would be additional memory if we keep the cluster in memory while we are creating a new one. But we are always closing cluster before opening a new one.

> Leads to slow downs because things which could be done immediatly, should be done immediatly.

"Closing" the cluster is almost instantaneous. We do not really close it but push it to the workers.
The workers do the real job (that could be long), not the main thread.
But from the log we have, the task queue is almost always full and worker all always working fully. Pushing a new task a millisecond before will not improve speed.
