### ISSUE TITLE
In `SearchResultSet::getResults(int start, int end)` end is max result count 

### ISSUE THREAD

**Issue by maneeshpm** [openzim/libzim#596]
In `Xapian::Enquire::get_mset(arg1, arg2..)`, arg1 is the begin offset or the `start`. And arg2 is max result count, but we have been wrongfully using it as `end`.
ie, `searchResultSet.getResult(10, 10)` does not return results in the range (10, 10) or no result. Rather, it returns results in the range (10, 20), ie 10 results from an offset of 10. 

The documentation needs to be fixed.

**Comment by kelson42** [comment]
@maneeshpm Hopefully, easy to fix.
