### ISSUE TITLE
libzim does not compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#6]
```
$ meson . build
The Meson build system
Version: 0.29.0
Source dir: /home/kelson/libzim
Build dir: /home/kelson/libzim/build
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: libzim
Native c compiler: cc (gcc 5.4.0-6ubuntu1)
Native cpp compiler: c++ (gcc 5.4.0-6ubuntu1)
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency zlib found: YES 1.2.8
Native dependency liblzma found: YES 5.1.0alpha
Dependency bzip2 found: NO
Native dependency xapian-core found: YES 1.4.2
Native dependency icu-i18n found: YES 55.1
Build targets in project: 2

```

**Comment by kelson42** [comment]
I suspect the problem come from the lack of .pc file for bz2, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853803

**Comment by kelson42** [comment]
Maybe the solution is #9

**Comment by mgautierfr** [comment]
I see no problem here, You've just ran the equivalent of `./configure`, so no compilation is done.

You need to 
```
cd build
ninja
```
To compile libzim.
(And it will compile libzim without bzip2 support indeed)

**Comment by kelson42** [comment]
Indeed... I just saw bzip2 in red... and assumed something went wrong. Sorry for the wrong alarm.

**Comment by chinmayapancholi13** [comment]
@mgautierfr @kelson42 I have been trying to install Libzim and run C++ code to read a `.zim` file. For installation, I have followed the following steps : 
-  Installed meson using `pip3 install meson` and then `hash -r`.
- Execute the steps for Ninja i.e.
   - git clone git://github.com/ninja-build/ninja.git
    - cd ninja
    - git checkout release
    - ./configure.py --bootstrap
    - mkdir ../bin
    - cp ninja ../bin
    - cd .. 
- Downloaded the libzim source code using `git clone` and in the root directory of the downloaded libzim repo, I do :
   - mkdir build
   - meson . build
   - cd build
   - ninja
- To install libzim, run `ninja install`

After these steps, I can see `libzim` listed in `pkg-config --list-all`. However, when I try to compile the following C++ code using `g++ -o zimlist -lzim zimlist.cpp` : 
```
#include <zim/file.h>
#include <zim/fileiterator.h>
#include <iostream>
int main(int argc, char* argv[]) 
{
  try
  {
    zim::File f("wikipedia.zim");
  
    for (zim::File::const_iterator it = f.begin(); it != f.end(); ++it)
    {
      std::cout << "url: " << it->getUrl() << " title: " << it->getTitle() << '\n';
    }
  }
  catch (const std::exception& e)
  {
    std::cerr << e.what() << std::endl;
  }
}
```

I get a lot of `undefined reference to ... ` errors like `undefined reference to zim::File::begin() const'`.

I have Ubuntu 16.04 installed on my machine, in case this is useful info.

**Comment by kelson42** [comment]
@chinmayapancholi13 

Where is libzim.so installed (path)?

**Comment by chinmayapancholi13** [comment]
@kelson42 libzim.so is present in the folder `/usr/local/lib/x86_64-linux-gnu/`.

**Comment by kelson42** [comment]
@chinmayapancholi13 

We all have here the same problem. This sounds to be a bug in Meson (the build system). Please subscribe this ticket to push the solution https://github.com/mesonbuild/meson/issues/1972

As a workaround, I use to move them back to /usr/loca/lib

`sudo mv /usr/local/lib/x86_64-linux-gnu/libzim* /usr/local/lib/ && sudo mv /usr/local/lib/x86_64-linux-gnu/pkgconfig/libzim.pc /usr/local/lib/pkgconfig/libzim.pc`

Do not forget to run "sudo ldconfig" again before running the compilation.

**Comment by chinmayapancholi13** [comment]
@kelson42 After moving libzim files to `/usr/local/lib` using the command you shared above and then executing `sudo ldconfig`, I am still getting the same 'undefined reference to  ..... ' errors on running `g++ -o zimlist -L/usr/local/lib/ zimlist.cpp` on trying to compile. :(

**Comment by kelson42** [comment]
@chinmayapancholi13 

`g++ zimlist.cpp -o zimlist --std=c++11 -lzim`

**Comment by chinmayapancholi13** [comment]
@kelson42 Great! Worked like a charm. I had been stuck at this for a long time. Thanks a ton for your help! :+1:

**Comment by kelson42** [comment]
`g++ zimlist.cpp -o zimlist -lzim` Should also work if your g++ version is recent. Out of curiosity, what do you try to obtain?

**Comment by chinmayapancholi13** [comment]
I was trying to read some wikipedia `.zim` files. You can find them here: http://wiki.kiwix.org/wiki/Content_in_all_languages.
