### ISSUE TITLE
Memory leak in libzim creator using StringItem.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#618]
There is a reference loop in libzim when using `StringItem`.

`Item::getIndexData()` store a shared_ptr to the `DefaultIndexData` to avoid libzim to create two `DefaultIndexData`.
The `DefaultIndexData` uses (and stores) a `ContentProvider`.
But the ContentProvider for a `StringItem` is a `SharedStringContentProvider` which share ownership to the item's content with the item itself.

The `StringItem` store a shared_ptr, which stores ... which, at the end, increment the ref count of the item itself.
So refcount never drop to 0 and the item is never freed.

---

While this bug as been found investigating https://github.com/openzim/python-libzim/issues/117, it does NOT fix it as we don't use StringItem in the python wrapper.

**Comment by kelson42** [comment]
@mgautierfr what kind of impact does it have? Is this a big or a small memory leak?

**Comment by mgautierfr** [comment]
Pretty big as we leak the `Item`, the `DefaultIndexData` and the `ContentProvider` associated (so all the content of the item).

We don't use `StringItem` in python-libzim.
But we use it in zimwriterfs for html and css content.

**Comment by mgautierfr** [comment]
python-libzim doesn't use `StringItem` but zimscraperlib stores a reference to the item in the Provider as does the `StringItem` (https://github.com/openzim/python-scraperlib/blob/master/src/zimscraperlib/zim/providers.py#L34-L37)

@rgaudin is already working on this.

**Comment by rgaudin** [comment]
Tried to setup a quick test that would show the leak by using just scraperlib but I'm not seeing increasing RAM usage. Will take another look at it later this week.
