### ISSUE TITLE
What is stored for empty titles?

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#629]
The [spec](https://wiki.openzim.org/wiki/ZIM_file_format#Content_Entry) says that what is stored for Entry (content or redirect) titles is 

> string with an title as refered in the Title pointer list or empty; in case it is empty, the URL is used as title.

As this is the documentation of the *Directory Entries*, it is not clear what exactly happens when setting `title=""` on an Entry:

- Is the URL (path) duplicated and stored as title ?
- Is an empty string stored and the libzim returns URL when being queried for the title?

I'd like to know as there are many cases where title doesn't make sense so I am using an empty title. But if it is stored as a copy of the URL, it might make more sense to use a different placeholder ; especially since we now have FRONT_ARTICLE Hint and don't need to tweak the Title to toggle search inclusion.

**Comment by mgautierfr** [comment]
If the title is empty we are storing an empty string (a simple `\0`).
Even more, if the title is equal to the url, we are also storing an empty string (as the reader part will return the url).

(This also means you cannot have a true empty title. You have a title or a title equal to the url)

**Comment by rgaudin** [comment]
Thanks ; that's clear now.

If there is such a strong assumption on the title being the URL in case it was set empty, shouldn't `getEntryByTitle()` work when passing the URL? At the moment, it doesn't.

**Comment by mgautierfr** [comment]
`getEntryByTitle` search on front articles only if a v1 listing exists.
If you don't set any front articles, the creator doesn't generate a v1 listing and `getEntryByTitle` should work with url (for entry without title).

**Comment by rgaudin** [comment]
Ah OK, I need to update pylibzim dosctring to specify this.

I was testing on [example.zim](https://github.com/kiwix/kiwix-lib/raw/master/test/data/example.zim) which is no-ns but has the v1 title list

```
Entry(url=listing/titleOrdered/v0, title=listing/titleOrdered/v0)
Entry(url=listing/titleOrdered/v1, title=listing/titleOrdered/v1)
```
