### ISSUE TITLE
kiwix-build fails:    2/26 cluster  FAIL  

### ISSUE THREAD

**Issue by lizfrank** [openzim/libzim#631]
OS: ubuntu 18, x86_64
Cloned today, 10-6-21:
git log output:
commit c3a0a27361bf634df8df100ef3b1c71e190ea6b8 (HEAD -> master, origin/master, origin/HEAD)
Merge: a95106b 2301647
Author: Matthieu Gautier <mgautier@kymeria.fr>
Date:   Wed Oct 6 10:17:19 2021 +0200

    Merge pull request #496 from kiwix/specify_signtool_algorithm

This is the tail end of the build:

[----------] Global test environment tear-down
[==========] 17 tests from 1 test case ran. (3411 ms total)
[  PASSED  ] 17 tests.
 1/26 lrucache                                OK       0.03 s 
 2/26 cluster                                 FAIL    44.49 s (exit 
status 1)
 3/26 creator                                 OK       0.65 s 
 4/26 dirent                                  OK       0.02 s 
 5/26 header                                  OK       0.02 s 
 6/26 uuid                                    OK       1.03 s 
 7/26 template                                OK       0.03 s 
 8/26 archive                                 OK       4.23 s 
 9/26 iterator                                OK       0.12 s 
10/26 reader                                  OK       0.04 s 
11/26 find                                    OK       0.07 s 
12/26 compression                             OK       5.81 s 
13/26 dirent_lookup                           OK       0.02 s 
14/26 istreamreader                           OK       0.02 s 
15/26 decoderstreamreader                     OK       1.38 s 
16/26 rawstreamreader                         OK       0.02 s 
17/26 bufferstreamer                          OK       0.01 s 
18/26 parseLongPath                           OK       0.01 s 
19/26 random                                  OK       0.12 s 
20/26 tooltesting                             OK       0.01 s 
21/26 tinyString                              OK       0.02 s 
22/26 suggestion_iterator                     OK       1.38 s 
23/26 search                                  OK       1.38 s 
24/26 defaultIndexdata                        OK       0.08 s 
25/26 search_iterator                         OK       0.93 s 
26/26 suggestion                              OK       3.49 s 

Ok:                   25
Expected Fail:         0
Fail:                  1
Unexpected Pass:       0
Skipped:               0
Timeout:               0

WARNING: qmake command not found.

Stopping build due to errors

I can provide more of the output if needed.

**Comment by kelson42** [comment]
@lizfrank ses, please provide the command and the full log.
