### ISSUE TITLE
Add a getMetadataEntry() endpoint

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#635]
Current API only offers two ways around ZIM metadata:

- `getMetadataKeys()` which returns a list like `["Name", "Title", "Illustration_48x48@1", "Description"]`
- `getMetadata("Name")` which returns the *content* of the metadata Item.

There is no way [^1] to retrieve the metadata Entry, and thus the mimetype of a given metadata which leads to code [like this in libkiwix](https://github.com/kiwix/libkiwix/blob/e46b0c07b5cae683c696ef1de25d12abef725519/src/server/internalServer.cpp).

Another `getMetadataEntry()` (or Item) endpoint would do no harm and fix this.

[^1]: It's possible to loop over all Entries by Id using `getAllEntryCount()` but that would be very inefficient.

**Comment by mgautierfr** [comment]
As we must not have redirection in metadata we can directly have a `getMetadataItem()` (even if the method itself should be prepared to have redirection)
