### ISSUE TITLE
Add built-in compatibility with emscripten compilation

### ISSUE THREAD

**Issue by mossroy** [openzim/libzim#643]
We are currently able to compile libzim with emscripten, but it needs a small patch on debug.h : https://github.com/mossroy/libzim_wasm/blob/master/patch_libzim_for_emscripten.patch

It would be better to handle the case of emscripten compilation in this file, so that libzim could be compiled without any patch

**Comment by kelson42** [comment]
@mossroy What could be done here? anyway to detect the emscripten compilator with a #if ?

**Comment by mossroy** [comment]
Probably : https://emscripten.org/docs/compiling/Building-Projects.html#detecting-emscripten-in-preprocessor

**Comment by kelson42** [comment]
@mossroy :) Looks like we came to the same conclusion. Will male a PR.

**Comment by mossroy** [comment]
I confirm it's now possible to compile libzim with emscripten without the need to patch it.
I just did it with libzim 7.2.2
Thanks!
