### ISSUE TITLE
Is zim::Archive thread safe? 

### ISSUE THREAD

**Issue by automactic** [openzim/libzim#673]
It seems like one of the biggest change in the new version of libzim & libkiwix is the deprecation of `kiwix::Reader` and `kiwix::Searcher`, in favor of `zim::Archive` and `zim::Searcher` instead.

I currently create one instance of `kiwix::Reader` per zim file and use it through out the lifetime of the app. There are many opportunity where a `kiwix::Reader` instance might be used in a multi threaded environment:

- respond to the web view's data loading request
- generate snippet of article content for each search results

If the plan is to switch to `zim::Archive`, can the same instance be safely used across different threads? Given a zim file, is it recommended to create an instance lasting through out the lifetime of the app, or should I initialize the `Archive` and immediately destroy it after use?

**Comment by mgautierfr** [comment]
`zim::Archive` is thread safe, you can use a archive from different thread.
All search operations (`zim::Searcher`, `zim::Search`, `zim::SuggestionSearcher`, ...) are not. But they do not have any global states, so you can create a `zim::Searcher` by thread if you want to.

> Given a zim file, is it recommended to create an instance lasting through out the lifetime of the app, or should I initialize the Archive and immediately destroy it after use?

It is probably better to have one `Archive` lasting through out the lifetime of the app (or at least for all the readingS of the zim). `zim::Archive` create a internal cache, it is better to create it only once.

**Comment by kelson42** [comment]
@mgautierfr Could you please put an entry in the READMe explaining what is thread safe and what is not?

**Comment by automactic** [comment]
@mgautierfr Thanks

**Comment by kelson42** [comment]
@mgautierfr Or if this is complex, update the places in the code documentation where this is needed.
