### ISSUE TITLE
Should creator.addMetadata mimetype have a default value?

### ISSUE THREAD

**Issue by kelvinhammond** [openzim/libzim#676]
https://github.com/openzim/libzim/blob/master/include/zim/writer/creator.h#L147

Should this be
```
void addMetadata(const std::string& name, std::unique_ptr<ContentProvider> provider, const std::string& mimetype = "text/plain;charset=utf-8");
```

That or use something like std::optional or a pointer.

**Comment by kelson42** [comment]
@mgautierfr Woukd you be able please to help @kelvinhammond ?

**Comment by mgautierfr** [comment]
I don't see why we shouldn't have a default value.
We have one for other `addMetadata`, we should have one here also.

@kelvinhammond can you do a PR for this ?

**Comment by kelvinhammond** [comment]
@mgautierfr https://github.com/openzim/libzim/pull/678
