### ISSUE TITLE
Item.getIndexData default implementation calls ContentProvider.feed on main thread

### ISSUE THREAD

**Issue by kelvinhammond** [openzim/libzim#683]
The `Item.getIndexData` method states that the default implementation will call the `ContentProvider.feed` in a thread other than the main thread but this does not actually happen.

Code:
https://github.com/openzim/libzim/blob/master/include/zim/writer/item.h#L133

I've worked around this by tracking which thread created the contentProvider (which **should** always be the main thread) and handling situations where the current thread is not that thread.

**Comment by mgautierfr** [comment]
It is indeed a bug. We should not call `ContentProvider.feed` in the main thread. It is fixed with #684 
Thanks for the report.

> I've worked around this by tracking which thread created the contentProvider (which should always be the main thread) and handling situations where the current thread is not that thread.

Just to be clear, the `ContentProvider` (a call to `zim::writer::Item::getContentProvider()`) is still created in the main thread. What is moved in the worker thread is the calls to `ContentProvider.feed`.

**Comment by mgautierfr** [comment]
In theory, at least performance impact (has we retrieve the content and parse it in the main thread) and dependently of how user of libzim are constructed maybe some kind of race condition/dead lock.

In practice, not a lot:
- Creator should be prepared to see `ContentProvider.feed` from another thread. If it is call from the main thread it should not be a problem. We could potentially have a mutex acquired twice and so a dead lock but we should have seen it before.
- On python wrapper, we already have a GIL (no choice), so the move to another thread do not help here.
