### ISSUE TITLE
Illustration URL does not match zim file format specification

### ISSUE THREAD

**Issue by vgbundo** [openzim/libzim#686]
Libzim appears to be using the url M/Illustration_\<width>x\<height>@\<scale> for illustrations as described in the May 26, 2021 comment to Pull Request 540.  This does not match the Metadata page of the zim file format specification at https://wiki.openzim.org/wiki/Metadata.

**Comment by kelson42** [comment]
@vgbundo Which part of the wiki page is not coherent exactly with the code?

**Comment by vgbundo** [comment]
The specification lists the url for for illustration as "Illustration_[height]x[width]" with no mention of the ***@***.***" part. Leaving the ***@***.***" part off the url causes zimcheck to report a failure.

April 12, 2022 11:49 AM, "Kelson" ***@***.*** ***@***.******@***.***>)> wrote:
	@vgbundo (https://github.com/vgbundo) Which part of the wiki page is not coherent exactly with the code?

**Comment by kelson42** [comment]
@kelson42 Could you please update the spec with the part about the screen pixel depth?

**Comment by vgbundo** [comment]
All I know about this is the reference I found to it in mgautierfr's comment on may 26, 2021 to pull request 540 when trying to figure out why zimcheck was failing my zim files (that were created as described by the specification). Based on this, I've found that calling my favicon ***@***.*** fixes this. 

However, I don't claim to have a clear understanding of what else can/should be done with this pattern or whether the specification should recommend that additional Illustrations be provided. Thus, someone who better understands the logic behind the decision to make this change would be more qualified to decide what the spec should say on this topic.

April 12, 2022 12:14 PM, "Kelson" ***@***.*** ***@***.******@***.***>)> wrote:
	@kelson42 (https://github.com/kelson42) Could you please update the spec with the part about the screen pixel depth?

**Comment by mgautierfr** [comment]
Spec is updated, see https://wiki.openzim.org/wiki/Metadata#Key 
The correct format is indeed `M/Illustration_<width>x<height>@<scale>`.
I have also added few more information about the meaning of `scale`.

Thank @vgbundo.
