### ISSUE TITLE
Dirent pointer table outside ZIM

### ISSUE THREAD

**Issue by rgaudin** [openzim/libzim#712]
This is most likely not a libzim bug but zimit-produced ZIM [der-postillon.com_fr_all_2022-06.zim](http://tmp.kiwix.org/ci/old-dev/der-postillon.com_fr_all_2022-06.zim) (124GB) cannot be read, raising

```
Dirent pointer table outside (or not fully inside) ZIM file
```

I disabled the [recipe](https://farm.openzim.org/pipeline/9910688ead8d37d3e0dbab26) until we find out what's going on.

**Comment by mgautierfr** [comment]
What is the exact size of the file ? According to the header, it should be `132967311955` bytes

**Comment by mgautierfr** [comment]
Have you done the check yourself or in an automated workflow ?
zim file is still downloading on my side but looking the header it should be ok. The "only" potential "rational" way to have this check failing is that the detected size of the file (which may not be the actual size of the file because of some bug) is smaller that it should be.

**Comment by rgaudin** [comment]
It was unattended. The script that reads metadata from ZIM files to build the (dev-)library raised this error.
Manually testing it now, I can't reproduce.

It's not a during-upload issue as ZIMs are uploaded elsewhere (same filesystem) and then moved once done uploading.
I doubt it happened *while file was being moved* as I believe this is an atomic index operation and also the script failed at least twice (meaning the container was started, script was launched, failed and restarted). This would account for multiple seconds.

**Comment by mgautierfr** [comment]
> I believe this is an atomic index operation

It is indeed a atomic operation if the move is made on the same fs. If it is between to different fs, the data has to be copied and it is not atomic (but you should have seen it)

> meaning the container was started, script was launched, failed and restarted).

Would it be possible that the script is started a bit to soon in regard of mounting the fs in the container ?
