### ISSUE TITLE
Stop allowing to create ZIM file using LZMA

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#714]
ZSTD works fine and is better than LZMA. Ultimatively we should remove support of LZMA to simplify the build/code and because there is fundamentally no reason to keep. The longer we or someone creates ZIM files using LZMA, the longer we will have to postpone the decision to fully remove the support LZMA in reading. Therefore we should IMO remove the LZMA support in writing (so in the creator) ASAP.

**Comment by kelson42** [comment]
@veloman-yunkan Any chance you could quickly implement this?

**Comment by veloman-yunkan** [comment]
@kelson42 Yes. Will do.
