### ISSUE TITLE
vcpkg package support

### ISSUE THREAD

**Issue by xiaoyifang** [openzim/libzim#741]
vcpkg is a crossplatform package management tool just like ,dnf ,apt ,pacman etc.

I noticed the openzim is using meson build chain to compile the project.

vcpkg has offered a method to build package based on meson.
https://vcpkg.io/en/docs/maintainers/vcpkg_configure_meson.html

Can the project offered a vcpkg package ?

**Comment by kelson42** [comment]
I have no opinion on this. To me there is for now not a strong need. But if someone wants to work on it and offer some effort to maintain it, then I have nothing against.

**Comment by xiaoyifang** [comment]
https://github.com/microsoft/vcpkg/pull/30758

**Comment by xiaoyifang** [comment]
Now there is an error ,  
```
Run-time dependency xapian-core found: NO (tried pkgconfig and cmake)

..\src\b60b9ad508-e0004f3ac3.clean\meson.build:49:4: ERROR: Dependency "xapian-core" not found, tried pkgconfig and cmake
```

seems the same as https://github.com/openzim/libzim/issues/320  ,
how to ignore xapian-core

**Comment by xiaoyifang** [comment]
I think I fingured out the above issue
```
meson -Dwith_xapian=false
```

**Comment by kelson42** [comment]
@xiaoyifang To fully benefit of the ZiM files we produce, you will need Xapian.

**Comment by xiaoyifang** [comment]
ok I'll try to add that.  but xapian seems can not work on Windows with debug mode.  I have not found out the reason.

**Comment by xiaoyifang** [comment]
another error throw by meson(vcpkg)
```
LINK : fatal error LNK1181: cannot open input file 'src\zim.lib'
```

**Comment by xiaoyifang** [comment]
Is libzim a headonly library?

**Comment by xiaoyifang** [comment]
> another error throw by meson(vcpkg)
> 
> ```
> LINK : fatal error LNK1181: cannot open input file 'src\zim.lib'
> ```
> 
> ```
> [34/35] "C:/VS2022/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x86/link.exe"  /MACHINE:x86 /OUT:src/zim-8.dll src/zim-8.dll.p/archive.cpp.obj src/zim-8.dll.p/cluster.cpp.obj src/zim-8.dll.p/buffer_reader.cpp.obj src/zim-8.dll.p/dirent.cpp.obj src/zim-8.dll.p/dirent_accessor.cpp.obj src/zim-8.dll.p/entry.cpp.obj src/zim-8.dll.p/envvalue.cpp.obj src/zim-8.dll.p/fileheader.cpp.obj src/zim-8.dll.p/fileimpl.cpp.obj src/zim-8.dll.p/file_compound.cpp.obj src/zim-8.dll.p/file_reader.cpp.obj src/zim-8.dll.p/item.cpp.obj src/zim-8.dll.p/blob.cpp.obj src/zim-8.dll.p/buffer.cpp.obj src/zim-8.dll.p/md5.c.obj src/zim-8.dll.p/template.cpp.obj src/zim-8.dll.p/uuid.cpp.obj src/zim-8.dll.p/tools.cpp.obj src/zim-8.dll.p/compression.cpp.obj src/zim-8.dll.p/istreamreader.cpp.obj src/zim-8.dll.p/writer_contentProvider.cpp.obj src/zim-8.dll.p/writer_creator.cpp.obj src/zim-8.dll.p/writer_item.cpp.obj src/zim-8.dll.p/writer_cluster.cpp.obj src/zim-8.dll.p/writer_dirent.cpp.obj src/zim-8.dll.p/writer_workers.cpp.obj src/zim-8.dll.p/writer_clusterWorker.cpp.obj src/zim-8.dll.p/writer_titleListingHandler.cpp.obj src/zim-8.dll.p/writer_counterHandler.cpp.obj src/zim-8.dll.p/suggestion.cpp.obj src/zim-8.dll.p/suggestion_iterator.cpp.obj src/zim-8.dll.p/version.cpp.obj src/zim-8.dll.p/fs_windows.cpp.obj "-INCREMENTAL" "/nologo" "/release" "/nologo" "/DLL" "/IMPLIB:src\zim.lib" "-machine:X86" "-nologo" "-debug" "/LIBPATH:G:/vcpkg/installed/x86-windows/debug/lib" "Rpcrt4.lib" "Ws2_32.lib" "winmm.lib" "icuuc.lib" "icuin.lib" "G:/vcpkg/installed/x86-windows/debug/lib/lzma.lib" "G:/vcpkg/installed/x86-windows/debug/lib/zstd.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.libInstalling src\zim-8.dll to G:/vcpkg/packages/libzim_x86-windows/debug\bin
> 
> ERROR: File 'src\\zim.lib' could not be found
> " "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
> ```
> 
> I think I should pass some options to meson, the default option in windows do not success. (good news is that the other platform all success.)

I managed to build success on Windows by changing `install: true` to `install: false` in src\meson.build file.
I have no idea if it will has some subsequences.

**Comment by mgautierfr** [comment]
This is probably the issue : https://github.com/mesonbuild/meson/issues/7838

We miss a proper export of our public function in libzim.

**Comment by kelson42** [comment]
> We miss a proper export of our public function in libzim.

Do we have s ticket for that?

**Comment by kelson42** [comment]
> This is somehow hidden in the whole "compile on windows" task. (ie, no specific issue opened about that)

OK, so this ticket depends on https://github.com/kiwix/kiwix-build/issues/466

**Comment by xiaoyifang** [comment]
> > This is somehow hidden in the whole "compile on windows" task. (ie, no specific issue opened about that)
> 
> OK, so this ticket depends on [kiwix/kiwix-build#466](https://github.com/kiwix/kiwix-build/issues/466)

That issue has not been processed in two years. !! 
any plan date for this?

**Comment by kelson42** [comment]
We are on it

**Comment by xiaoyifang** [comment]
> another error throw by meson(vcpkg)
> 
> ```
> LINK : fatal error LNK1181: cannot open input file 'src\zim.lib'
> ```
> 
> ```
> [34/35] "C:/VS2022/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x86/link.exe"  /MACHINE:x86 /OUT:src/zim-8.dll src/zim-8.dll.p/archive.cpp.obj src/zim-8.dll.p/cluster.cpp.obj src/zim-8.dll.p/buffer_reader.cpp.obj src/zim-8.dll.p/dirent.cpp.obj src/zim-8.dll.p/dirent_accessor.cpp.obj src/zim-8.dll.p/entry.cpp.obj src/zim-8.dll.p/envvalue.cpp.obj src/zim-8.dll.p/fileheader.cpp.obj src/zim-8.dll.p/fileimpl.cpp.obj src/zim-8.dll.p/file_compound.cpp.obj src/zim-8.dll.p/file_reader.cpp.obj src/zim-8.dll.p/item.cpp.obj src/zim-8.dll.p/blob.cpp.obj src/zim-8.dll.p/buffer.cpp.obj src/zim-8.dll.p/md5.c.obj src/zim-8.dll.p/template.cpp.obj src/zim-8.dll.p/uuid.cpp.obj src/zim-8.dll.p/tools.cpp.obj src/zim-8.dll.p/compression.cpp.obj src/zim-8.dll.p/istreamreader.cpp.obj src/zim-8.dll.p/writer_contentProvider.cpp.obj src/zim-8.dll.p/writer_creator.cpp.obj src/zim-8.dll.p/writer_item.cpp.obj src/zim-8.dll.p/writer_cluster.cpp.obj src/zim-8.dll.p/writer_dirent.cpp.obj src/zim-8.dll.p/writer_workers.cpp.obj src/zim-8.dll.p/writer_clusterWorker.cpp.obj src/zim-8.dll.p/writer_titleListingHandler.cpp.obj src/zim-8.dll.p/writer_counterHandler.cpp.obj src/zim-8.dll.p/suggestion.cpp.obj src/zim-8.dll.p/suggestion_iterator.cpp.obj src/zim-8.dll.p/version.cpp.obj src/zim-8.dll.p/fs_windows.cpp.obj "-INCREMENTAL" "/nologo" "/release" "/nologo" "/DLL" "/IMPLIB:src\zim.lib" "-machine:X86" "-nologo" "-debug" "/LIBPATH:G:/vcpkg/installed/x86-windows/debug/lib" "Rpcrt4.lib" "Ws2_32.lib" "winmm.lib" "icuuc.lib" "icuin.lib" "G:/vcpkg/installed/x86-windows/debug/lib/lzma.lib" "G:/vcpkg/installed/x86-windows/debug/lib/zstd.lib" "kernel32.lib" "user32.lib" "gdi32.lib" "winspool.lib" "shell32.lib" "ole32.libInstalling src\zim-8.dll to G:/vcpkg/packages/libzim_x86-windows/debug\bin
> 
> ERROR: File 'src\\zim.lib' could not be found
> " "oleaut32.lib" "uuid.lib" "comdlg32.lib" "advapi32.lib"
> ```
> 
> I think I should pass some options to meson, the default option in windows do not success. (good news is that the other platform all success.)

I still got this error after the commit of https://github.com/openzim/libzim/pull/783 .
I remembered I have successed,now I'm confused.

**Comment by xiaoyifang** [comment]
https://github.com/microsoft/vcpkg/pull/30758

vcpkg libzim is been merged .

```
vcpkg install libzim
```
install libzim without xapian support
```
vcpkg install lizim[xapian]
```
install libzim with xapian support

NOTE: as vcpkg xapian library has some restriction on Windows.  on Window only libzim release package is supported right now(handled in https://github.com/microsoft/vcpkg/pull/31338)
on Windows 
```
vcpkg install libzim[xapian]:x64-windows-release --allow-unsupported
```

**Comment by xiaoyifang** [comment]
This has been supported , so I just close this.

**Comment by kelson42** [comment]
@xiaoyifang So I guess all good now with the source code considering Windows compilation and usage of the `libzim.dll`?

**Comment by xiaoyifang** [comment]
So far ,It can work on my case.
