### ISSUE TITLE
Multiple .so file on linux tar file on nightly

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [openzim/libzim#752]
We have found two .so file on nightly upload for linux architecture on https://download.openzim.org/nightly/libzim_linux-x86_64.tar.gz. Shared library was showing as 0mb while other with release number were working.
![Screenshot from 2022-12-06 17-35-27](https://user-images.githubusercontent.com/34593983/205907728-4d4795b4-189f-41ef-927f-266df175a579.png)

**Comment by kelson42** [comment]
This is not a bug, the two 0B files are symbolic links.
