### ISSUE TITLE
gtest C++14 requirement

### ISSUE THREAD

**Issue by xvitaly** [openzim/libzim#757]
Google Test since version 1.13.0 requires C++14:
```
[2/133] g++ -Itest/template.p -Iinclude -I../include -Isrc -I../src -fdiagnostics-color=always -Wall -Winvalid-pch -std=c++11 -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -DGTEST_HAS_PTHREAD=1 -pthread -DWITH_TEST_DATA=1 -MD -MQ test/template.p/template.cpp.o -MF test/template.p/template.cpp.o.d -o test/template.p/template.cpp.o -c ../test/template.cpp
FAILED: test/template.p/template.cpp.o 
g++ -Itest/template.p -Iinclude -I../include -Isrc -I../src -fdiagnostics-color=always -Wall -Winvalid-pch -std=c++11 -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -DGTEST_HAS_PTHREAD=1 -pthread -DWITH_TEST_DATA=1 -MD -MQ test/template.p/template.cpp.o -MF test/template.p/template.cpp.o.d -o test/template.p/template.cpp.o -c ../test/template.cpp
In file included from /usr/include/gtest/gtest-message.h:57,
                 from /usr/include/gtest/gtest-assertion-result.h:46,
                 from /usr/include/gtest/gtest.h:64,
                 from ../test/template.cpp:22:
/usr/include/gtest/internal/gtest-port.h:270:2: error: #error C++ versions less than C++14 are not supported.
  270 | #error C++ versions less than C++14 are not supported.
      |  ^~~~~
```

**Comment by kelson42** [comment]
@xvitaly I guess this could make the packaging difficult if we don't move?
@mgautierfr @veloman-yunkan Any challenge to implement/fix?

**Comment by xvitaly** [comment]
I can send a PR with fix.

**Comment by mgautierfr** [comment]
> @mgautierfr @veloman-yunkan Any challenge to implement/fix?

The challenge is that we must ensure that all the compiler we use to compile libzim/libkiwix/... are compatible with C++14
The list is there : https://en.cppreference.com/w/cpp/compiler_support/14

So we need :
- gcc >= 5
- clang >= 3.4
- msvc >= 19.10 (2015)

On ubuntu bionic we are at gcc-7 (Fedora is gcc-12)
On ubuntu bionic , clang is 6
On android, it seems ndk use clang 9
On windows (CI) we use Visual Studio 2019
For wasm, we use clang 16

However, we still use gcc 4.8.3 to crosscompile to armhf. We use the toolchain from https://github.com/raspberrypi/tools but it seems that this toolchain is deprecated and we can now use gcc provided by ubuntu packages directly (which seems to be gcc-7 on bionic)

We have to update the armhf crosscompilation before moving to C++14.

---

While we are here, we can also discuss about moving to C++17
We would need:
- gcc >= 7 (if we exclude file system library and other advanced features)
- clang >= 6 for most of the feature
- msvc >= 19.14 (?)

---

On top of that, bionic is eof in april of this year. After that we will move to Focal with a gcc-9 and clang-10

**Comment by kelson42** [comment]
OK for Focal, c++17 support benefits are still unclear (in our context).

**Comment by kelson42** [comment]
Depends on https://github.com/kiwix/kiwix-build/issues/587

**Comment by kelson42** [comment]
Depends on https://github.com/kiwix/kiwix-build/issues/598

**Comment by kelson42** [comment]
libzim does not build anymore on Debian unstable which requires as well C++14 https://github.com/openzim/libzim/actions/runs/5630822420/job/15296002629.

Like decided, we need now urgently to respect c++17 norm, but use max features of c++14 for max compatibility with older compilers.

**Comment by legoktm** [comment]
FWIW in Debian I added a patch to build with C++14 (https://salsa.debian.org/debian/libzim/-/commit/5c0a477dfaa8316fff9a08a18feeade5a48f01e4) and it seemed to be fine. (the updated libzim package is waiting for review still since I renamed it, finally :))

**Comment by kelson42** [comment]
@legoktm Thank you!
