### ISSUE TITLE
Compressed clusters should share a dictionary

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#76]
#This would increase the compression level (bigger dictionary) and save a lot of disk space because instead of having a LZMA dictionnary in each cluster we would have only one for the whole file.

Moved from https://phabricator.wikimedia.org/T148283

**Comment by mgautierfr** [comment]
I'm not sure of how lzma works, but there is no explicit dictionary. If there is one, it is "hidden" in the compressed content.
From what I understand of lzma compression algorithm (and dictionary compression algorithms in general), the dictionary is only structure in the de-compressor memory (not in the compressed content). This dictionary is build during the (de)compression process.

The problem with this algorithm, it that at the beginning of the content, there is no dictionary, so the compression algo need to store the content as literal (and it it to the dictionary). It cannot use reference to already content in the dictionary.
This is why the compression ratio is not good on small content. And this is why we compress a whole cluster (and not an article). First article is not well compressed, but other ones can "reuse" the dictionary.

It is possible (even with lzma) to give an already existing dictionary. This way, even for short content, we have a dictionary to use.

If we start to use a shared dictionary this become somehow a all new "problem" :
- We need a dictionary at compression step. We can create one "dry compressing" content and keep only the dictionary to further use. And as a good dictionary depend of the content compressed, we probably need a dictionary per type of content. It would not be efficient to compress css content with a dict created with html content.
- We need the dict at decompression step, so we need to pass the dict "of band". So store it in the zim file (where?)
- If this is efficient enough, we don't need cluster. We can simply compress the article content with a correct dict.

As a big improvement, we could decompress only one article at a time. No cluster to handle (and decompress).

But it would become a whole new zim format then.

**Comment by kelson42** [comment]
@veloman-yunkan What are you thoughs about that?

**Comment by veloman-yunkan** [comment]
@kelson42 If we talk about support for external dictionaries in zstd (which we can take advantage of and store various dictionaries as a non-user-visible items in the ZIM file), then it seems that we won't save much. Citing [Zstd documentation](https://github.com/facebook/zstd#the-case-for-small-data-compression) (the emphasis is mine):

> Dictionary gains are mostly effective in the first few KB. Then, the compression algorithm will gradually use previously decoded content to better compress the rest of the file.

But, as @mgautierfr has noted above, we can try to take advantage of the dictionary feature of zstd in order to get rid of clusters (but the gain here will be in speed, maybe at the cost of somewhat increased size of the ZIM file).

**Comment by kelson42** [comment]
@mgautierfr @veloman-yunkan Thank you for your helpful answers. To me, it seems that the (still somehow hypothetical advantages) don't counterbalance the investment we would have to do to get this done... I'm for sure not ready to start an effort to get ride of clusters. For this reason I will close this ticket as won't fix.
