### ISSUE TITLE
& symbol in search box still not redirecting to article

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#763]
From kiwix-tools created by [nijazm](https://github.com/nijazm): kiwix/kiwix-tools#588  

Okay, looks like you were fixing something but unsuccessfully. I just tested yesterday's nightly version of kiwix desktop and kiwix tools on Windows 11. Now just shows fulltext search autocomplete result for & symbol and when I click on it, it says `No results were found for "&"`. In search box it shows containing '&'. The same happens in kiwix serve (web browsers) and kiwix desktop app. Tested with english wikipedia 2021-12. The only difference is that now titles containing & redirect properly (previously they did not), e.g. `Me, Myself & Irene`

**Comment by kelson42** [comment]
> Do you know exactly which part of the code removes this?

@kelson42 No, I don't.

**Comment by kelson42** [comment]
As hypothesized in https://github.com/kiwix/kiwix-tools/issues/587#issuecomment-1354495921, the problem is that the ampersand symbol is treated as punctuation and is simply discarded during the creation of the title index as well as when running suggestion search on it.

Ideally, while building the title index we should handle article names consisting of a single symbol or word in a special way, letting those terms go into the title index as is despite any rules that drop punctuation and stopwords. Also we will have to enhance the suggestion search so that it accounts for such an addition to the title index.

**Comment by kelson42** [comment]
I would say that we try to clean the query (or the title to index). And if the clean query(/title) is empty then we use the original string instead of the cleaned one.
We don't care about what the original string is composed of.

**Comment by kelson42** [comment]
@mgautierfr Should we move this ticket to `openzim/libzim`?

**Comment by kelson42** [comment]
@veloman-yunkan Thank you for the explanation and analysis. Do you know exactly which part of the code removes this? Is that related the stop words? Your proposal seems worth to be considered IMO. I believe this special handling here might be pretty independant of any special character but impacting any really short titles.

**Comment by kelson42** [comment]
I don't understand this bug report. Can someone rephrase it please, https://github.com/kiwix/overview/blob/master/REPORT_BUG.md

**Comment by kelson42** [comment]
@mgautierfr If there is only stop word(s) OR punctions in a title we should keep them IMO. Does that make sense?

**Comment by kelson42** [comment]
@veloman-yunkan Considering we have currently a bit divergent priorities, would that be something you could fix?

**Comment by mgautierfr** [comment]
Here a comment in https://github.com/kiwix/kiwix-tools/issues/588#issuecomment-1439806027 lost during transfer of the issue in libzim repository :

>I would say that we try to clean the query (or the title to index). And if the clean query(/title) is empty then we use the original string instead of the cleaned one.
We don't care about what the original string is composed of.

**Comment by veloman-yunkan** [comment]
@mgautierfr The comment was not lost - it's [here](https://github.com/openzim/libzim/issues/763#issuecomment-1441813536). But the authorship of the idea was definitely impacted.

**Comment by veloman-yunkan** [comment]
It turns out that the current version of libzim doesn't use stopwords when indexing, and doesn't use them in suggestion search. Thus the issue is restricted to titles consisting entirely of punctuation.
