### ISSUE TITLE
Add Apple silicon support.

### ISSUE THREAD

**Issue by FledgeXu** [openzim/libzim#764]
relative to: https://github.com/openzim/mwoffliner/issues/1793

**Comment by kelson42** [comment]
AFAIK the libzim compiles on macOS. What is the problem?

**Comment by FledgeXu** [comment]
If `download.openzim.com` does not offer the `macos-arm64` binary, `node-libzim` will crash when users use it on Apple silicon Mac, because `node-libzim` only downloads the `macos-x84_64` binary.

**Comment by FledgeXu** [comment]
See this issue: https://github.com/openzim/mwoffliner/issues/1793

**Comment by kelson42** [comment]
OK, its a feature request for kiwix-build. https://github.com/kiwix/kiwix-build/issues/570
