### ISSUE TITLE
Reintroduce `Entry::getItem` optimization in next api/abi release.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#769]
PR https://github.com/openzim/libzim/pull/768 remove interesting optimization but it was necessary as the change introduced a ABI break.
We should reintroduce it in the next release of libzim with ABI break

**Comment by kelson42** [comment]
@mgautierfr I'm not sure there is anything to do here as you have made 8.1.1 in a branch?!

**Comment by mgautierfr** [comment]
This is just a reminder to not forget to reintroduce the change.
We could reintroduce it right now, it it would force us to make a version `9`.
As this change is just a really small optimization, I prefer to postpone it and make it when other change forces us to have a major version change.

**Comment by kelson42** [comment]
@mgautierfr We should really do that right now IMO
