### ISSUE TITLE
release 8.1.1 was not completed

### ISSUE THREAD

**Issue by chenrui333** [openzim/libzim#777]
👋 it looks like the 8.1.1 release build was not competed, [action run ref](https://github.com/openzim/libzim/actions/runs/4489838818/jobs/7896744746)

it kind of blocks the homebrew release for the version bump, https://github.com/Homebrew/homebrew-core/pull/126370

**Comment by mgautierfr** [comment]
The CI on the tag is not relevant. What is missing is a github release (https://github.com/openzim/libzim/releases/) at it seems that it is what homebrew guy are looking for.
But tag is ok (https://github.com/openzim/libzim/tags)

**Comment by mgautierfr** [comment]
Done (https://github.com/openzim/libzim/releases/tag/8.1.1)
