### ISSUE TITLE
Correctly export public api

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#780]
On windows (msvc?), functions are by default hidden (in contrast to gcc).

We must correctly export our public API.

Either with `__declspec(dllexport)` in function/method declaration (to do with a macro for portability)
Or with a `.def` file.

See #741 and https://github.com/mesonbuild/meson/issues/7838

**Comment by xiaoyifang** [comment]
Can you tell me which class header files need to be exported .
At first I thought it should be the` include` folder,
But it seems some header files in the `src `folder also need to be exported.
