### ISSUE TITLE
ZIM file Metadata should offer a way to specify license

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#79]
This is an important information and for now there is no otherway than saving it in the ZIM file content itself.

Moved from https://phabricator.wikimedia.org/T128578

**Comment by kelson42** [comment]
@rgaudin @mgautierfr What about finally move on this, I woukd propose to start with an non-mandatory new ZIM Metadata `Licence`. What do you think?

**Comment by rgaudin** [comment]
already in the spec

**Comment by kelson42** [comment]
Indeed!!!?!?!
