### ISSUE TITLE
Support fulltext query with wildcard

### ISSUE THREAD

**Issue by xiaoyifang** [openzim/libzim#794]
Some questions:
1. does libzim support query wildcard string ,such as "he*o"
https://xapian.org/docs/apidoc/html/classXapian_1_1QueryParser.html#:~:text=FLAG_WILDCARD-,Support%20wildcards.,-At%20present%20only
<s>3. does libzim support CJK tokenize/query?</s> See #802

**Comment by mgautierfr** [comment]
> does libzim support query wildcard string ,such as "he*o"

Mostly no.

If it is [getEntryByPath](https://libzim.readthedocs.io/en/latest/api/classzim_1_1Archive.html#_CPPv4NK3zim7Archive14getEntryByPathE16entry_index_type) or [findByPath](https://libzim.readthedocs.io/en/latest/api/classzim_1_1Archive.html#_CPPv4NK3zim7Archive10findByPathENSt6stringE), the answer is clearly no. We are at the byte level and we search for exact match.
`findByPath` is searching for a prefix, so "foo" is equivalent to "foo.*" But that's all.

If it is fulltext search or suggestion search, no also. The query is passed to xapian which will parse it but we don't set `FLAG_WILDCARD `. But even if we set it, from the [documentation](https://xapian.org/docs/apidoc/html/classXapian_1_1QueryParser.html#ae96a58a8de9d219ca3214a5a66e0407ea99e75d48aca2ebbf477572d855c82e36), only "foo*" would be supported, not "he*o".
For suggestion search, we use the [FLAG_PARTIAL](https://xapian.org/docs/apidoc/html/classXapian_1_1QueryParser.html#ae96a58a8de9d219ca3214a5a66e0407eae0b632c2f797fc7ae53c444f104072c7) which somehow add a `*` at the end of the query (see the doc for the details).

> does libzim support CJK tokenize/query?

Libzim works at byte level and the specification tell to store utf8.
So if you pass a utf8 encoded CJK string, it should works.

**Comment by xiaoyifang** [comment]
goldendict-ng has use xapian as fulltext engine too.  in order to search cjk character ,  FLAG_CJK_NGRAM has to pass to termgenerator.

https://xapian.org/docs/sourcedoc/html/classXapian_1_1TermGenerator.html#ad1dbf8af7a6b0d5a7f0dca5f1202a291a0b31ee76f4e202359c590645280c7027:~:text=for%20spelling%20correction.-,FLAG_CJK_NGRAM%C2%A0,-Enable%20generation%20of

If libzim support CJK search ,I can skip the zim dictionary's fulltext creation in goldendict-ng and use libzim to query zim's built-in fulltext ,which should save a lot of disk space.

**Comment by mgautierfr** [comment]
Hum.. Maybe we have to use the `FLAG_CJK_NGRAM` then. I don't see how it could break things.

**Comment by xiaoyifang** [comment]
CJK character are not space delimited as English.    the default tokenize is wrong ,which lead to wrong query. 
" positional infirmation " has cost too much extra space(1x more disk space than without it),  it is a different issue with CJK .   CJK flag can work without the positional information .

**Comment by kelson42** [comment]
@xiaoyifang I would like to move forward with ticket. One of the problem is that the feature request is no very clear from the user perspective. Can we please clarify this:
* Do we talk about the Xapian based suggestions? About fulltext search? Both?
* what is exactly meant with cjk character search? On what this applies exactly:xapian suggestions or/and ft search?

**Comment by xiaoyifang** [comment]
I talked about fulltext search .  I do not know much about the xapian-based suggestions.

> what is exactly meant with «  cjk character search »? Can we have a concrete use case example? 

I have migrated Goldendict fulltext engine to xapian.  During the migration ,I have found that if not enabled CJK flag

```
    Xapian::TermGenerator indexer;
    //  Xapian::Stem stemmer("english");
    //  indexer.set_stemmer(stemmer);
    //  indexer.set_stemming_strategy(indexer.STEM_SOME_FULL_POS);
    indexer.set_flags( Xapian::TermGenerator::FLAG_CJK_NGRAM );
```

it will give less results when searched in Chinese Dictionary.

**Comment by kelson42** [comment]
> I talked about fulltext search . I do not know much about the xapian-based suggestions.

The suggestion search is a way to fournish article title base suggestions (completion approach).

**Comment by kelson42** [comment]
This tickets requests that we allow wildcard fulltext searches. Here my remarks:
* This feature has been ignore so far in the history of Kiwix has I think this is not really needed, or at least not a priority.
* I would be ready to consider it if it would be pretty easy and without strong impact at user level (the biggest of it, being that the xapian index size).

@mgautierfr Do you think we could implement this feature without user impact?

**Comment by xiaoyifang** [comment]
> > it will give less results when searched in Chinese Dictionary.
> 
> Please open a dedicated ticket for this. To me this sounds like a serious bug and I'm in favour to fix this ASAP if the chinese search fails to work properly.

https://github.com/openzim/libzim/issues/802

**Comment by kelson42** [comment]
CJK has been implement which was definitly the most important for the rest I think we will pass on wildcards.

**Comment by tedaz** [comment]
As of Kiwix android version 3.12.0, this issue still unfixed.

**Comment by kelson42** [comment]
This is fixed in the libzim, but some ZIM files are still built with an older libzim.

**Comment by tedaz** [comment]
> This is fixed in the libzim, but some ZIM files are still built with an older libzim.

The bug https://github.com/openzim/libzim/issues/794 seems fixed in Jan 2023, however the zim file "wikipedia Apr 2024" still cannot be correctly searched with Kiwix Android 3.12.0.

The zim file "wikipedia Apr 2024" works correctly with Kiwix Android 3.6.0.

It is the Kiwix Android's bug, not the zim file's bug.
