### ISSUE TITLE
Somehow broken Windows dllexport for DLLs

### ISSUE THREAD

**Issue by xiaoyifang** [openzim/libzim#795]
https://github.com/openzim/libzim/pull/792

the  `__declspec(dllexport)` on the class has not export all the public methods to dll .

This is the method in the zim-8.dll on Windows.
[method in dll.txt](https://github.com/openzim/libzim/files/11465055/method.in.dll.txt)

many public method has not been export to the dll.  

I also tried to put `__declspec(dllexport)` on class method directly ,   even less methods were exported to the dll.

**Comment by mgautierfr** [comment]
It seems that only constructors (and somehow implicit method) have been export.
Maybe we need to add the `LIBZIM_API` to the methods also (and not only on to the class declaration).

**Comment by xiaoyifang** [comment]
I have tried to add LIBZIM_API to the methods ,  still have not been exported .

**Comment by mgautierfr** [comment]
Maybe we need to also use `__stdcall`  https://learn.microsoft.com/en-us/cpp/cpp/stdcall?view=msvc-170 ?

**Comment by xiaoyifang** [comment]
some libzim classes are derived from std::xxx class , does this have some relation with the exportdll?

**Comment by xiaoyifang** [comment]
[zim-8.zip](https://github.com/openzim/libzim/files/11522564/zim-8.zip)

the weird thing is that the above dll is generate by vcpkg seems correct.

**Comment by xiaoyifang** [comment]
handled in this https://github.com/openzim/libzim/pull/796

When put `LIBZIM_EXPORT_DLL` in privateConf ,  the generated `config.h` was not included in zim.h . That's why it does not work 
while `-DLIBZIM_EXPORT_DLL` works.

**Comment by xiaoyifang** [comment]
https://github.com/microsoft/vcpkg/pull/31383
