### ISSUE TITLE
[question]help ,how to  iterate all the article

### ISSUE THREAD

**Issue by xiaoyifang** [openzim/libzim#798]
is this the correct way to iterate all the articles?
pseudocode
```
zim::Archive archive('file');
auto n = archive.getArticleCount();
for(i=0;i<n;i++){
            auto entry    = archive.getEntryByPath( i );     
            //getEntryByPath seems not proper ,is there an method such as getArticleByPath(i)
            auto item     = entry.getItem( true );
           
            //item is the article.
}
```
getEntryByPath seems not proper ,is there a method such as getArticleByPath(i)

**Comment by kelson42** [comment]
@xiaoyifang I woukd recommend to look at how zimdump does it. Here for example https://github.com/openzim/zim-tools/blob/main/src/zimdump.cpp#L148

**Comment by xiaoyifang** [comment]
Thanks ,this seems ok.

On more question
Is there any property in entry to indicate that the the current entry is article or not?

**Comment by kelson42** [comment]
@xiaoyifang What could it be if not an article?

**Comment by xiaoyifang** [comment]
> What could it be if not an article?

js,css etc all could be in this entry.
