### ISSUE TITLE
Support CJK index creation and query

### ISSUE THREAD

**Issue by xiaoyifang** [openzim/libzim#802]
Current situation:
https://download.kiwix.org/zim/wikipedia/wikipedia_zh_mathematics_mini_2023-05.zim

fulltext search `平方`  
gives no result.
![image](https://github.com/openzim/libzim/assets/105986/c8768cf4-fbb5-4716-aa8b-a17c2764a9b2)

actually there are much more articles contain this word.
![image](https://github.com/openzim/libzim/assets/105986/cec61519-890c-43c4-b278-a69b74c75eb9)
![image](https://github.com/openzim/libzim/assets/105986/0616a369-710f-4d95-a7b3-b9c156daf11e)

english word seems ok.
![image](https://github.com/openzim/libzim/assets/105986/b2149799-1306-483b-b45c-d384200d4655)
The `No` seems another issue.

CJK characters have to be indexed with CJK flags

Creation:
```
   Xapian::TermGenerator indexer;

    indexer.set_flags( Xapian::TermGenerator::FLAG_CJK_NGRAM );
```
Query:
```
      Xapian::QueryParser::feature_flag flag = Xapian::QueryParser::FLAG_DEFAULT;
      if( searchMode == FTS::Wildcards )
        flag = Xapian::QueryParser::FLAG_WILDCARD;
      Xapian::Query query = qp.parse_query( query_string, flag|Xapian::QueryParser::FLAG_CJK_NGRAM );
```

_Originally posted by @kelson42 in https://github.com/openzim/libzim/issues/794#issuecomment-1573246698_

**Comment by mgautierfr** [comment]
@xiaoyifang The PR #806 should fix this.
Can you test on your side ? I'm not sure to fully understand what is the expected behavior :)

**Comment by xiaoyifang** [comment]
From the unittest you provided .it seems ok.
