### ISSUE TITLE
Cannot search Japanese characters with diacritics inside Kiwix iOS

### ISSUE THREAD

**Issue by haoming-li-ling** [openzim/libzim#821]
I am using Wiktionary on Kiwix iOS 3.1 build 116. For words containing characters such as が、ず、ぱ, they cannot be searched directly in Wiktionary; I must search for the words with the characters replaced by か、す、は instead.

**Comment by kelson42** [comment]
@haoming-li-ling Thank you for reporting this bug. We confirm the problem. This bug has already been reported in ticket #794. Therefore I will close this issue as « duplicate ».
