### ISSUE TITLE
[REGRESSION] Fulltext search crashes on javascript libzim since version 8.2.1

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#828]
See https://github.com/openzim/javascript-libzim/issues/58

**Comment by Jaifroid** [comment]
@mgautierfr How do you suggest we proceed? Given that v8.2.1 can be compiled from source correctly (see [sample run here](https://github.com/openzim/javascript-libzim/actions/runs/6606592181/job/17942944428#step:6:8149) and outcome of test on this [here](https://github.com/openzim/javascript-libzim/actions/runs/6606592181/job/17942944428#step:9:38)), can we adjust the build pipeline for `libzim.a` here to match? If we can identify exactly which source packages are different, we can eliminate them one-by-one until we identify the culprit.

More info on testing: tests of basic functions (loading ZIM, checking article count, loading an article by path, searching with Xapian) can be run against compiled versions of the WASM either from `libzim.a` or from source code. See instructions here: https://github.com/openzim/javascript-libzim#tests. Any `libzim.a` can be easily compiled by placing it in `/build/lib/`, making sure nothing else is there, and any previously build WASMs are removed (e.g. by running `make clean` first), then following the (updated) instructions to build with docker here: https://github.com/openzim/javascript-libzim#steps-to-recompile-from-source-with-docker (despite the title of those instructions, if `libzim.a` is already in `/build/lib`, it shouldn't attempt to recompile it).

I'm happy to do any testing.

**Comment by mgautierfr** [comment]
Can you test with https://tmp.kiwix.org/ci/dev_preview/update_icu/libzim_wasm-emscripten-2023-10-25.tar.gz ?

This is a test build with ICU 71.1. Not yet ready for publishing but I least we could know if it is the root cause.

**Comment by Jaifroid** [comment]
Thanks, will do.

**Comment by Jaifroid** [comment]
@mgautierfr Yay!

![image](https://github.com/openzim/libzim/assets/4304337/0bd47227-530c-4202-bc6b-1a88ca7a9b5f)

I'll make a test PR to see if I can replicate this on GitHub, but I don't see why it shouldn't work. Just good to double-check.

Thank you!

**Comment by Jaifroid** [comment]
Also passing when built as a release artefact (rather than as a nightly). Not actually released of course. See https://github.com/openzim/javascript-libzim/pull/63#issuecomment-1780018137.

**Comment by mgautierfr** [comment]
Good to know !
It confirms it is a ICU version issue. We have to update it to a recent version but it may take a bit of time as it has impact in the way we publish kiwix-android.

**Comment by Jaifroid** [comment]
@mgautierfr No problem. Possibly it could be used in the nightly release first, or would that break the Android nightly build chain? It would allow the javascript-libzim nightlies to start working again.

**Comment by kelson42** [comment]
> Good to know !
> It confirms it is a ICU version issue. We have to update it to a recent version but it may take a bit of time as it has impact in the way we publish kiwix-android.

@mgautierfr Please create a dedicated ticket so we understand all the challenges. We will anyway put this high on the prio list.

**Comment by kelson42** [comment]
@mgautierfr What is the status? Is this ticket fixed by https://github.com/kiwix/kiwix-build/pull/642 ?

**Comment by Jaifroid** [comment]
@kelson42 Yes [last nightly build](https://github.com/openzim/javascript-libzim/actions/runs/6752235229/job/18357353083) succeeded. As far as I'm concerned, this ticket can be closed.
