### ISSUE TITLE
Failling iOS cross-compilation on macOS 13 (CI)

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#834]
Failling CI is crosscompiling from macos-13 to iOS.
Cross compiling use a "meson_cross_file" file found in https://tmp.kiwix.org/ci/deps2_osx_iOS_x86_64_libzim.tar.xz (step "Install Deps") generated by kiwix-build.
This file tells which compiler to use.

I **suppose** that this archive is build by kiwix-build for macos-12 and that the binaries paths have changed between macos-12 and macos-13

From https://github.com/openzim/libzim/pull/832#issuecomment-1784909058

**Comment by kelson42** [comment]
No emergency on that for the moment as we compile production on macOS 12.

**Comment by rgaudin** [comment]
There is no link to an action here ; PR linked has been merged. Is this still valid?

**Comment by kelson42** [comment]
@rgaudin You can remove exclusion at https://github.com/openzim/libzim/blob/176c73b44c1a696160191ad757ce45d8cf48b4e7/.github/workflows/ci.yml#L33

**Comment by rgaudin** [comment]
done
