### ISSUE TITLE
Add option for disabling tests

### ISSUE THREAD

**Issue by data-man** [openzim/libzim#849]
Also I propose rename `test` directory to `tests`.

**Comment by kelson42** [comment]
@data-man Which commands exactly run the tests and for which you would like to have a variant which would not?

**Comment by data-man** [comment]
I'm currently commenting out `subdir('test')` in `meson.build` for speed up compilation.

**Comment by data-man** [comment]
The possible patch:
```diff
diff --git a/meson.build b/meson.build
index 53b7522..13bfbae 100644
--- a/meson.build
+++ b/meson.build
@@ -91,7 +91,9 @@ subdir('src')
 if get_option('examples')
   subdir('examples')
 endif
-subdir('test')
+if get_option('tests')
+subdir('tests')
+endif
 if get_option('doc')
   subdir('docs')
 endif
diff --git a/meson_options.txt b/meson_options.txt
index f1bf953..253c773 100644
--- a/meson_options.txt
+++ b/meson_options.txt
@@ -18,6 +18,8 @@ option('doc', type : 'boolean', value : false,
   description : 'Build the documentations.')
 option('examples', type : 'boolean', value : true,
   description : 'Build the examples.')
+option('tests', type : 'boolean', value : true,
+  description : 'Build the tests.')
 option('with_xapian', type : 'boolean', value: true,
   description: 'Build libzim with xapian support')
 option('test_data_dir', type : 'string', value: '',
```

**Comment by kelson42** [comment]
test are not executed by running:
```
meson . build
ninja -C build
```
like written in the `README.md`, so I don't understand the problem.

**Comment by data-man** [comment]
> I don't understand the problem.

Problem is compilation.

**Comment by kelson42** [comment]
@data-man Please give me clear reproduction steps, what it does and what you expect to be done.

**Comment by data-man** [comment]
```
meson . build
ninja -C build
```
> ninja: Entering directory `build'
[0/133] ...

After commenting out `subdir('test')` in `meson.build`:
> ninja: Entering directory `build'
[1/46] ...

I don't want to compile unnecessary files.

**Comment by kelson42** [comment]
Got it!
