### ISSUE TITLE
Document ZIM major and minor versions

### ISSUE THREAD

**Issue by benoit74** [openzim/libzim#853]
We should:
- document what is ZIM minor 2 (of version 6)
- document more clearly:
  - what were major 1 to 5
  - what is backward compatible (e.g. an implementation capable to read ZIM 6 is capable to read ZIM 5 by design, since ZIM 6 is only an extension)
  - which libzim versions supports which ZIM versions

**Comment by mgautierfr** [comment]
> document what is ZIM minor 2 (of version 6)

This part is done

**Comment by kelson42** [comment]
I will complete at https://wiki.openzim.org/wiki/ZIM_file_format#Header

**Comment by kelson42** [comment]
I have completed an reshaped the documentation, see https://wiki.openzim.org/wiki/ZIM_file_format#Header

**Comment by benoit74** [comment]
I don't get what "Backward compatible" means in your table, or there are some mistakes in your values.

I would assume that when present on a version N it could means that "an implementation reading version N-1 is capable to read version N" or "an implementation reading version N is capable to read ZIMs in version N-1 by design" but I feel like none of them makes sense with the value you provided (based on my very limited understanding). Plus it conflicts with the meaning you gave to major / minor versioning in the table above. And we are not sure whether the compatibility refers to the previous minor or major version.

You should at least add a sentence making it clearer I think.

Did you forget about the libzim table? (explaining which libzim version is producing which ZIM version)

**Comment by mgautierfr** [comment]
The value (and the description) in the wiki are wrong.
At least for major 5. The extended cluster has been introduced by major version 6. (And it is why I've made a version 6)

**Comment by mgautierfr** [comment]
I have update the wiki.(https://wiki.openzim.org/w/index.php?title=ZIM_file_format&type=revision&diff=31347&oldid=31346) Please comment here if you agree or not with the changes.
