### ISSUE TITLE
Snippets highlight stem words instead of searched words.

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#86]
In kiwix-tools, when searching for `apple` for example, `apple` is stemmed to `appl`.
When asking to xapian to generate a snippet based on the article content, xapian will highlight the stemmed word (`appl`) instead of `apple`

This probably need a better indexing of the database with better handling of stemming (https://trac.xapian.org/ticket/750)

**Comment by kelson42** [comment]
@mgautierfr It seems there is a way to deal with that, see upstream bug. What stops us now to fix the bug?

**Comment by mgautierfr** [comment]
It is a pretty old issue. I'm not sure to remember correctly.
The upstream bug is more about openzim/libzim#324 (and is not fixed yet).

The highlighting in the snippets is made by xapian. We have to find the correct way to index the content to have the the searched word correctly highlighted.
We probably need to store the word along the stem in the database (for now, we store only the stem). It will increase the database size.

**Comment by maneeshpm** [comment]
@kelson42 `Xapian::MSet::snippet` provides a constructor that accepts a `Xapain::Stem` parameter. If we provide the same stemmer that was used to generate the query, snippets seem to be covering the reported case in this issue and the duplicate issue as well. So this is not exactly an upstream issue.
