### ISSUE TITLE
Last version of libzim seems to no be present in debian repo

### ISSUE THREAD

**Issue by mgautierfr** [openzim/libzim#863]
See : https://github.com/openzim/zim-tools/actions/runs/8130890684/job/22219595768?pr=316

**Comment by kelson42** [comment]
Now it is, see https://tracker.debian.org/pkg/libzim

The problem is that https://tracker.debian.org/pkg/libzim is different from https://tracker.debian.org/pkg/zimlib and that actually libzim is not listed on https://debian.kiwix.org
