### ISSUE TITLE
Upload new releases to http://www.openzim.org/download/

### ISSUE THREAD

**Issue by legoktm** [openzim/libzim#87]
Debian checks the download page to find new releases, so it hasn't picked up 3.0.0 or 3.1.0 yet. Also I think 3.1.0 is also missing a git tag?

**Comment by kelson42** [comment]
@mgautierfr @legoktm yes

**Comment by legoktm** [comment]
This needs to be resolved before Debian will be able to update libzim, which is needed to update libkiwix...

**Comment by kelson42** [comment]
@legoktm I have created download.kiwix.org to start to publish release more properly and the code to link git tags - travis - publication of src/bin tarball is ready. We will give it a try next week.

**Comment by legoktm** [comment]
OK, I've filed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884440 to update zimlib, which is waiting on the resolution of this issue :)

**Comment by kelson42** [comment]
@legoktm Thx, just to say that even if we are late, we are still on it. A top priority for us, should be available at any time from now.  Thank you for your patience.

**Comment by kelson42** [comment]
Remark: Updating libzim on Debian will in addition probably fail because of #112

**Comment by kelson42** [comment]
@legoktm Here it is :) http://download.kiwix.org/release/ (I will put the SSL certificate soon).

**Comment by legoktm** [comment]
@kelson42 I don't see libzim there?

**Comment by legoktm** [comment]
And the git tag for 3.1.0 is still missing :)

**Comment by kelson42** [comment]
Download.openzim.org and 3.0.0 tag is there
