### ISSUE TITLE
Correctly handle the lib soname.

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#89]
_From @mgautierfr on March 6, 2017 17:23_

With the 1.3 version, we add a new API (`getOffset`, ...), but we haven't change the soname.

So, the linker may link with the wrong library.
This is what happen on a debian if the zimlib (1.2) deb package is installed.
As the system libzim.so and the locally built one have the same soname, the linker use the first one (1.2) and fails because it cannot found `getOffset`.

The actual soname is `2.0.0`. We should change it to `2.1.0`

_Copied from original issue: wikimedia/openzim#8_

**Comment by kelson42** [comment]
@mgautierfr I think you have fixed the problem meanwhile?!

**Comment by mgautierfr** [comment]
Yes, I update the soname at each release.
