### ISSUE TITLE
Purpose and constraints of LongDescription should be clarified

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#890]
In particular how it articulates with Description metadata.

**Comment by rgaudin** [comment]
See https://github.com/openzim/zim-tools/issues/408

**Comment by kelson42** [comment]
@rgaudin I have [precised the nature of the `LongDescription` ZIM Metadata](https://wiki.openzim.org/w/index.php?title=Metadata&type=revision&diff=31418&oldid=31373). Does it make sense to you?

**Comment by rgaudin** [comment]
Yes, that settles it ; thank you
