### ISSUE TITLE
Remove bzip2 support

### ISSUE THREAD

**Issue by kelson42** [openzim/libzim#9]
I do not see any reason why we should keep it.

**Comment by mgautierfr** [comment]
The only potential reason is to handle old zim created with bzip2 compression.
If you think we don't have to support them, I will be glade to merge your PR :)

**Comment by kelson42** [comment]
I wonder if such files have been created ever! Probably an inheritance of the old ZENO format. So, let's go.

**Comment by kelson42** [comment]
@mgautierfr Could you please merge this?

**Comment by kelson42** [comment]
This has been merged.
