### ISSUE TITLE
compilation failed

### ISSUE THREAD

**Issue by LAfricain** [openzim/libzim#91]
I tried to install the libzim from github, but instructions seems not so clear for me. First need I to clone the git?
I follow all the instruction till the Compilation section. When need I to clone the git repo, in wich folder need I to work?
`sudo apt-get install liblzma-dev libmagic-dev zlib1g-dev libgumbo-dev` this is ok but :
`cd ../zimlib && ./autogen.sh && ./configure && make && cd ../zimwriterfs`
Where can I find the zimlib folder?

Is cd ../zimlib right? Maybe you want to write **libzim**?
Because the `make` still failed. But I did not run it.
Meson and ninja seems to run well... but the end of the install with ninja have also problem:
`..github/libzim/build$ sudo ninja install`
`log: reading configuration file: install`
`die: error: unable to read configuration file`

Maybe the readme can be more explicite :)

**Comment by kelson42** [comment]
There is not "autogen.sh" in libzim git master HEAD
https://github.com/openzim/libzim

Read the libzim README and follow all the steps rigorously.

**Comment by LAfricain** [comment]
> There is not "autogen.sh" in libzim git master HEAD

Yes I know it's just a question because in the readme of zimwriterfs it is write:

> On Debian, you can ensure these are installed with:
sudo apt-get install liblzma-dev libmagic-dev zlib1g-dev libgumbo-dev
cd ../zimlib && ./autogen.sh && ./configure && make && cd ../zimwriterfs

I didn't do this. But I would like just to understand the meaning of it.
I follow the differents steps of the readme. But as I'm a newbie for all this, I don't understand the meaning of the commands :)
But I run all the command in the same folder named zim_nv:
`cyrille@W54:~/Documents/github/zim_nv$ virtualenv -p python3 ./`
And all the following...

After cloning ninja the console is like that:
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv$ `
I continue:
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv/ninja$ ./configure.py --bootstrapbootstrapping ninja...
warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.
wrote build.ninja.
bootstrap complete.  rebuilding...
[26/26] LINK ninja`
Then:
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv$ mkdir build`
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv$ `
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv$ meson . build`
`Error during basic setup:`
`Neither directory contains a build file meson.build.`

I stopped here (this time the last time I went further.

**Comment by kelson42** [comment]
It looks like the zimwriterfs is a bit outdated regarding libzim, I have proposed a fix here:
https://github.com/openzim/zimwriterfs/pull/32

**Comment by kelson42** [comment]
@LAfricain I do not have an explanation why `meson . build` fails. That said Meson seems to complain that there is no `meson.build` in the `libzim` directory. I suspect you do not have the last version of the git repository. What does `git show HEAD` gives you?

**Comment by LAfricain** [comment]
Git show HEAD:
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv/libzim$ git show HEAD`
`commit 06466fa404b7cc26f18d19e835e758411384b297`
`Merge: 5436b34 68a64f4`
`Author: Matthieu Gautier <matthieu.gautier@mgautier.fr>`
`Date:   Tue Nov 14 17:55:33 2017 +0100`
 `   Merge pull request #88 from openzim/geo_loc`
`    All zimlib to do geo query if avalaible in xapian database.`

Today I run all again. But first I cloned the libzim repo (because the other times I didn't know which moment to clone it). And now it said : Meson is not installed. I install it with the official ubuntu repo. It uninstall ninja, and installed meson and ninja-build from official repo.
And again:
`cyrille@W54:~/Documents/github/zim_nv$ virtualenv -p python3 ./`
`Already using interpreter /usr/bin/python3`
`Using base prefix '/usr'`
`New python executable in /home/cyrille/Documents/github/zim_nv/bin/python3`
`Not overwriting existing python script /home/cyrille/Documents/github/zim_nv/bin/python (you must use` `/home/cyrille/Documents/github/zim_nv/bin/python3)`
`Installing setuptools, pkg_resources, pip, wheel...done.`
`cyrille@W54:~/Documents/github/zim_nv$ source bin/activate`
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv$ pip3 install meson`
`Requirement already satisfied: meson in ./lib/python3.5/site-packages`
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv$ hash -r`
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv$ cd ninja/`
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv/ninja$ git checkout release`
`Déjà sur 'release'`
`Votre branche est à jour avec 'origin/release'.`
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv/ninja$ ./configure.py --bootstrapbootstrapping ninja...`
`warning: A compatible version of re2c (>= 0.11.3) was not found; changes to src/*.in.cc will not affect your build.`
`wrote build.ninja.`
`bootstrap complete.  rebuilding...`
`[25/25] LINK ninja`
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv/ninja$ cp ninja ../bin`
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv/ninja$ cd ..`
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv$ meson . build`
`Error during basic setup:`
`Neither directory contains a build file meson.build.`
`(zim_nv) cyrille@W54:~/Documents/github/zim_nv$`

> It looks like the zimwriterfs is a bit outdated regarding libzim, I have proposed a fix here:
Your fixe is better, this avoids confusion.

**Comment by kelson42** [comment]
@LAfricain 

Your repo is not in the good state... You do not have the file "meson.build" in the directory probably. Just remove your `zim_nv` directory and clone it again.

**Comment by LAfricain** [comment]
> directory and clone it again.

Libzim?

**Comment by kelson42** [comment]
yes

**Comment by LAfricain** [comment]
Ok I found the problem, after cloning libzim, we need to move in the libzim directory! As it was not specified I didn't it... Maybe we can add this in the readme at the top: "After cloning libzim move to the directory cd libzim..."

And I don't if it is good, but if with the meson an ninja from the official repo it is possible to work then we can add it in the "Dependencies"?

But the compilation of zimwriterfs doesn't yet run...

**Comment by LAfricain** [comment]
I tried to install libzim on an other pc but I couldn't. First I need to install more dependancies, like:
* python3-pip
* Ninja-build
* re2c
* libxapian-1.3-5 (this one I'm not sure it is useful, because as I see an error with xapian, I tried to install it :) )
Then I went till the command `ninja` with this error:
`(libzim) lafricain@U30Sd:~/zim2/libzim/build$ ninja
[2/10] Compiling C++ object 'src/zim@sha/search_iterator.cpp.o'.
FAILED: c++  -Isrc/zim@sha -Isrc -I../src -Iinclude -I../include -I/usr/include/x86_64-linux-gnu -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -Werror -Wall -fPIC -pthread -MMD -MQ 'src/zim@sha/search_iterator.cpp.o' -MF 'src/zim@sha/search_iterator.cpp.o.d' -o 'src/zim@sha/search_iterator.cpp.o' -c ../src/search_iterator.cpp
../src/search_iterator.cpp: In member function ‘std::__cxx11::string zim::search_iterator::get_snippet() const’:
../src/search_iterator.cpp:178:48: error: ‘class Xapian::MSet’ has no member named ‘snippet’
     return internal->search->internal->results.snippet(htmlParser.dump, 500);
                                                ^
[2/10] Compiling C++ object 'src/zim@sha/search.cpp.o'.
FAILED: c++  -Isrc/zim@sha -Isrc -I../src -Iinclude -I../include -I/usr/include/x86_64-linux-gnu -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -Werror -Wall -fPIC -pthread -MMD -MQ 'src/zim@sha/search.cpp.o' -MF 'src/zim@sha/search.cpp.o.d' -o 'src/zim@sha/search.cpp.o' -c ../src/search.cpp
../src/search.cpp: In function ‘void zim::{anonymous}::setup_queryParser(Xapian::QueryParser*, Xapian::Database&, const string&, const string&)’:
../src/search.cpp:103:18: error: ‘class Xapian::SimpleStopper’ has no member named ‘release’
         stopper->release();
                  ^
../src/search.cpp: In member function ‘zim::Search::iterator zim::Search::begin() const’:
../src/search.cpp:211:45: error: invalid conversion from ‘int’ to ‘Xapian::Database::Internal*’ [-fpermissive]
         Xapian::Database database(databasefd);
                                             ^
In file included from /usr/include/xapian.h:50:0,
                 from ../src/search_internal.h:26,
                 from ../src/search.cpp:22:
/usr/include/xapian/database.h:99:11: note:   initializing argument 1 of ‘Xapian::Database::Database(Xapian::Database::Internal*)’
  explicit Database(Internal *internal);
           ^
../src/search.cpp:261:9: error: ‘GreatCircleMetric’ is not a member of ‘Xapian’
         Xapian::GreatCircleMetric metric;
         ^
../src/search.cpp:262:9: error: ‘LatLongCoord’ is not a member of ‘Xapian’
         Xapian::LatLongCoord centre(latitude, longitude);
         ^
../src/search.cpp:263:9: error: ‘LatLongDistancePostingSource’ is not a member of ‘Xapian’
         Xapian::LatLongDistancePostingSource ps(valuesmap["geo.position"], centre, metric, distance);
         ^
../src/search.cpp:265:34: error: ‘ps’ was not declared in this scope
           query = Xapian::Query(&ps);
                                  ^
../src/search.cpp:267:81: error: ‘ps’ was not declared in this scope
           query = Xapian::Query(Xapian::Query::OP_FILTER, query, Xapian::Query(&ps));
                                                                                 ^
ninja: build stopped: subcommand failed.
`

**Comment by kelson42** [comment]
@LAfricain What is the bug?

**Comment by LAfricain** [comment]
"Build stopped" doesn't mean that it failed? It runs?

**Comment by kelson42** [comment]
Meson should complain abou (the version of) Xapian.

**Comment by LAfricain** [comment]
On Ubuntu 16.04, I have :
Package: libxapian-1.3-5
Version: 1.3.4-0ubuntu6
Or:
sudo apt show libxapian22v5
Package: libxapian22v5
Version: 1.2.22-2

**Comment by kelson42** [comment]
Uninstall the libxapian dev package. probably "libxapian-dev"

**Comment by LAfricain** [comment]
Before I removed libxapian-dev:
lafricain@U30Sd:~/zim2/libzim$ meson . build
The Meson build system
Version: 0.43.0
Source dir: /home/lafricain/zim2/libzim
Build dir: /home/lafricain/zim2/libzim/build
Build type: native build
Project name: libzim
Native C compiler: cc (gcc 5.4.0)
Native C++ compiler: c++ (gcc 5.4.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.28)
Native dependency zlib found: YES 1.2.8
Native dependency liblzma found: YES 5.1.0alpha
Native dependency xapian-core found: YES 1.2.22
Dependency threads found: YES
Native dependency icu-i18n found: YES 55.1
Configuring config.h using configuration
Dependency GTest found: NO
Executing subproject gtest.
Project name: gtest
Native C++ compiler: c++ (gcc 5.4.0)
Build targets in project: 2
Subproject gtest finished.
Found a fallback subproject subprojects/gtest for gtest
Build targets in project: 7
Found ninja-1.5.1 at /usr/bin/ninja

After I remove libxapian-dev:

lafricain@U30Sd:~/zim2/libzim$ meson . build
The Meson build system
Version: 0.43.0
Source dir: /home/lafricain/zim2/libzim
Build dir: /home/lafricain/zim2/libzim/build
Build type: native build
Project name: libzim
Native C compiler: cc (gcc 5.4.0)
Native C++ compiler: c++ (gcc 5.4.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.28)
Native dependency zlib found: YES 1.2.8
Native dependency liblzma found: YES 5.1.0alpha
Dependency xapian-core found: NO
Dependency threads found: YES
Native dependency icu-i18n found: YES 55.1
Configuring config.h using configuration
Dependency GTest found: NO
Executing subproject gtest.
Project name: gtest
Native C++ compiler: c++ (gcc 5.4.0)
Build targets in project: 2
Subproject gtest finished.
Found a fallback subproject subprojects/gtest for gtest
Build targets in project: 7
Found ninja-1.5.1 at /usr/bin/ninja

**Comment by kelson42** [comment]
Xapian is not installed... so it's clear it won't work. You need to download the last version from xapian.org, compile and install it.

**Comment by LAfricain** [comment]
> Xapian is not installed... 

Yes of course, you said to me to uninstall it :) Ok I'll download the last version... It becomes difficult, install ninja, manson, xapian, libzim, finally zimwriterfs :) I hope for a deb.

**Comment by LAfricain** [comment]
With the new version of xapian I compiled successfully libzim. I wrote a new Readme, if it can help.
[README.txt](https://github.com/openzim/libzim/files/1485429/README.txt)
I can found the library in /usr/local/lib/x86_64-linux-gnu/libzim.so.3.1.0
I you want to verify :
`lafricain@U30Sd:~/zim2/libzim/build$ sudo ninja install`
`[sudo] Mot de passe de lafricain : `
`[1/1] Installing files.`
`Installing src/libzim.so.3.1.0 to /usr/local/lib/x86_64-linux-gnu/libzim.so.3.1.0`
`Installing article.h to /usr/local/include/zim`
`Installing blob.h to /usr/local/include/zim`
`Installing error.h to /usr/local/include/zim`
`Installing file.h to /usr/local/include/zim`
`Installing fileheader.h to /usr/local/include/zim`
`Installing fileiterator.h to /usr/local/include/zim`
`Installing search.h to /usr/local/include/zim`
`Installing search_iterator.h to /usr/local/include/zim`
`Installing uuid.h to /usr/local/include/zim`
`Installing zim.h to /usr/local/include/zim`
`Installing articlesource.h to /usr/local/include/zim/writer`
`Installing zimcreator.h to /usr/local/include/zim/writer `

**Comment by kelson42** [comment]
@LAfricain Could you please make a PR if you have improvements for the README in mind?

**Comment by probonopd** [comment]
When I try to build without libxapian-dev, I am getting `../src/writer/xapianIndexer.h:27:20: fatal error: xapian.h: No such file or directory`.

Full build log:
https://api.travis-ci.com/v3/job/202409076/log.txt

My Travis CI build script:
https://github.com/probonopd/kiwix-desktop/blob/558cf3b6831303a5f6f05538c1d4ede591d0ddaa/.travis.yml

Am I missing something?
